### ISSUE TITLE
Support asymmetric bounds padding

### ISSUE THREAD

**Issue by csjames** [johnpryan/flutter_map#113]
FitBoundsOptions currently takes a Point, perhaps an EdgeInsets would be more appropriate, especially given the parameters name is padding. 

Asymmetric padding is supported by Google maps and I believe it is a useful feature

I'll take a look at doing it myself if the boss things the padding looks crap,

Thanks, James :)

**Comment by csjames** [comment]
Bump

**Comment by johnpryan** [comment]
thanks for filing an issue. I don't currently have plans to work on this but if you would like to make a PR I agree this would make more sense.

FitBounds options I believe was part of the port from Leaflet

**Comment by csjames** [comment]
I'll get it done, just need a bit of time  :)

Thanks! 
James

**Comment by johnpryan** [comment]
Thanks for filing an issue. I went through the PR and nitpicked a few things. If you have time to fix them up I can include them in the next release.

Thanks!

**Comment by johnpryan** [comment]
This is fixed now
