### ISSUE TITLE
No such method: latitude called on null

### ISSUE THREAD

**Issue by ghost** [johnpryan/flutter_map#124]
Hello,
Whenever I try to create a map I receive the error 

"  Exception has occurred.
NoSuchMethodError: The getter 'latitude' was called on null.
Receiver: null   
Tried calling: latitude"

locations services are enabled and the map works fine if im not running the debugger to catch exceptions, thank you

**Comment by Redhood27** [comment]
This error happens with the example app

**Comment by zhen1991** [comment]
Hi!
I am facing the same problem!
any update??
thnx:)

**Comment by Jack74r** [comment]
For me , work in example and my project but after update i have this issue.

**Comment by Arkangel12** [comment]
i thinks this happens because your map its getting null value in the center, it happens to me when i move between tabs, i fixes using a default LatLon but the problem with this i that the map does not get back in the state i was before move to another tab.

if someone know a work around for this please lmk

**Comment by johnpryan** [comment]
Without example code that reproduces, it's difficult to identify what the problem is. I'm going to close this as stale for now.

**Comment by kushankurxd** [comment]
Try conditionally 💯 
![image](https://user-images.githubusercontent.com/37204706/99143857-f3a3bf00-2686-11eb-8995-343e1fc19747.png)

**Comment by kushankurxd** [comment]
and you can try calling this function whenever u need user's current position
![image](https://user-images.githubusercontent.com/37204706/99143885-336aa680-2687-11eb-9388-f154085a1e75.png)

**Comment by kushankurxd** [comment]
**Packages used:** 👍 
flutter_map:
geolocator:

**Comment by Atheer2022** [comment]
> Try conditionally 💯
> ![image](https://user-images.githubusercontent.com/37204706/99143857-f3a3bf00-2686-11eb-8995-343e1fc19747.png)

thanks a lotttttttttttttttttt it works
