### ISSUE TITLE
map not fit perfect screen on ios 

### ISSUE THREAD

**Issue by gimox** [johnpryan/flutter_map#125]
Map view not fit flexible tag on ios device < X.

look at grey border.
It work on iphone X.

![error](https://user-images.githubusercontent.com/2871248/46355390-01418a80-c661-11e8-8cb0-2e20139a5aa5.jpeg)

```
return new Padding(
      padding: new EdgeInsets.all(0.0),
      child: new Column(
        children: [
          new Flexible(
            child: new FlutterMap(
              options: new MapOptions(
                  center: new LatLng(39.213695, 9.121050),
                  interactive: false,
                  minZoom: 12.0,
                  maxZoom: 19.0,
                  zoom: 16.5,
                  onTap: (latLng) {
                    print('tap callback  $latLng');
                  },
                  onPositionChanged: (MapPosition mapPos) {
                    print("pos changed $mapPos");
                  }),
              layers: [
                new TileLayerOptions(
                    offlineMode: false,
                    urlTemplate:
                        "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                    //  urlTemplate: "assets/offlinemaps/cagliari/{z}/{x}/{y}.png"),
                    subdomains: ['a', 'b', 'c']),
                new MarkerLayerOptions(markers: markers)
              ],
            ),
          ),
        ],
      ),
    );
```

**Comment by johnpryan** [comment]
Can you double check that you are using the latest version? (0.1.4)

**Comment by gimox** [comment]
I m using 0.1.4

**Comment by johnpryan** [comment]
Were you able to figure out what was causing this?

**Comment by gimox** [comment]
I m investigating,no risults for now. Flexible container fit correct all the space (ad you se in the pick has gray background). Maps appear ti ve not in the center.

**Comment by gimox** [comment]
ok some news... this is related to option.zoom.


this code has map without problem
```
 options: new MapOptions(
                 ...
                  maxZoom: 17.0,
                  zoom: 14.0,
                  ....
                 maxZoom: 18.0,
                  zoom: 17.0,
```
this code generate the problem

```
...
 maxZoom: 17.0,
 zoom: 16.5,
...
maxZoom: 17.0,
zoom: 15.5,
...
maxZoom: 17.0,
zoom: 14.5,
```

it seems that the problem appear when zoom is not int!!!

**Comment by jovanovski** [comment]
@gimox Thanks, saved me! `zoom` and `maxZoom` must be rounded doubles, with no decimal points.

**Comment by benoitskipr** [comment]
> gotcha. I would vote to re-open this now that this is a reproducible bug

@johnpryan yes, it should be reopened, it still happens as of today, and the zoom property still is a double, and should definitely be a int

**Comment by benoitskipr** [comment]
mmmh, the gray bars also happen when using `fitBounds()` probably because it does not round the calculated zoom

**Comment by benoitskipr** [comment]
@johnpryan this ticket should be reopened, it happens all the time with fitbounds

**Comment by pakutoma** [comment]
I have the same issue in Android, and I solved by:
src/layer/tile_layer.dart, Line 194
```
var tileZoom = _clampZoom(zoom.round().toDouble());
```
to
```
var tileZoom = _clampZoom(zoom.floorToDouble());
```

I want to send PR, but I can't know that this solution works perfectly or not.

Thanks.
