### ISSUE TITLE
Zoom speed (double tap or pinch)

### ISSUE THREAD

**Issue by shinayser** [johnpryan/flutter_map#133]
We should be able to customize the zoom amount (for double tap) and sensitivity (for pinch). The default implementation is actually **very fast**.
There is any way of doing this on this moment or am I missing something?

**Comment by johnpryan** [comment]
There's not currently a way to do this - In general the pinching to zooming needs to be improved a little. I just created an issue to track the more general zoom issue issue: https://github.com/apptreesoftware/flutter_map/issues/171 which could include a "zoomScalar" or some other property to increase the "power" of the zoom gesture.
