### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by neiljaywarner** [johnpryan/flutter_map#167]
dartpub has a link for video
https://pub.dartlang.org/packages/flutter_map
It referenceas a private file.
I requested access but it was not granted.
I imagine it should be removed or made public

thanks for a cool library!

**Comment by neiljaywarner** [comment]
link is https://drive.google.com/file/d/14srd4ERdgRr68TtLmG6Aho9L1pGOyFF7/view?usp=sharing
(it says "Video" right above the picture

**Comment by johnpryan** [comment]
The video is marked as "anyone with the link can view" but it's an old video and should be removed or replaced with a new one. Thanks for bringing this up

**Comment by johnpryan** [comment]
merging into #63
