### ISSUE TITLE
add projection support

### ISSUE THREAD

**Issue by WoodenPC** [johnpryan/flutter_map#169]
more info https://leafletjs.com/reference-1.3.4.html#projection

**Comment by johnpryan** [comment]
This is already supported. Are you looking to have this exposed as a public API?

**Comment by WoodenPC** [comment]
@johnpryan Yes I am. Pls make that feature public :)

**Comment by WoodenPC** [comment]
i guess i found how to use that. I need to create instance of MapOptions and use crs property propably)

**Comment by johnpryan** [comment]
MapController is the interface for controlling the map, which could expose the `project` method from MapState here: https://github.com/apptreesoftware/flutter_map/blob/8d2c3b6738500ecad69d2d47fccb202dc2d0596a/lib/src/map/map.dart#L12

**Comment by WoodenPC** [comment]
I have map bounds {"x1":52065.489907638,"y1":-90977.3001140543,"x2":117151.184832625,"y2":-29618.6763295051,"width":65085.6949249871,"height":61358.6237845492} and i need to draw markers on map. Marker has coords "x":"6979","y":"15297". For correct coords transformation i have to set map bounds i guess. But i cannot find function to set mapbounds. There is Bounds<T> class but i dont see setter.

**Comment by johnpryan** [comment]
There is still work to do to support this. We'll need to add this to the MapController interface.

**Comment by WoodenPC** [comment]
Hi are there any updates?

**Comment by ibrierley** [comment]
Not sure if I'm misunderstanding this one, but as an example in the meantime, couldn't you do...

```
import 'package:flutter_map/src/geo/crs/crs.dart';

var point = Epsg3857().latLngToPoint(new LatLng(50.8833814, -0.2228946), 12.0);
var project = SphericalMercator().project( new LatLng(50.8833814, -0.2228946) );
var unproject = SphericalMercator().unproject ( project );

print( "Point:$point" );
print( "Project: $project" );
print( "Unproject: $unproject");

```

**Comment by johnpryan** [comment]
@WoodenPC What do you mean "set my custom bounds"?

**Comment by WoodenPC** [comment]
sry i probably answered wrong, i mean i need something like leaflet`s fitBounds and fitWorld functions

**Comment by johnpryan** [comment]
Is there a reason you can't use MapController.fitBounds? You can also use the LatLngBounds class to extend the bounds before you call fitBounds.

**Comment by WoodenPC** [comment]
found solution, ty all for help
