### ISSUE TITLE
Avoid exceptions when no tiles are available for a zoom level

### ISSUE THREAD

**Issue by WoodenPC** [johnpryan/flutter_map#173]
Getting an exception when loading tile from url/{z = 2}/{x = 0}/{y = 3}.png, although max y is 2, Is that a bug or i am doing something wrong? Can i set tile dimesions or something like that {"level":0,"x":1,"y":1},{"level":1,"x":2,"y":2} ... ?

**Comment by WoodenPC** [comment]
maybe i forget to add some options in MapOptions?
`return Column(`
`        children: <Widget>[`
`                Flexible(`
`                  child: FlutterMap(`
`                    mapController: _mapController,`
`                    options: MapOptions(`
`                      center: LatLng(51.9, -0.09),`
`                      minZoom: map.zoom.minZoom.toDouble(),`
`                      maxZoom: map.zoom.maxZoom.toDouble(),`
`                      zoom: 1.0,`
`                    ),`
`                    layers: [`
`                      TileLayerOptions(`
`                        tileSize: map.tileSize.toDouble(),`
`                        backgroundColor: Colors.white,`
`                        maxZoom: map.zoom.maxZoom.toDouble(),`
`                        urlTemplate: '${widget.url}/{z}/{x}/{y}.png'`
`                      ),`
`                    ]`
`                  ),`
`                )`
 `              ],`
`            );`

**Comment by johnpryan** [comment]
Can you double check that the urlTemplate has `widget.url` when the options are first defined? If the tile layer doesn't receive the correct `urlTemplate` the first time it probably won't work

**Comment by WoodenPC** [comment]
It is correct, widget.url initialize in contructor. The exception reproduces after some time, like I said earlier z was 2, I already zoomed 2 times

**Comment by WoodenPC** [comment]
I think, that exception was thrown when I was moving near the borders of the map

**Comment by johnpryan** [comment]
I see. It sounds like the tile service you are using doesn't have tiles available for that zoom level. As a workaround you could set a minimum zoom level, but you're right we should avoid the exception being thrown. Thanks for filing an issue

**Comment by WoodenPC** [comment]
its not only about {z} its about not available {x} and {y}, for my example i had max zoom = 7 min zoom = 0, exception was on {z = 2}/{x = 0}/{y = 3}.png but i dont have tile with y = 3 on z = 2 and x = 0

**Comment by johnpryan** [comment]
got it, thanks

**Comment by ganisback** [comment]
Hope this can be fixed, I always meet this issue

**Comment by ganisback** [comment]
flutter map should avoid zoom in again if there is no available tiles

**Comment by johnpryan** [comment]
I don't see a clear way to implement this. It's up to the user to know what zoom levels work, and update the min and max zoom levels accordingly.
