### ISSUE TITLE
official document

### ISSUE THREAD

**Issue by DanialV** [johnpryan/flutter_map#183]
Please provide a document to understand available features and upcoming one and how to use them.

**Comment by vinicentus** [comment]
+1

**Comment by Naranmandakh** [comment]
+1

**Comment by sky93** [comment]
+1

**Comment by Yodart** [comment]
+1

**Comment by aitorres** [comment]
+1
I can try to write a small, basic usage guide with current features.

**Comment by johnpryan** [comment]
There's no official roadmap, the issue tracker is the best source for the most requested features. This is something we can improve in the documentation, so I'm merging this into #63
