### ISSUE TITLE
More Caching

### ISSUE THREAD

**Issue by haydenflinner** [johnpryan/flutter_map#19]
Is there any way I can convince my mapview to cache the images it downloads indefinitely? I'd like to be able to look at an area once and then have the tiles downloaded always available, at least until someone clear's the app's cache.

I'd also be happy with a way to supply my own custom tiles that doesn't involve hosting a webserver. Saw a technique for a React map library that involved giving a local filename to the device's filesystem instead of a URL. I doubt something like that would work as easily here, but how hard would it be for me to add?

**Comment by haydenflinner** [comment]
Just started with Flutter about 4 days ago, no experience with dart. How would I go about experimenting with a custom NetworkImage widget? If I succeed with that, I might end up trying to add PolyLine support as well.

Mental health rant incoming:

Started with Flutter and my project Monday, without a firm grasp of what I wanted my project to look like. By the time I posted this issue, it was basically done, minus some forms that would have been trivial in Flutter and it would have been limited in future growth because can't draw polylines on your map.

So I switched to React Native. Biggest development mistake I've ever made, by far. Every single step along the way is a headache. Map doesn't work unless you set up the component tree in a very finicky way. Can't show modals or anything of that nature over the map without them screwing up. Can't use a custom view that pops up when you tap a marker without doing all sorts of finicky witchcraft (gave up on this after an hour and launched a full-screen window when someone tapped my marker). It developed a strange bug where it zoomed in and out constantly, on its own. Sometimes it just doesn't render my markers. Not to mention all the undefineds and silent failures I've been chasing because of JS.

I've wasted approx. 12 hours of effort over the last few days trying to get React Native to give me anywhere close to the smooth, good-looking, and pain-free experience Flutter + your library gave me, and I'm wishing I had just extended your library for the stuff I needed instead. Depending on how easy you think adding the things I need will be, I'd love to switch back.

**Comment by johnpryan** [comment]
Ouch! Actually, @vahid-sohrabloo [just added polyline support](https://github.com/apptreesoftware/flutter_map/pull/9) so please file issues if you need anything else or find any bugs.

 I haven't played around with maps + React Native maps, it's good to hear this solution works better.

> use the dart HttpServer class as the provider for tiles to the map, forwarding requests to the real provider and saving the results as they come back

you might be interested in the discussion happing here: https://github.com/apptreesoftware/flutter_map/issues/3 

> markers randomly stopped working and sending UDP packets also continued to fail

Good to know! This is a known issue and a another way to debug might be to use [flutter_stetho](https://github.com/brianegan/flutter_stetho)

**Comment by haydenflinner** [comment]
Nono, markers not showing and UDP packets not working was in React! My Flutter experience had continued to be nothing but perfect!

**Comment by haydenflinner** [comment]
Looking forward to messing with this polyline support! Very glad to see new stuff being added and to be back to having fun developing this project. Thanks for the link to #3! I'm going to stick with my HTTP server idea though I think, that way I can share tiles easily across the WLAN when the WLAN isn't connected to Internet!

**Comment by savy-91** [comment]
@haydenflinner if you need polyline support, I started working on a fork (I'm going to make a PR eventually) to add encoded polyline support: https://github.com/savy-91/flutter_google_map_view

It currently works already with Google Maps Directions API.

**Comment by johnpryan** [comment]
@savy-91 what other features does that have compared to https://github.com/apptreesoftware/flutter_map/pull/9?

**Comment by GeoTob** [comment]
Commenting on the original issue, we've been using `https://pub.dartlang.org/packages/cached_network_image` for caching images in the past and it works like a charm as a drop-in replacement for `NetworkImage`. I'd presume with some tweaking of the default settings it shouldn't be too hard to have a simple caching implementation working?

**Comment by johnpryan** [comment]
`https://pub.dartlang.org/packages/cached_network_image` looks nice, in addition, it would help for us to override the CachedNetworkImageProvider class in that package to provide some custom caching rules based on the user's location. For instance, we want to limit the number of cached images and probably remove cached images over a certain distance away from the viewport.

**Comment by natezhengbne** [comment]
@johnpryan Could I ask has support cache?

**Comment by johnpryan** [comment]
@natezhengbne this package is currently using the flutter_image package here: https://github.com/apptreesoftware/flutter_map/blob/eaee6b926ba2332fe0c4d805f7ead83475112412/lib/src/layer/tile_layer.dart#L452

**Comment by johnpryan** [comment]
There's been some changes with how images are displayed, and there are multiple TileProviders to choose from, so I'm marking this as stale
