### ISSUE TITLE
how to invoke GaoDe map

### ISSUE THREAD

**Issue by zoujinbin** [johnpryan/flutter_map#192]
Hi~I want to invode GaoDe to show map, and I use "http://webrd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}" instead of "https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}" in urlTemplate, but I can't view the map in the mobile phone.

![map](https://user-images.githubusercontent.com/39855077/50547506-8561d900-0c75-11e9-8240-7d4510a51f1a.jpg)

**Comment by ibrierley** [comment]
I think you may be missing the subdomain {s} part in the additional options (you can hardcode the subdomain to test)?

Have you tested the URL with an example x,y,z,s ?

**Comment by zoujinbin** [comment]
yeah, I add the sudomains and it works. Does the project have  locate function?

**Comment by ibrierley** [comment]
If you mean a geo-locate type function, no. I can recommend geolocator plugin though.

**Comment by zoujinbin** [comment]
Thanks

**Comment by Huai-Dc** [comment]
请问一下 你高德的瓦片图 可以加载了吗
