### ISSUE TITLE
move to the center point

### ISSUE THREAD

**Issue by zoujinbin** [johnpryan/flutter_map#194]
In the flutter_map, I move  to the other point or zoom the map with gesture, so I often can't find the initial center point. how can I add a icon that when I click the icon, I can jump to the center point. Just like a geolocate function, It can help you find your current location. 
![amap](https://user-images.githubusercontent.com/39855077/50571711-3ee2ba80-0dec-11e9-8cd8-03b77858649d.jpg)

**Comment by ganisback** [comment]
You can use mapController to move to the center point. For the button, flutter has floating action button. pls close this issue, it not related flutter map

**Comment by zoujinbin** [comment]
Okay! Thanks a lot.

**Comment by yanqiqi1996** [comment]
> Okay! Thanks a lot.

Can you tell me how to  use amp?
