### ISSUE TITLE
How can I get specified locations from center latlng?

### ISSUE THREAD

**Issue by zoujinbin** [johnpryan/flutter_map#195]
In the flutter map, I have a center latlng. Now I want to obtain some locations which near the center latlng, and mark them with marker. For example, how can I get these locations that 500 meters from the center latlng?

**Comment by ibrierley** [comment]
Not sure I quite follow. What locations, where are they from ? It feels like that would be part of a different solution, but maybe if you explain a bit differently, it may be a bit more obvious what type of solution is needed.

**Comment by MVTalent** [comment]
Maybe this will suit [Overpass_API](https://wiki.openstreetmap.org/wiki/Overpass_API#Around) or [nominatim-radius-search](https://help.openstreetmap.org/questions/14407/nominatim-radius-search) with [nominatim](https://pub.dartlang.org/packages/nominatim) is it with a few changes

**Comment by johnpryan** [comment]
This isn't related to flutter_map. See the latlong package for ideas on how to calculate distance. There's different approaches.
