### ISSUE TITLE
A package may not list itself as a dependency

### ISSUE THREAD

**Issue by AliRezaBeitari** [johnpryan/flutter_map#196]
When I run `flutter packages get` it gives my this error:
```
Error on line 18, column 3 of pubspec.yaml: A package may not list itself as a dependency.
  flutter_map:
  ^^^^^^^^^^^


pub get failed (65)
```
How can I fix it?!

**Comment by SamuelRioTz** [comment]
i guess is missing the version, try this one "flutter_map: ^0.4.0"

**Comment by AliRezaBeitari** [comment]
I tried it, but still same error!

**Comment by johnpryan** [comment]
I suspect your package name is flutter_map. Try changing the name of your package to something else.

**Comment by AliRezaBeitari** [comment]
@johnpryan Yes, you were right 😅 Thanks for your help.
