### ISSUE TITLE
Auto zoom

### ISSUE THREAD

**Issue by agnoam** [johnpryan/flutter_map#197]
Is there way to set auto zoom at any time and see all my markers in the screen without change the zoom manually ?

**Comment by RaimundWege** [comment]
@agnoam you could create a LatLngBounds for your markers and use fitBounds to show all your markers at once.

**Comment by agnoam** [comment]
Could you show me an example please ?

**Comment by aytunch** [comment]
This would make all the markers stay in screen, yes, but it does not zoom enough to fit the markers perfectly. Is there a way to zoom(move) with animation?

**Comment by johnpryan** [comment]
#236 is closed. I think this can be closed too.
