### ISSUE TITLE
too many directory crashes Flutter

### ISSUE THREAD

**Issue by TechieOldFox** [johnpryan/flutter_map#199]
Tried a map with level 16 zoom. Created assets with all the PNG files necessary. Run Flutter and it crashed. Confirm with Flutter team that it is due to too many assets defined. Had to choose a smaller map area and zoom level combination or wait until Flutter team solve the issue. 

Able to use mbtiles instead? Its just one SQLite file instead of tens of thousands of PNG.

**Comment by johnpryan** [comment]
MBTiles support has now been added to master
