### ISSUE TITLE
Marker cluster

### ISSUE THREAD

**Issue by agnoam** [johnpryan/flutter_map#201]
Hey I need MarkerCluster, is there a way to use it here ?

**Comment by johnpryan** [comment]
You will have to cluster the pins yourself. You can do this by rounding the latitude and longitude of the locations to 6 digits or so.

**Comment by fvisticot** [comment]
Is there any sample code or library available ? I think that many people need this feature

**Comment by RaimundWege** [comment]
I haven't tried it yet but I will see in the near future if I can use [k_means_cluster](https://pub.dartlang.org/packages/k_means_cluster) for clustering marker.

**Comment by johnpryan** [comment]
cool, let us know how it goes!

**Comment by RaimundWege** [comment]
The package I've mentioned can be used for Marker clustering. I'm not finished yet but I can't see no big issues for my further work. So here are the steps you have to do (this is only one way to solve the issue and there are still space for optimizations):

1. Add  `k_means_cluster: ^0.2.1` to your dependencies
2. Handle each position change of your map:
```
  MapPosition _mapPosition;
  void _handleOnPositionChanged(MapPosition position, bool hasGesture) {
    setState(() {
      _mapPosition = position;
    });
  }
```
3. Write a function to create a list of markers for a specific region:
```
  List<Marker> _buildEventMarkers(List<Event> eventList, MapPosition position) {
    if (position == null || !position.bounds.isValid) {
      return [];
    }

    // Lookup table for all visible marker (for the library we need an id for each marker)
    final eventMap = eventList.fold<Map<String, Event>>(Map(), (events, event) {
      if (position.bounds.contains(event.location)) {
        events[event.id] = event;
      }
      return events;
    });
    if (eventMap.isEmpty) return [];

    // Build instances for k-mean
    List<Instance> instances = eventMap.values.map((event) {
      return Instance(
        [event.location.latitude, event.location.longitude],
        id: event.id,
      );
    }).toList();

    // Initialize clusters (maximum of 9 marker will be shown)
    List<Cluster> clusters = initialClusters(9, instances, seed: 0);
    kmeans(clusters: clusters, instances: instances);
    return clusters.map<Marker>((cluster) {
      if (cluster.instances.length == 1) {
        Event event = eventMap[cluster.instances[0].id];
        return buildEventMarker(
          event: event,
          onTap: () {
            setState(() {
              _selectedEvent = event;
            });
          },
        );
      } else {
        return buildClusterMarker(
          cluster: cluster,
          onTap: () {},
        );
      }
    }).toList()
      ..sort(
        (m1, m2) => -1 * m1.point.latitude.compareTo(m2.point.latitude),
      );
  }
```
4. Use the function above to create a marker layer for your map:
```
    FlutterMap(
      // ...
      options: MapOptions(
        // ...
        onPositionChanged: _handleOnPositionChanged,
      ),
      layers: <LayerOptions>[
        // ...
        MarkerLayerOptions(markers: _buildEventMarkers(events, _mapPosition))
      ],
    );
```

The downside of the clustering per 'onMapPositionChanged' is a flickering of markers and in the next step I will calculate the clusters only once for each zoom level.

**Comment by RaimundWege** [comment]
This is how it looks right now:
![clusters](https://user-images.githubusercontent.com/1120142/52708964-c561ee80-2f8b-11e9-9f46-c8113b08b1a9.gif)

**Comment by johnpryan** [comment]
that's looking pretty good - thanks for the update!

**Comment by 926** [comment]
Super cool ! Thank you @johnpryan  for pointing this out. 
@RaimundWege have you already published a repo using this functionality ?

**Comment by letsar** [comment]
@RaimundWege this is great, by the way how did you put custom text into the markers?

**Comment by pinxox** [comment]
Hi @RaimundWege , 
do you have this functionality fully implemented in some example? It would be a great help to me, since I'm not going to make this code work.
Thanks¡¡

**Comment by lpongetti** [comment]
https://github.com/lpongetti/flutter_map_marker_cluster
