### ISSUE TITLE
BOTTOM OVERLFLOWED BY 114 PIXELS

### ISSUE THREAD

**Issue by agnoam** [johnpryan/flutter_map#202]
Hey this error 

> BOTTOM OVERFLOWED BY 114 PIXELS

showed instead of Marker, I want to create Marker looks like this
![marker](https://user-images.githubusercontent.com/6377503/50776169-f79f7280-12a0-11e9-974f-29355d60b26e.PNG)

so I created this class:
```
import 'package:flutter/material.dart';

class MarkerIcon extends StatelessWidget {
  
  final Image _profileImage;
  final Color groupColor;

  MarkerIcon(this._profileImage, { this.groupColor });

  @override
  Widget build(BuildContext context) {
    return Container(
      child: SafeArea(
        child: Column(
          children: <Widget>[
            CircleAvatar(
              radius: 50.0,
              backgroundColor: Colors.white,
              child: this._profileImage,
            ),
            CircleAvatar(
              radius: 10.0,
              backgroundColor: this.groupColor != null ? this.groupColor : Colors.black,
              child: null
            )
          ]
        )
      )
    );
  }
}
```
And put it into your Marker class like this:
```
Marker a = new Marker(
  point: LatLng(25.243532, 53.21548),
  builder: (BuildContext context) {
    MarkerIcon(new Image.assets('/pinguin.jpg'), groupColor: Colors.lightGreen);
  }
);
```

Why is it happens ?

**Comment by johnpryan** [comment]
Does this error throw with other marker types or just this one?

**Comment by johnpryan** [comment]
I suspect this issue is coming from your widget, not the map widget.

**Comment by agnoam** [comment]
It comes from your map because, when I use it in Scaffold everything works. You can try...

**Comment by stafyniaksacha** [comment]
I suspect `SafeArea` to be the cause. Have you tried without (just to be sure that this cause the issue)
