### ISSUE TITLE
Use image cache for tiles images

### ISSUE THREAD

**Issue by SamuelRioTz** [johnpryan/flutter_map#203]
Every tiles are downloaded again after every restart the app, it will be good if we use CachedNetworkImageProvider instead NetworkImageWithRetry.

CachedNetworkImageProvider is part of:
[https://pub.dartlang.org/packages/cached_network_image](url)

I already have an example working with both options:

> if(options.cachedTiles){
        return new CachedNetworkImageProvider(url);
      }else{        
        return new NetworkImageWithRetry(url);
      }

**Comment by lnalex** [comment]
Feature released in 0.5.0 : https://github.com/johnpryan/flutter_map/pull/204

This issue can be closed.
