### ISSUE TITLE
Is it possible to draw a polyline dynamically? Or move marker positions without reloading the map?

### ISSUE THREAD

**Issue by rubberbird** [johnpryan/flutter_map#209]
I would like to be able to use a streambuilder or state to dynamically move a marker or draw/extent a polyline re-actively. I tried a few options but all reloaded the map itself. Any suggestions?

Related Link in Stackoverflow - https://stackoverflow.com/questions/54226997/reactive-dynamic-markers-using-flutter

**Comment by karan20000000000** [comment]
Not sure how're you trying to achieve this but when I tried something like following, it seems to work good without reloading the map.

Somewhere in class you can have a list of LatLng objects for polyline
`List<LatLng> routePath;`

Something similar for markers, but you can have a list of objects that have a latlng property
```dart
List<BusStop> busStops;
List<Bus> buses;
```

Then in your flutter_map widget:
```dart
layers: [
        new TileLayerOptions(
          urlTemplate:
              "...",
          additionalOptions: {
            'accessToken':
                '...',
            'id': 'mapbox.mapbox-streets-v8',
          },
          keepBuffer: 3,
        ),

        //Route
        new PolylineLayerOptions(polylines: [
          new Polyline(
            points: routePath ?? [],
            color: Colors.white,
          )
        ]),

        new MarkerLayerOptions(
          markers: busStops?.map<Marker>((bs) {
                return new Marker(
                    point: bs.position, //.position is the latlng property of BusStop object
                    builder: (context) {
                      return new GestureDetector(
                        onTap: () {
                          Scaffold.of(context).showSnackBar(new SnackBar(
                            content: Text(bs.toString()),
                            duration: Duration(seconds: 1),
                          ));
                        },
                        child: Icon(
                          Icons.casino,
                          color: Colors.white,
                          size: 17.0,
                        ),
                      );
                    });
              })?.toList() ??
              [],
        ),

        new MarkerLayerOptions(
          markers: buses?.map<Marker>((bs) {
                return new Marker(
                    point: bs.position, //.position is the latlng property of Bus object
                    builder: (context) {
                      return new GestureDetector(
                        onTap: () {
                          Scaffold.of(context).showSnackBar(new SnackBar(
                            content: Text(bs.toString()),
                            duration: Duration(seconds: 1),
                          ));
                        },
                        child: new Icon(
                          Icons.train,
                          color: Colors.blueAccent,
                        ),
                      );
                    });
              })?.toList() ??
              [],
        ),
      ],

```

Now whenever you want to update your markers, make changes to the lists within the setState method:

```dart
void updateBusPositions() {
    
    //Not the exact method i wrote but something similar to this
    UpdatePositionsMethod().then((newlist) {
        setState(() {
          //update buses list here
          for(Bus bus in buses) {
              //update bus' position
          }
      });
    });
      

  }
```

You could now call this above update method with some timer or based on some other callback.

Also, there is a possibility I may not have completely understood your question. So, let me know if I'm right or wrong. :]

**Comment by ibrierley** [comment]
Is your setState being called on your map widget state though ? If so, that will rebuild the whole map (assuming we are talking about rebuilds when we mention reloads ?)

**Comment by rubberbird** [comment]
@karan20000000000  Thanks for the example, It is similar to what I have tried already which rebuild the entire Map, but I will give your code a shot and see what happens.

**Comment by johnpryan** [comment]
Markers are similar to other widgets. They can be moved by calling "setState" with the new markers. please see `moving_markers.dart` example in the example project for ideas. There isn't an example for polylines yet but it should be a similar pattern.
