### ISSUE TITLE
add support for detectRetina display

### ISSUE THREAD

**Issue by DanialV** [johnpryan/flutter_map#212]
there is an option in original leaflet js library which is used for retina display(high pixel density) however I couldn't find such feature in FlutterMap widget. this feature will prevent map images render blurry in devices with high pixel density 
here is the github issue about this problem [Blurry Maps](https://github.com/Leaflet/Leaflet/issues/6068#issuecomment-368256572)
here is leaflet document description about this option

> If true and user is on a retina display, it will request four tiles of half the specified size and a bigger zoom level in place of one to utilize the high resolution.

**Comment by sky93** [comment]
I really need this feature too.

**Comment by sky93** [comment]
I think we should change tileSize from 256.0 to 128.0 and then somehow resize the image when showing in tiles. And add the whole thing as an option called Retina Display.

**Comment by songfei** [comment]
use  512x512 png tile  or 768x768 png tile  and set tileSize to  256

**Comment by sky93** [comment]
> tile

Unfortunately our tile server only supports 256px.

**Comment by HugoHeneault** [comment]
Hey there! Thanks for this awesome flutter map plugin 🍻 

Is it in your schedule to support retina? It is blurring my maps on almost every design for providers without `@2x` support... 

Thanks a lot!

**Comment by maRci002** [comment]
Hello, checkout PR #585 it adds support for retina mode.
