### ISSUE TITLE
Polylines not being displayed

### ISSUE THREAD

**Issue by MatanLjubas** [johnpryan/flutter_map#215]
I'm trying to create a simple routing system through the use of this plugin. I'm using mapbox map, and I'm getting the coordinates of route through the use of the Graphhopper API. 

Unfortunately, polylines are not displayed after the map is loaded, whether I enter them manually, or using the code below.

My code is as follows:

`import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:latlong/latlong.dart';
import 'OSMap.dart';`

Future<Points> _fetchCoordinates(startLat, startLng, endLat, endLng) async {
  final response = await http.get(
    'https://graphhopper.com/api/1/route?point=${startLat.toString()},${startLng.toString()}&point=${endLat.toString()},${endLng.toString()}&vehicle=foot&locale=hr&key=<API_KEY>&points_encoded=false&instructions=false',
  );

  if (response.statusCode == 200) {
    return Points.fromJson(json.decode(response.body));
  } else {
    throw Exception('Error');
  }
}

class Points {
  List<List<double>> coordinates;

  Points({this.coordinates});

  factory Points.fromJson(Map<String, dynamic> json) => Points(
      coordinates: List<List<double>>.from(json["paths"][0]["points"]
              ["coordinates"]
          .map((x) => List<double>.from(x.map((x) => x.toDouble())))));

  Map<String, dynamic> toJson() => {
        "coordinates": List<dynamic>.from(
            coordinates.map((x) => List<dynamic>.from(x.map((x) => x))))
      };
}

class Routing extends StatelessWidget {
  Routing({
    @required this.startLat,
    @required this.startLng,
    @required this.endLat,
    @required this.endLng,
  });

  final double startLat;
  final double startLng;
  final double endLat;
  final double endLng;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<Points>(
      future: _fetchCoordinates(startLat, startLng, endLat, endLng),
      builder: (context, snapshot) {
        final List coordinates =
            snapshot.hasData ? snapshot.data.coordinates : <LatLng>[];
        if (snapshot.hasData) {
          print(coordinates.map((pair) => LatLng(pair[0], pair[1])).toList());
          return MyCustomMap(
              mapType: 'mapbox.outdoors',
              lat: startLat,
              lng: startLng,
              points:
                  coordinates.map((pair) => LatLng(pair[0], pair[1])).toList());
        } else if (snapshot.hasError) {
          [...]
        } else
          [...]
      },
    );
  }
}`

And the map itself: 

`import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';

class MyCustomMap extends StatefulWidget {
  MyCustomMap({
    @required this.lat,
    @required this.lng,
    this.markers: const <Marker>[],
    this.mapType: 'mapbox.light',
    this.points: const <LatLng>[],
  });

  final double lat;
  final double lng;
  final List<Marker> markers;
  final String mapType;
  final List<LatLng> points;

  @override
  State<StatefulWidget> createState() {
    return _MyCustomMapState();
  }
}

class _MyCustomMapState extends State<MyCustomMap> {
  @override
  Widget build(BuildContext context) {
    return FlutterMap(
      options: MapOptions(
        interactive: true,
        zoom: 16.0,
        center: LatLng(widget.lat, widget.lng),
      ),
      layers: [
        TileLayerOptions(
          urlTemplate: "https://api.tiles.mapbox.com/v4/"
              "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
          additionalOptions: {
            'accessToken':
                <ACCESS_TOKEN>,
            'id': widget.mapType,
          },
        ),
        PolylineLayerOptions(
          polylines: [
            Polyline(
              points: widget.points,
              strokeWidth: 4,
              color: Colors.purple,
            ),
          ],
        ),
        MarkerLayerOptions(markers: widget.markers),
      ],
    );
  }
}`

When printing the code inserted into the list of points connecting the polyline ( `
          print(coordinates.map((pair) => LatLng(pair[0], pair[1])).toList());` ), everything seems to be set up properly. The result is the following:

`I/flutter ( 9311): [LatLng(latitude:15.240278, longitude:44.103121), LatLng(latitude:15.240624, longitude:44.102999), LatLng(latitude:15.241097, longitude:44.102731), LatLng(latitude:15.241316, longitude:44.102563), LatLng(latitude:15.241827, longitude:44.10227), LatLng(latitude:15.242245, longitude:44.10195), LatLng(latitude:15.243088, longitude:44.101372), LatLng(latitude:15.244048, longitude:44.100957), LatLng(latitude:15.244533, longitude:44.10071), LatLng(latitude:15.245143, longitude:44.100235), LatLng(latitude:15.246142, longitude:44.099028), LatLng(latitude:15.245459, longitude:44.098711)]`

Any help with this would be highly appreciated.

**Comment by ibrierley** [comment]
If you print out the points in the MyCustonMapState...does it show them ? And is it displaying after your earlier print from your futurebuilder ? Just checking if the build method is getting called as you think, and if points is populated.

**Comment by MatanLjubas** [comment]
@ibrierley I've just added the `print(widget.points);` function into the initState function in the MyCustomMapState class, and the result is `I/flutter (10803): [LatLng(latitude:15.240278, longitude:44.103121), LatLng(latitude:15.240624, longitude:44.102999), LatLng(latitude:15.241097, longitude:44.102731), LatLng(latitude:15.241316, longitude:44.102563), LatLng(latitude:15.241827, longitude:44.10227), LatLng(latitude:15.242245, longitude:44.10195), LatLng(latitude:15.243088, longitude:44.101372), LatLng(latitude:15.244048, longitude:44.100957), LatLng(latitude:15.244533, longitude:44.10071), LatLng(latitude:15.245143, longitude:44.100235), LatLng(latitude:15.246142, longitude:44.099028), LatLng(latitude:15.245459, longitude:44.098711)]`

**Comment by MatanLjubas** [comment]
Definitely! :) 
My startLat and startLng parameters (lat and long points where the route is starting) is also the center of my map.

**Comment by MatanLjubas** [comment]
Okay, I just realise I've messed up my lat and long :) 
I'm sorry! Also, I would like to thank you very much for your time.
