### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by tegarkurniawan** [johnpryan/flutter_map#217]
I tried the polyline example and when it was run white screen
E/flutter (21942): [ERROR:flutter/shell/common/engine.cc(172)] Could not prepare to run the isolate.
E/flutter (21942): [ERROR:flutter/shell/common/engine.cc(119)] Engine not prepare and launch isolate.
E/flutter (21942): [ERROR:flutter/shell/platform/android/android_shell_holder.cc(167)] Could not launch engine in configuration.
I/zygote64(21942): Do partial code cache collection, code=30KB, data=23KB
I/zygote64(21942): After code cache collection, code=30KB, data=23KB
I/zygote64(21942): Increasing code cache capacity to 128KB

**Comment by johnpryan** [comment]
It's hard to say what's causing this. Perhaps the polyline layer is using a lot of memory.

**Comment by johnpryan** [comment]
Can you add a small example that reproduces the issue?

**Comment by johnpryan** [comment]
marking as stale
