### ISSUE TITLE
Does this plugin have navigation function？

### ISSUE THREAD

**Issue by QixinLi** [johnpryan/flutter_map#219]
Or how can I use navigation function with the native GaoDe api?

**Comment by haroonkhan9426** [comment]
Following the same. @QixinLi  if you have found any solution for navigation, please also let me know.

**Comment by ibrierley** [comment]
You can use an API like Mapbox or google for navigation.

**Comment by QixinLi** [comment]
> Following the same. @QixinLi if you have found any solution for navigation, please also let me know.

I don't think this plugin can navigate, but I solve this question by using GaoDe API in Android native. 
Probably, you can write a custom flutter plugin, so that you can jump to an Android native page from flutter app.

**Comment by johnpryan** [comment]
This is not a planned feature, sorry

**Comment by bettdalpha** [comment]
If the API you use returns a geojson, you can parse the geojson and create a polyline feature, then add markers and the source and destination
