### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by dyardyGIT** [johnpryan/flutter_map#222]
Is it possible to have multiple layers with an opacity on one and not the other?

i.e. bring in a street map with 100% opacity then bring in another layer at 50%

**Comment by ibrierley** [comment]
I think it depends, do you mean 2 separate complete maps over each other, or different layers within the same map ?

**Comment by dyardyGIT** [comment]
I was wanting to add 2 layers and have one of them 50% transparent.  This was my primary goal.

i.e.
layers:[
 new TileLayerOptions(#1),
 new TileLayerOptions(#2)
]

where layer #1 is 50% transparent.

thank you!

**Comment by johnpryan** [comment]
This isn't currently possible, sorry

**Comment by dyardyGIT** [comment]
Is there any approach that would allow me to layer more than 1 layer? (do you see this as a feature you will be adding)?  
We would like to have 1 layer for construction effort and another for street or satellite map.  Embedding both in the offline tiles (pngs) is challenging for us.

Thanks again - Dave

**Comment by ibrierley** [comment]
Why not run 2 overlapping full maps (rather than layers)?

**Comment by johnpryan** [comment]
@dyardyGIT If you have the bandwidth, you could take a look at modifying this project to support that. I'm not totally opposed to adding an `opacity` option to the API, but there may be a way to support allowing arbitrary customizations to the tile layers, not just opacity

@ibrierley this could work, but would involve coordinating the two map positions, and could potentially lead to situations where they get out of sync

**Comment by jazzytomato** [comment]
There is a default `backgroundColor` set to grey with no transparency https://github.com/johnpryan/flutter_map/blob/3f54a36c87420efed16db0e475bac0849170bfae/lib/src/layer/tile_layer.dart#L109

Which is ok as default value for the first layer, but I wonder if it shouldn't just be completely transparent.

If the tile images of the second layer already have transparency, then setting the `backgroundColor` option explicitly should work.
```dart
new TileLayerOptions(backgroundColor: new Color.fromRGBO(0, 0, 0, 0)) // last parameter is alpha channel
```

**Comment by lordzyx** [comment]
> There is a default `backgroundColor` set to grey with no transparency
> 
> https://github.com/johnpryan/flutter_map/blob/3f54a36c87420efed16db0e475bac0849170bfae/lib/src/layer/tile_layer.dart#L109
> 
> Which is ok as default value for the first layer, but I wonder if it shouldn't just be completely transparent.
> 
> If the tile images of the second layer already have transparency, then setting the `backgroundColor` option explicitly should work.
> 
> ```dart
> new TileLayerOptions(backgroundColor: new Color.fromRGBO(0, 0, 0, 0)) // last parameter is alpha channel
> ```

yeah! working perfect with openstreetmap + openrailwaymap ! thank you!
