### ISSUE TITLE
Add bbox to templateUrl (WMS tile)

### ISSUE THREAD

**Issue by noneex** [johnpryan/flutter_map#225]
Hello, I want to add bbox to templateUrl, but can't access mapController, it's always null. 
How to do it properly?

**Comment by noneex** [comment]
![image](https://user-images.githubusercontent.com/38165959/52558262-0b984000-2e1c-11e9-8d7b-7d96af34f69c.png)
my bad try

**Comment by johnpryan** [comment]
Sorry, I don't understand the question

**Comment by maituongan11zz** [comment]
I think this plugin do not support WMS and WFS yet, it only support for wmts.

**Comment by devmgs** [comment]
There is a request for WMS at https://github.com/johnpryan/flutter_map/issues/412
