### ISSUE TITLE
fitToBounds doesn't change zoom level

### ISSUE THREAD

**Issue by rafalur** [johnpryan/flutter_map#233]
Basing on example I tested how fitToBounds works. The "Map Controller" example provides map with 3 markers and button that fires call to fitToBounds to show all markers. 

```
new MaterialButton(
  child: new Text("Fit Bounds"),
  onPressed: () {
    var bounds = new LatLngBounds();
    bounds.extend(dublin);
    bounds.extend(paris);
    bounds.extend(london);
    mapController.fitBounds(
      bounds,
      options: new FitBoundsOptions(
        padding: new EdgeInsets.only(left: 15.0, right: 15.0),
      ),
    );
  },
),
```

when I comment out Dublin from bounds and tap "Fit bounds" button the map is only centered on both Paris and London markers but not zoom in to fit these two markers:
![simulator screen shot - iphone x - 2019-02-22 at 12 04 42](https://user-images.githubusercontent.com/5586039/53238792-8eca5900-369a-11e9-88a3-51e457b8392a.png)

**Comment by johnpryan** [comment]
I think this was fixed in https://github.com/johnpryan/flutter_map/pull/249
