### ISSUE TITLE
Detect map onTap

### ISSUE THREAD

**Issue by BGomes17** [johnpryan/flutter_map#235]
Hi,

Is it possible to detect if the user clicked in the map area?
For instance, I want to show information about a marker when the user tap on the marker and then remove that info when the user click in another place on the map. Is this possible?

Thanks in advance,

**Comment by RaimundWege** [comment]
@BGomes17 yes it is possible. You can define a `handleOnMapTapped` with your `MapOptions`:
```
MapOptions(
  minZoom: 1.0,
  maxZoom: 19.0,
  zoom: 13.0,
  onTap: (point) => print(point),
  onPositionChanged: (mapPosition) => print(mapPosition),
  center: LatLng(0.0, 0.0),
)
```

**Comment by BGomes17** [comment]
Thank you very much, I was missing the parameter point in the onTap().
It worked like a charm.

Thank you,
