### ISSUE TITLE
move animated using different zoom levels

### ISSUE THREAD

**Issue by aytunch** [johnpryan/flutter_map#236]
The [animated_map_controller.dart](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/animated_map_controller.dart) example in example directory shows how to move(pan) in an animated way but it doesn't move(zoom) in an animated way. In the example there is a comment saying:

`controller.addListener(() {
      // Note that the mapController.move doesn't seem to like the zoom animation. This may be a bug in flutter_map.
      mapController.move(
          LatLng(_latTween.evaluate(animation), _lngTween.evaluate(animation)),
          _zoomTween.evaluate(animation));
    });`

Is there a way to zoom in an animated manner?

**Comment by pintomic** [comment]
I stumbled upon the same problem today and figured out that the restriction stems from the maxZoom being set to 5.0 on the MapOptions. Changing that to 10.0 enables the animation.

**Comment by aytunch** [comment]
@pintomic Thanks for this info. Zooming is working with animation as expected now
