### ISSUE TITLE
offline pngs not visible

### ISSUE THREAD

**Issue by dyardyGIT** [johnpryan/flutter_map#238]
I have png's that are working well in html leaflet web page, however when i put in assets directory (add them to yaml), put new center point on top of them with lat/long I just do not see them.  The map just appears gray.  Just not sure why.  
I even took my pngs put them in the 0.5.0 offline_map.dart page, changed the lat/long and zoom but still nothing.  I know they are in the apk file.
Ideas?

**Comment by dyardyGIT** [comment]
Solved my issue
I saw in your readme you added tms format (fantastic timing)
   this.tms = false (default) as soon as i set to true it aligned up.

I noticed in html leaflet for my png's this setting .. which sparked a thought when i saw your recent addition of tms format > thanks!
// Overlay layers (TMS)
var lyr = L.tileLayer('./{z}/{x}/{y}.png', {tms: true, opacity: 0.7, attribution: ""});

**Comment by johnpryan** [comment]
shout to to @bugWebDeveloper https://github.com/johnpryan/flutter_map/pull/214
