### ISSUE TITLE
Problem with flutter run --profile

### ISSUE THREAD

**Issue by TH-Productions** [johnpryan/flutter_map#242]
When I try to install my App using the flutter_map package with  flutter run --profile I get the following error.

```

flutter run --profile
Initializing gradle...                                              3.5s
Resolving dependencies...                                           3.4s
Launching lib/main.dart in profile mode...
../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 1839: error: Want to drop class Library:'package:latlong/latlong.dart' Class: Vincenty, but it has 1 instances
                                                                        
thread=19414, isolate=isolate(0x1b3d4b0)                                
  [0x0000000000482f7c] Unknown symbol                                   
  [0x0000000000482f7c] Unknown symbol                                   
-- End of DumpStackTrace                                                
Dart snapshot generator failed with exit code -6                        
Snapshotting exited with non-zero exit code: -6                         
Running Gradle task 'assembleProfile'...                                
Running Gradle task 'assembleProfile'... Done                      28.9s
Gradle task assembleProfile failed with exit code 1
```

I already tried to remove all packages and reinstall them to see if something would change but I always get the same error.

**Comment by johnpryan** [comment]
hmm. This part seems odd:

```
error: Want to drop class Library:'package:latlong/latlong.dart' Class: Vincenty, but it has 1 instances
```

Do you know what `Vincenty` could be referring to? I don't see it anywhere in the latlong package

**Comment by johnpryan** [comment]
Ah... It looks like it  could be an issue with the latlong package https://github.com/MikeMitterer/dart-latlong or a bug with the AOT compiler

**Comment by TH-Productions** [comment]
I tried to install the same project using other computer and it worked fine. It has to had been a bug in the installation maybe or as you say with de compiler. 
I would try to reinstall flutter and see if that solves the problem.

Thx for the quick answers

**Comment by Benassou** [comment]
I have the same problem. I redownloaded the flutter SDK but no luck. Does anyone know a workaround?

**Comment by johnpryan** [comment]
This seems like an issue with your local setup on windows. Please re-open if I'm misunderstanding
