### ISSUE TITLE
add support for cached_network_image 0.7+

### ISSUE THREAD

**Issue by pepie** [johnpryan/flutter_map#263]
Because flutter_map >=0.5.0 depends on cached_network_image ^0.5.1 and <app> depends on cached_network_image 0.7.0, flutter_map >=0.5.0 is forbidden.
So, because <app> depends on flutter_map 0.5.0, version solving failed

**Comment by joserocha3** [comment]
Same as #234

**Comment by johnpryan** [comment]
fixed in https://github.com/johnpryan/flutter_map/pull/268
