### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by MauriPastorini** [johnpryan/flutter_map#264]
Hello, many thanks for the library 
Can I use this library for heatmap feature? If not can I integrate it somehow with other tech? 
Thanks

**Comment by RaimundWege** [comment]
@MauriPastorini right now it is not possible but I guess after this PR is merged: https://github.com/johnpryan/flutter_map/pull/218 you can try out to build your own tile provider which creates the heat map as overlay tiles on the fly with your data. How is your heat map data currently stored?

**Comment by MauriPastorini** [comment]
Great! I have on the server a lot of points store on Redis. I had to implement native code on both ios and android in order to implement this feature. On google maps I had a heatmap feature where I set the points, gradient, radius, among other parameters, and it builds the heat map.
Did I answer the question?

**Comment by johnpryan** [comment]
#218 has been merged. You can take a look at the [plugin example](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/plugin_api.dart) for ideas on how to render custom layers

**Comment by TheLastGimbus** [comment]
Hey @MauriPastorini, I'm currently looking into drawing the heatmap myself - could show me what approach did you take?

**Comment by Renneke** [comment]
I would also be interested to see an example of a heat map implementation :)

**Comment by hm122** [comment]
+1 for a heatmap example :)

**Comment by rafaelmaia8384** [comment]
+1 for the heatmap implementation!

**Comment by riveraj33** [comment]
Hi All. Just wanted to see if there is any update on a heatmap implementation. thanks!
