### ISSUE TITLE
Looking for some clarification with streams

### ISSUE THREAD

**Issue by VeprUA** [johnpryan/flutter_map#272]
Hello!
I'm a huge fan of this library! loved working with Leaflet on JS side and to learn that there is a flutter alternative 👍.

So I was wondering if someone can give me some clarification for what is the `rebuild` stream is used for? 

Correct me if I am wrong, but basically after looking through the source code, the typical use case is to redraw the markers, but the markers aren't coming through every event of the stream, instead they are fetched from the markers parameter. Wouldn't just be easier for the end-user to just create a Streambuilder that returns a list of markers as an option?

I would love to just hook up firestore stream and make my markers that way. If this is something that you, authors, interested in perhaps I can make a PR?

Thanks,
Vepr

**Comment by johnpryan** [comment]
Hi,

I would ignore the `rebuild` stream; it was added for a specific use-case. 

You can always call setState with the new markers. If you need to update markers from a stream you could try wrapping the map widget in a `StreamBuilder` and re-building the markers. Hope that helps!

**Comment by VeprUA** [comment]
Thank you)) That was my thoughts as well. Love the project!
