### ISSUE TITLE
Error with the latest flutter sdk and just importing "package:flutter_map/flutter_map.dart" in a hello world app

### ISSUE THREAD

**Issue by arnuarias** [johnpryan/flutter_map#273]
Compiler message:
file:///C:/Users/Usuario/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:75:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///c:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///C:/Users/Usuario/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:168:65: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///c:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: '$runtimeType failed to load ${instructions.uri}',
                                                                ^
file:///C:/Users/Usuario/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///c:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler terminated unexpectedly.
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      12.0s
Gradle task assembleRelease failed with exit code 1

**Comment by johnpryan** [comment]
this is showing errors for a few different packages, specifically `flutter_image`, try filing the issue there unless you think this is specific to flutter_map. Thanks!

**Comment by arnuarias** [comment]
flutter upgrade
git clone https://github.com/johnpryan/flutter_map.git
cd flutter_map/example
flutter build apk

Running "flutter packages get" in example...                       15.7s
Initializing gradle...                                            108.7s
Resolving dependencies...                                               
  224.8s (!)                                       
                                                                        
Compiler message:                                                       
file:///Users/admin/Downloads/OpenGL/flutter_map/lib/src/layer/mbtiles/mbtiles_image_provider.dart:93:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.                                  
 - 'Iterable' is from 'dart:core'.                                      
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/admin/Downloads/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {              
                              ^                                         
file:///Users/admin/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:75:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.                                  
 - 'Iterable' is from 'dart:core'.                                      
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/admin/Downloads/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {              
                              ^                                         
file:///Users/admin/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:168:65: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/admin/Downloads/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: '$runtimeType failed to load ${instructions.uri}',       
                                                                ^       
file:///Users/admin/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.                                  
 - 'Iterable' is from 'dart:core'.                                      
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/admin/Downloads/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {              
                              ^                                         
Compiler terminated unexpectedly.                                       
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      25.6s
Gradle task assembleRelease failed with exit code 1

**Comment by johnpryan** [comment]
what version of the flutter sdk are you using? there's a new version of the flutter_image package that you could try using:

```
dependency_overrides:
  flutter_image: 2.0.0-dev.1
```

**Comment by arnuarias** [comment]
Flutter 1.5.9-pre.148 • channel master • https://github.com/flutter/flutter.git
Framework • revision d53115ab2e (3 hours ago) • 2019-05-09 12:43:51 -0700
Engine • revision 644db5a49c
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 dbe80f3397)
Running "flutter packages get" in example...                        2.2s
Initializing gradle...                                              5.7s
Resolving dependencies...                                          44.8s
                                                                        
Compiler message:                                                       
file:///Users/admin/Downloads/OpenGL/flutter_map/lib/src/layer/mbtiles/mbtiles_image_provider.dart:93:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.                                  
 - 'Iterable' is from 'dart:core'.                                      
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/admin/Downloads/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {              
                              ^                                         
file:///Users/admin/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:75:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.                                  
 - 'Iterable' is from 'dart:core'.                                      
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/admin/Downloads/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {              
                              ^                                         
file:///Users/admin/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:168:65: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/admin/Downloads/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: '$runtimeType failed to load ${instructions.uri}',       
                                                                ^       
file:///Users/admin/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.                                  
 - 'Iterable' is from 'dart:core'.                                      
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/admin/Downloads/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {              
                              ^                                         
Compiler terminated unexpectedly.                                       
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      33.2s
Gradle task assembleRelease failed with exit code 1

**Comment by fvisticot** [comment]
Same error for me ... and I'm blocked to deliver my app :(
Any workaround / suggestion ?

**Comment by aidooyaw1992** [comment]
dependency_overrides:
  flutter_image: 2.0.0-dev.1

didnot work

[√] Flutter (Channel beta, v1.7.8+hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale
    en-US)
    • Flutter version 1.7.8+hotfix.2 at D:\flutter
    • Framework revision 2e540931f7 (5 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0

**Comment by aidooyaw1992** [comment]
Future<ui.Image> _loadImage(img.ImageProvider imageProvider) async {
  var stream = imageProvider.resolve(img.ImageConfiguration.empty);
  var completer = Completer<ui.Image>();
  void listener(img.ImageInfo frame, bool synchronousCall) {
    var image = frame.image;
    completer.complete(image);
    stream.removeListener(listener);
  }

  stream.addListener(listener);
  return completer.future;
}


this part is also having an error
