### ISSUE TITLE
Calculate distance between two markers.

### ISSUE THREAD

**Issue by thanooshan** [johnpryan/flutter_map#277]
I'm trying to calculate the distance between two markers in-order to show the nearest marker's details in the app. But couldn't able to find solution for it.  Does anyone know how to calculate the distance between two markers?

**Comment by strxetics** [comment]
here's a java solution that i have used before for that https://github.com/mgavaghan/geodesy maybe it helps ;)

**Comment by ibrierley** [comment]
Doesn't the LatLng Module contain distance methods, I'm sure I've used that in the past (not able to double check atm)

**Comment by cetorres** [comment]
I'm using the Distance class, part of latlong package.

static double calculateDistance(LatLng p1, LatLng p2) {
    final Distance distance = new Distance();
    return distance.as(LengthUnit.Meter, p1, p2);
  }

**Comment by thanooshan** [comment]
@cetorres Your solution worked!. Thanks mate..

**Comment by cetorres** [comment]
No problem @thanooshan

**Comment by ruqaiyasattar** [comment]
@cetorres How you calculate time to reach from one destination to other ?

**Comment by JaffaKetchup** [comment]
@ruqaiyasattar This is a use-case for routing machines. Please see our FAQ for more info.

**Comment by ruqaiyasattar** [comment]
share me link please

**Comment by JaffaKetchup** [comment]
The bottom the landing page of the docs site. And/or the Polyline docs page.
