### ISSUE TITLE
Since 0.5.1 - Pinching map to zoom results in the map breaking

### ISSUE THREAD

**Issue by jacksos101** [johnpryan/flutter_map#281]
Since the latest update (I think), pinching the map to zoom in/out results in the map doing very weird things.

This can be seen on the example app. When you pinch to zoom towards London, you end up way out in the ocean.

Offline maps are also going blank when pinching to zoom - I'm guessing the map is being panned way beyond the available tileset.

**Comment by jesusrp98** [comment]
Can confirm this, the pinch to zoom feature is completely broken in this release.

**Comment by khaskelberg** [comment]
This happens because of this change https://github.com/johnpryan/flutter_map/commit/d74b249d16ca7f0ec50e5a2f3ab7d94795e07076#diff-d0fc1fe821e34169c8068a76a40415f3L171

Reverting this should fix zoom issues

**Comment by johnpryan** [comment]
Thanks for your patience, @khaskelberg thanks for looking into the issue
