### ISSUE TITLE
Update cache_network_image to 0.8.0

### ISSUE THREAD

**Issue by jesusrp98** [johnpryan/flutter_map#282]
I know this is a recurrent issue, but I'd like to use the latest stable version of this package.

**Comment by aytunch** [comment]
It says:

> Because flutter_map 0.5.1 depends on cached_network_image ^0.7.0 and no versions of flutter_map match >0.5.1 <0.6.0, flutter_map ^0.5.1 requires cached_network_image ^0.7.0.

It seems with every new cached_network_image version, we as flutter_map lovers will open up a new issue and wait for the solution:((

**Comment by jesusrp98** [comment]
I know right?

Wouldn't be easier for all of us just to update the `pubspec.yaml` file to pick the latest `cache_network_image` release?

**Comment by johnpryan** [comment]
Just a friendly reminder that you can always use `dependency_overrides` in your pubspec while waiting for flutter_map to upgrade the pubspec. It's also slightly faster when there's a pull request :)

**Comment by aytunch** [comment]
how do we use it? can somebody be polite enough to show it?

**Comment by aytunch** [comment]
@jesusrp98 could you work it out the way John suggested?

**Comment by johnpryan** [comment]
something like:

```
# pubspec.yaml
dependency_overrides:
  cached_network_image: 0.8.0
```

**Comment by jesusrp98** [comment]
Already created the #288 pull request.
Pull it if you will, and tell me if anything's wrong :)

**Comment by johnpryan** [comment]
Thanks!
