### ISSUE TITLE
Failed to run the example code!

### ISSUE THREAD

**Issue by azamsharp** [johnpryan/flutter_map#283]
When I am running the sample app, I am getting the following error: 

Error output from CocoaPods:
↳

    [!] [!] Xcodeproj doesn't know about the following attributes
    {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the
    'PBXShellScriptBuildPhase' isa.
    If this attribute was generated by Xcode please file an issue:
    https://github.com/CocoaPods/Xcodeproj/issues/new

    [!] [!] Xcodeproj doesn't know about the following attributes
    {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the
    'PBXShellScriptBuildPhase' isa.
    If this attribute was generated by Xcode please file an issue:
    https://github.com/CocoaPods/Xcodeproj/issues/new

    [!] Automatically assigning platform `ios` with version `8.0` on target
    `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone Xʀ.

**Comment by smasato** [comment]
Please refer to this issue.
https://github.com/CocoaPods/CocoaPods/issues/7835
