### ISSUE TITLE
Cannot async add marker (setState() called after dispose())

### ISSUE THREAD

**Issue by dimitristaufer** [johnpryan/flutter_map#285]
First of all, thank you so much for putting all the time into making this awesome widget!

I'm using a basic FlutterMap() embedded in a ListView() in a Stateful Widget.

Within the initState() function, I call the function **addPositionMarker()** to asynchronously fetch the users location and once finished, add a marker with this location to the List of markers my FlutterMap() uses. I then call setState() to update the map.

    void addPositionMarker() async {
    
    Position currentPosition = await sharedLocationInstance.currentLocation();

    setState(() {
      markers.add(Marker(
        width: 40.0,
        height: 40.0,
        point: new LatLng(currentPosition.latitude, currentPosition.longitude),
        builder: (ctx) => new Container(
              child: pulse,
            ),
      ));
    });

I however get a _setState() called after dispose()_ error in my debug console.

**Could this be related to using FlutterMap() inside a ListView() and the Flutter Plugin disposing the widget after being initialised?**

Any help would highly be appreciated. Thanks in advance.

**Comment by johnpryan** [comment]
I think this is happening because Flutter will dispose your ListView's widgets at certain points. You need to check `isMounted` in this case

**Comment by dimitristaufer** [comment]
Thanks for your answer :)
