### ISSUE TITLE
Plugin not compatible with flutter 1.6

### ISSUE THREAD

**Issue by kunit1** [johnpryan/flutter_map#286]
Since upgrading flutter to 1.6 this plugin will not compile. The following error is thrown.

`Compiler message:
file:///D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.5.2/lib/src/layer/mbtiles/mbtiles_image_provider.dart:93:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///D:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {`

Please see the comments from the flutter devs regarding this issue: [31962](https://github.com/flutter/flutter/issues/31962)

Please also use flutter_image 2.0.0-dev.1 as a dependency as it has a fix for this issue also.

**Comment by johnpryan** [comment]
I don't think this is something that can be fixed in this package

**Comment by kunit1** [comment]
From my understanding, there is a breaking change in flutter. Any packages using the information collector parameter is affected. This package is using that on line 93 in file mbtiles_image_provider.dart

Additionally, this package depends on version 1.0.0 of flutter_image which is also affected by the breaking change. The flutter team fixed flutter_image in flutter_image 2.0.0-dev.1 so this package also needs to update the dependency.

**Comment by johnpryan** [comment]
Ok. I'm not sure there's anything we can do at the moment so I'm going to close until this reaches stable. Please use `dependency_overrides` in pubspec.yaml to work around any dependency issues.
