### ISSUE TITLE
Drawing Directions On Map

### ISSUE THREAD

**Issue by ignertic** [johnpryan/flutter_map#287]
New to the lib, how can i be able to calculate directions between two specified points preferably when user is offline.

**Comment by ibrierley** [comment]
Do you mean just a general angle direction, or do you mean something like street directions (which I guess would be tricky offline).

**Comment by johnpryan** [comment]
I think something like this has already been asked here: https://github.com/johnpryan/flutter_map/issues/205#issuecomment-454861982 

It's a tricky problem and I'm not aware of a solution that's available right now. Google Maps might be your best option but requires the user to be online

**Comment by ignertic** [comment]
@ibrierley yes it would be very tricky but i managed to get a solution tho it's not much of a Flutter Solution tho. Instead of doing the routing on clients phone, it will be done by the server. The app will be on operating on a LAN where the server will be deployed as well but thank you all for your effort
 
And @johnpryan thank you for such a great project, will be looking forward to contribute :)

**Comment by icnahom** [comment]
@ibrierley @ibrierley 

Hey! I want to load the map from assets (offline) but draw the route on it by making an API call to the server (OSRM). Can this be achieved? 

To clarify:
- I don't want to load the map tiles from the server. I just want to draw a polyline from a json data that I get from the routing server.

**Comment by ibrierley** [comment]
Yes, I don't see a problem, just convert the json to a list of latlngs, and then pass to flutter_maps polyline layer ?
