### ISSUE TITLE
Position Indicator Icon

### ISSUE THREAD

**Issue by aleffabricio** [johnpryan/flutter_map#289]
Hello, does anyone have any tips on how to put a current position indicator, similar to google maps that has the blue icon indicating the actually position. And when the user moves the  indicator icon will walk along.

**Comment by ibrierley** [comment]
Well, I guess you would use a stream from the gps, and if the lat/lng has changed (which will probably happen if listening to the stream anyway), you can just update the marker coords, and call setState on the map ?

**Comment by synw** [comment]
I made a package that does exactly this: https://github.com/synw/livemap

**Comment by johnpryan** [comment]
👍 Created an issue to add an example: https://github.com/johnpryan/flutter_map/issues/290

**Comment by aleffabricio** [comment]
> Well, I guess you would use a stream from the gps, and if the lat/lng has changed (which will probably happen if listening to the stream anyway), you can just update the marker coords (actually when I say that, you will probably have to rebuild the marker list each time, rather than update an object), and call setState on the map ?

cool, I was thinking of something like that, using MapPlugin to customize the marker and put it in layers, thanks for the suggestion.

**Comment by aleffabricio** [comment]
> I made a package that does exactly this: https://github.com/synw/livemap

@synw 
Show, thanks for the help. Just ask one more thing I do not know if it would be for another topic, but with this icon interacts with the gyroscope, for example, if I turn the device to the side the icon also rotates according to the movement?
