### ISSUE TITLE
Edit Marker Class to add extra fields.

### ISSUE THREAD

**Issue by daehruoydeef** [johnpryan/flutter_map#293]
Would it be possible to edit the Marker Class to add some extra fields like time of the day or a custom String associated with the Marker.

**Comment by aytunch** [comment]
@daehruoydeef You can always extend `Marker` Class to add whatever extra info you need to have. I guess everybody will have different needs so It is best to keep `Marker` Class contained within its basic needs.

**Comment by daehruoydeef** [comment]
Thanks worked as you told!

**Comment by Pepslee** [comment]
> @daehruoydeef You can always extend `Marker` Class to add whatever extra info you need to have. I guess everybody will have different needs so It is best to keep `Marker` Class contained within its basic needs.

But plugins described in documentation can`t work with extended Marker class.

**Comment by ibrierley** [comment]
If stuck I assume you can create a closure around the marker eg c being any data...

```
Marker createMarker(point, c) {
    return Marker(
      point: point,
      builder: (ctx) =>
          Container(
            child: IconButton(
              icon: Icon(Icons.location_on),
              color: Color.fromARGB(255, 3, 249, 32),
              onPressed: () {
                print("clicked $c");
              },
            ),
          )
    );
```

**Comment by Pepslee** [comment]
> 

With simple Marker in flutter_map it`s work fine. But I also use some plugins which do some work with Markers inside callback functions, like cluster building. And I want to have access to my custom field inside these callbacks.

**Comment by Pepslee** [comment]
> If stuck I assume you can create a closure around the marker eg c being any data...
> 
> ```
> Marker createMarker(point, c) {
>     return Marker(
>       point: point,
>       builder: (ctx) =>
>           Container(
>             child: IconButton(
>               icon: Icon(Icons.location_on),
>               color: Color.fromARGB(255, 3, 249, 32),
>               onPressed: () {
>                 print("clicked $c");
>               },
>             ),
>           )
>     );
> ```

With simple Marker in flutter_map it`s work fine. But I also use some plugins which do some work with Markers inside callback functions, like cluster building. And I want to have access to my custom field inside these callbacks.

**Comment by ibrierley** [comment]
Think we've been here before. I can't remember if it's a cluster plugin issue or marker issue (prob both). Maybe pop up a minimal example to highlight the issue.

**Comment by Pepslee** [comment]
> MarkerClusterLayerOptions(
>     popupOptions: PopupOptions(
>                         popupBuilder: (context, marker) {
>                           return Card(
>                             child: Text(
>                               marker.customField,
>                               style: const TextStyle(color: Colors.white),
>                             ),
>                           );
>                         })

I have attached some example with cluster above.

**Comment by aytunch** [comment]
@Pepslee this is what I use along with the cluster plugin and it works fine for me

```
import 'package:flutter/material.dart';

import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

class EventMarker extends Marker {
  final int eventsCount;

  EventMarker({
    Key? key,
    required LatLng point,
    required WidgetBuilder builder,
    double width = 30.0,
    double height = 30.0,
    bool? rotate,
    Offset? rotateOrigin,
    AlignmentGeometry? rotateAlignment,
    AnchorPos? anchorPos,
    required this.eventsCount,
  }) : super(
          key: key,
          point: point,
          builder: builder,
          width: width,
          height: height,
          anchorPos: anchorPos,
          rotate: rotate,
          rotateOrigin: rotateOrigin,
          rotateAlignment: rotateAlignment,
        );
}

and inside of the `MarkerClusterLayerOptions` you need to do a simple casting:
```

markers: generateEventMarkers(
                          addressCategoriesActivitiesTuple3List:
                              addressCategoriesActivitiesTuple3List),
                      builder: (context, markers) {
                        if (markers.isEmpty) {
                          return const SizedBox.shrink();
                        }
                        List<EventMarker> eventMarkers =
                            markers.map((e) => e as EventMarker).toList();
                        return EventsClusterWidget(
                          markers: eventMarkers,
                          zoom: widget.mapController.zoom,
                        );
                      },
```

```
