### ISSUE TITLE
OverlayImage fails

### ISSUE THREAD

**Issue by Victor-emil** [johnpryan/flutter_map#294]
Hi there,

Thank you for a great library. 

I have been using the library without any issues until I started using OverlayImages. At first I thought that the issue was with my own code, but I am currently using the example code to add an image to the map as an overlay and it also fails. I have tested on my own Samsung S6 galaxy and also the Nexus 5X emulator in Android Studio.

An excerpt of the stack trace:

![image](https://user-images.githubusercontent.com/8555068/58475067-38fbc600-814d-11e9-9e55-fb4374da3eda.png)

The OverlayImage gets loaded after a couple of seconds, but it seems like the code tries to call "width" before it has been computed. This results in a bunch of "NoSuchMethodError: The getter 'width' was called on null." exceptions. It also stops running the remaining code. I have tried using a network image, but also an asset image. The amount of exceptions thrown decreases if I use an asset image. Probably because it loads faster than a network image and the width attribute becomes available faster.

![image](https://user-images.githubusercontent.com/8555068/58475500-6ac15c80-814e-11e9-8858-65e59be8fbfc.png)

**Comment by aleffabricio** [comment]
Hello, @Victor-emil were you able to get around this problem?

**Comment by ay8s** [comment]
Seeing the same. Can get one Overlay Image showing but a second one doesn't display.

**Comment by johnpryan** [comment]
paging @4kssoft

**Comment by ay8s** [comment]
Releasing an app tomorrow without the overlays and will add them next week. Would happily send someone a coffee/beer or something if anyone has a fix 👍 

Right now thinking of combining the 2 overlays to work around the issue.

**Comment by 4kssoft** [comment]
PR https://github.com/johnpryan/flutter_map/pull/365

**Comment by spvalencia** [comment]
I have the same issue

**Comment by 4kssoft** [comment]
Master version works well without errors

![flutter_01](https://user-images.githubusercontent.com/16765325/61983438-a8cce680-b000-11e9-8d7e-4734aa0a7fc7.png)

**Comment by johnpryan** [comment]
#365 is now published in version 0.7.0
