### ISSUE TITLE
Update path_provider version?

### ISSUE THREAD

**Issue by bmelnychuk** [johnpryan/flutter_map#298]
Is it possible to update path_provider version to the latest?

```
To be more specific 
Because flutter_map >=0.5.3 depends on path_provider ^0.5.0+1 and graphql_flutter >=1.0.1-beta.8 depends on path_provider ^1.1.0, flutter_map >=0.5.3 is incompatible with graphql_flutter >=1.0.1-beta.8.
```

Thanks

**Comment by lsaudon** [comment]
It is `cached_network_image` that uses `flutter_cache_manager` which did not update the dependency.
https://github.com/renefloor/flutter_cache_manager/pull/85

**Comment by bmelnychuk** [comment]
I see, thanks
