### ISSUE TITLE
tileset and style not working

### ISSUE THREAD

**Issue by virshlee** [johnpryan/flutter_map#304]
I tried to use my own style. I wanted to use a mapbox style, so I made one on the mapbox site. I used the   mapbox streets v8 id. This is the error I got.
 
E/flutter ( 7002): [ERROR:flutter/lib/ui/painting/codec.cc(97)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
I/flutter ( 7002): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 7002): The following _Exception was thrown resolving an image codec:
I/flutter ( 7002): Exception: operation failed
I/flutter ( 7002): 
I/flutter ( 7002): When the exception was thrown, this was the stack:
I/flutter ( 7002): #0      CachedNetworkImageProvider._loadAsyncFromFile (package:cached_network_image/src/cached_network_image_provider.dart:78:12)
I/flutter ( 7002): <asynchronous suspension>
I/flutter ( 7002): #1      CachedNetworkImageProvider._loadAsync (package:cached_network_image/src/cached_network_image_provider.dart:64:18)
I/flutter ( 7002): <asynchronous suspension>
I/flutter ( 7002): #2      CachedNetworkImageProvider.load (package:cached_network_image/src/cached_network_image_provider.dart:44:14)
I/flutter ( 7002): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:315:48)
I/flutter ( 7002): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:157:22)
I/flutter ( 7002): #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:315:25)
I/flutter ( 7002): #6      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter ( 7002): #7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:312:11)
I/flutter ( 7002): #11     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:304:16)
I/flutter ( 7002): #12     _ImageProviderResolver.resolve (package:flutter/src/widgets/fade_in_image.dart:370:29)
I/flutter ( 7002): #13     _FadeInImageState._resolveImage (package:flutter/src/widgets/fade_in_image.dart:445:20)
I/flutter ( 7002): #14     _FadeInImageState.didChangeDependencies (package:flutter/src/widgets/fade_in_image.dart:427:5)
I/flutter ( 7002): #15     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862:12)
I/flutter ( 7002): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 7002): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7002): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 7002): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 7002): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 7002): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 7002): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7002): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 7002): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 7002): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 7002): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 7002): #29     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter ( 7002): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #31     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter ( 7002): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7002): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 7002): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7002): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 7002): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 7002): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 7002): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 7002): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7002): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 7002): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 7002): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 7002): #46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 7002): #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 7002): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #49     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter ( 7002): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7002): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 7002): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 7002): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 7002): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 7002): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)

**Comment by virshlee** [comment]
I made a new style and it worked, there was something specific problem with the other one.

**Comment by FalkF** [comment]
@virshlee 
Could you please wrap your exception in code tags?
Otherwise you are referencing issue 1-54 and everybody watching these will eventually land here :D
for example: https://github.com/johnpryan/flutter_map/issues/56
