### ISSUE TITLE
Version 0.6.0+1

### ISSUE THREAD

**Issue by lpongetti** [johnpryan/flutter_map#314]
Not compatible with stable channel..
This decrease ranking in pub https://pub.dev/packages/flutter_map/versions/0.6.0+1#-analysis-tab-

You have release 0.6.0 from dev branch

**Comment by lpongetti** [comment]
Ok i see now 5.4.0

**Comment by johnpryan** [comment]
0.5.x releases are compatible with the stable channel, whereas 0.6.x are released from the dev branch and only compatible with the dev channel. see the CHANGELOG.md for details
