### ISSUE TITLE
What's the correct version to use!?!?!

### ISSUE THREAD

**Issue by sjmcdowall** [johnpryan/flutter_map#319]
I am pretty confused as to what version should be used now .. it went to 0.6.X and now it's back to 0.5.5?!

**Comment by lpongetti** [comment]
0.5.x is to use for channel stable.. 0.6.x channel beta

**Comment by johnpryan** [comment]
see CHANGELOG.md for details

**Comment by sjmcdowall** [comment]
@johnpryan -- I read the CHANGELOG.md in master here and it doesn't mention 0.6 at all .. but you published 0.6. and I guess it's there from dev branch .. so I think I have it.. but I still find it confusing LOL

**Comment by johnpryan** [comment]
https://github.com/johnpryan/flutter_map/blame/master/CHANGELOG.md#L10

**Comment by johnpryan** [comment]
I'll update the README, thanks for the feedback
