### ISSUE TITLE
Should the API Docs be showing the dev branch?

### ISSUE THREAD

**Issue by 19smitgr** [johnpryan/flutter_map#320]
Is the API documentation page supposed to show the docs for the dev branch? Unfortunately it looks like the docs aren't being generated by pub.dev for v0.6.1+2, so I had to manually switch back to the docs for v0.5.4

**Comment by johnpryan** [comment]
This was a mistake on my part - pub automatically generates docs and computes a package score based on the latest released version - I think 0.6.0 should have been something like 0.6.0-dev.0 but it's too late to change it now I think

**Comment by 19smitgr** [comment]
Yeah I figured for people new to flutter_maps, that could be confusing

**Comment by johnpryan** [comment]
I'm considering publishing the latest master branch as 0.7.0 to work around this issue

**Comment by johnpryan** [comment]
0.7.0 has been published and works with flutter stable and master
