### ISSUE TITLE
plugin clustering

### ISSUE THREAD

**Issue by lpongetti** [johnpryan/flutter_map#323]
Hi,
i have to make the plugin flutter_map_marker_cluster private for a little

**Comment by Nachodlv** [comment]
hi @lpongetti ! Do you know when it will be made public again? My team is highly interested in your work so any feedback will be useful.
Thanks mate.

**Comment by johnpryan** [comment]
I'm sorry to hear that! What's the reason?

**Comment by lpongetti** [comment]
Hi, i hope next week

**Comment by Akshar-Patel** [comment]
@lpongetti I am waiting for it.

**Comment by lpongetti** [comment]
Is public

**Comment by lpongetti** [comment]
Is public
