### ISSUE TITLE
Markers `onTap` not working with polylines

### ISSUE THREAD

**Issue by FalkF** [johnpryan/flutter_map#324]
When a polyline is present the markers `onTap` function is not invoked.
The polyline does not need to overlap a marker.

example: 
https://github.com/FalkF/flutter_map/commit/56760dfb53d122a7a36af252c87c2a08d69f666a

Older comment: https://github.com/johnpryan/flutter_map/issues/119#issuecomment-423868626

**Comment by johnpryan** [comment]
Does it work if you change the ordering so that MarkerLayerOptions is after the PolylineLayerOptions?

**Comment by FalkF** [comment]
Indeed, well i should have come up with that myself :see_no_evil:
