### ISSUE TITLE
Use offline mode with raster from sentinel-2 ( JP2 )

### ISSUE THREAD

**Issue by eaedk** [johnpryan/flutter_map#325]
Hi please, I need help to use your plugin with offline sentinel-2 in JP2 store on device from https://scihub.copernicus.eu/dhus/#/home

**Comment by johnpryan** [comment]
Unless you provide some more information, I don't think this is something anyone can help with. Is there a specific issue you are seeing with flutter_map?

**Comment by eaedk** [comment]
My rasters are in JP2 format and i don't know how to do to use it as a tiles

**Comment by johnpryan** [comment]
You might try [CustomTileProvider](https://github.com/johnpryan/flutter_map/blob/0d0b1916134c2ee30368602b13663ae3bef05c7d/lib/src/layer/tile_layer.dart#L567)

**Comment by eaedk** [comment]
ok thanks... is your plugin working for FLUTTER WEB ??

**Comment by johnpryan** [comment]
I don't think anyone has tested this with flutter_web yet. I assume it
would work since it is written entirely in Dart.

**Comment by eaedk** [comment]
I get an error, when i try to use flutter_map in my flutter_web project ...

pub get
Resolving dependencies...
The current Dart SDK version is 2.3.0-dev.0.5.flutter-a1668566e5.

Because flutter_map <0.1.0 requires SDK version >=1.8.0 <2.0.0 and flutter_map >=0.6.0 requires the Flutter SDK, flutter_map is forbidden.
So, because first_project depends on flutter_map any, version solving failed.

Flutter users should run `flutter packages get` instead of `pub get`.
exit code 1
