### ISSUE TITLE
Display a local static image as a map?

### ISSUE THREAD

**Issue by Ericwc1** [johnpryan/flutter_map#330]
I am trying to figure out if this plugin can be used to display a local static image as a map that I can then overlay the users current position on.  See this post for more details,
https://stackoverflow.com/questions/56573073/display-current-location-on-a-local-image-map-in-flutter
Thanks for any help or insight you can provide.

**Comment by johnpryan** [comment]
Leaflet has an imageOverlay API that you might be able to add to this package. You might also consider digging around for what Leaflet users do. I'm not sure it's exactly what you're looking for, but I found [this stackoverflow answer](https://gis.stackexchange.com/a/285518) that might be relevant.

**Comment by escamoteur** [comment]
Hi, I have the same requirement, to use one big image as map. Would this be best added as a plugin?
Thanks

**Comment by johnpryan** [comment]
You can always write a plugin, and there is an OverlayImage layer that can be used as a reference if you need additional features
