### ISSUE TITLE
Failed to Open Database "libCachedImageData.db"

### ISSUE THREAD

**Issue by nedpals** [johnpryan/flutter_map#332]
**Version**: 0.6.1+2
**Flutter**: 1.7.5-pre.14

I have an app that uses `sqflite` and when I start a Flutter map instance, it shows an error that the cached image database cannot be open. I was wondering because of the shared dependencies between the app i worked on and `flutter_map` which is `sqflite` which maybe the reason here. I also looked for solutions like upgrading Flutter and the package and also in the `cached_network_image` pub repo but I have found none of the problems the same as mine. Here's the log output: 

```
cannot open file at line 31320 of [5a3022e081]
E/SQLiteLog(27322): (14) os_unix.c:31320: (20) open(/data/user/0/com.example.app/databases/libCachedImageData.db) -
E/SQLiteDatabase(27322): Failed to open database '/data/user/0/com.example.app/databases/libCachedImageData.db'.
E/SQLiteDatabase(27322): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
E/SQLiteDatabase(27322): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
```

**Comment by johnpryan** [comment]
Yes it's possible that the version of sqflite that flutter_map specifies is an older version. You can try using `dependency_overrides` in your pubspec to force a specific version of sqflite.

**Comment by nedpals** [comment]
@johnpryan I tried it but still doesn't work. Both the `sqflite` version `flutter_map` and my app used is the same.

**Comment by johnpryan** [comment]
To troubleshoot, I would recommend using `dependency_overrides` to find a version that works you. Feel free to file a new issue with the specific version you need.
