### ISSUE TITLE
How to set multi tile layer?

### ISSUE THREAD

**Issue by jasonleung101** [johnpryan/flutter_map#333]
I would like to import more than one layer but I found that if I place two TileLayerOptions, it will return the top layer only but not both layers. Note that one layer is a full map and the other one is just a part of the map. Thanks

**Comment by lou147** [comment]
+1

**Comment by lou147** [comment]
![image](https://user-images.githubusercontent.com/19778108/61013973-aab76880-a3b7-11e9-9782-e3eef546c0bd.png)
Setting Transparent Colors

**Comment by johnpryan** [comment]
Can you explain in more detail what you're trying to do? both layers will end up being drawn, but one might be drawn on top of the other. If you look at the DevTools to inspect the widget hierarchy, you should see widgets from both layers being added to the Stack widget that hosts the layers
