### ISSUE TITLE
Support of ImageOverlay ?

### ISSUE THREAD

**Issue by wawanopoulos** [johnpryan/flutter_map#336]
Hi,
Could you please add support of image overlay inside this flutter_map library ?
Is there any workaround solution to be able to add an image on the map ?
Thanks

**Comment by ZeBrody** [comment]
You can use the MarkerLayerOptions with Marker. Marker uses a builder where you can return an Image Widget.

**Comment by johnpryan** [comment]
@wawanopoulos can you describe more what you mean by overlay? Are you talking about a custom tile layer or a marker, or something else?

**Comment by wawanopoulos** [comment]
@johnpryan I would like to insert an image in overlay on the Map at a specific position. Like this using Leaflet on the web: https://leafletjs.com/reference-1.5.0.html#imageoverlay

**Comment by ay8s** [comment]
Sounds like OverlayImage? https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/overlay_image.dart

**Comment by johnpryan** [comment]
@ay8s is correct, it sounds like OverlayImage is what you're looking for. Feel free to re-open or file an issue if it's not what you need.
