### ISSUE TITLE
How to use custom markers with custom icons ?

### ISSUE THREAD

**Issue by Gausoft** [johnpryan/flutter_map#338]
How to draw map marker widget with Icon as child ?

**Comment by pandagis** [comment]
like this: 
   Marker(
      width: 8.0,
      height: 8.0,
      point: london,
      builder: (ctx) => Container(
        key: Key('blue'),
        child: Icon(Icons.location_on,color: Colors.red,size: 30.0,),
      ),
    ),

**Comment by Gausoft** [comment]
> like this:
> Marker(
> width: 8.0,
> height: 8.0,
> point: london,
> builder: (ctx) => Container(
> key: Key('blue'),
> child: Icon(Icons.location_on,color: Colors.red,size: 30.0,),
> ),
> ),

No, I'am talking about customization. Something like : leaflet-awesome markers : 
![screenshot-soft](https://user-images.githubusercontent.com/26385667/60032439-0f738300-9696-11e9-9a46-95fe8591490f.png)

**Comment by Gausoft** [comment]
> > like this:
> > Marker(
> > width: 8.0,
> > height: 8.0,
> > point: london,
> > builder: (ctx) => Container(
> > key: Key('blue'),
> > child: Icon(Icons.location_on,color: Colors.red,size: 30.0,),
> > ),
> > ),
> 
> No, I'am talking about customization. Something like : leaflet-awesome markers :
> ![screenshot-soft](https://user-images.githubusercontent.com/26385667/60032439-0f738300-9696-11e9-9a46-95fe8591490f.png)

I would l

**Comment by Gausoft** [comment]
> like this:
> Marker(
> width: 8.0,
> height: 8.0,
> point: london,
> builder: (ctx) => Container(
> key: Key('blue'),
> child: Icon(Icons.location_on,color: Colors.red,size: 30.0,),
> ),
> ), 

No, I'am talking about customization. Something like : leaflet-awesome markers :  
 ![screenshot-soft](https://user-images.githubusercontent.com/26385667/60032439-0f738300-9696-11e9-9a46-95fe8591490f.png)
I would like to creat my own marker shape that can support various type of icons like : flutter icons, font-awesome icons, ionicons, etc..

**Comment by johnpryan** [comment]
These can be implemented by tweaking the example above. This isn't something we intent to support directly.

**Comment by felikhn** [comment]
> These can be implemented by tweaking the example above. This isn't something we intent to support directly.

any example how to tweaking it?

**Comment by johnpryan** [comment]
You can return any Widget in the `builder` parameter

**Comment by felikhn** [comment]
> You can return any Widget in the `builder` parameter

noted. thank you
