### ISSUE TITLE
Better transition for unloaded map tiles

### ISSUE THREAD

**Issue by aytunch** [johnpryan/flutter_map#342]
When we drag or zoom in/out the map and the new tiles are not downloaded yet, we see just our background instead of low res tiles like Google maps is doing. This results in bad user experience imho. Is there a way to show scaled up/down version of the loaded tiles in place of the unloaded ones until they are loaded?

The first screenshot is from flutter_map which has no low res image.
Second screenshot is from google maps app which uses a tile image constructed from another zoom levels tile image by scaling down i guess.

![IMG_3365](https://user-images.githubusercontent.com/6442915/60198099-81d89480-9849-11e9-9976-29e15cf26ad1.PNG)
![IMG_3364](https://user-images.githubusercontent.com/6442915/60198100-81d89480-9849-11e9-9a7b-696e18547bea.PNG)

**Comment by johnpryan** [comment]
Thanks - this is a known issue and we're tracking it here: https://github.com/johnpryan/flutter_map/issues/79
