### ISSUE TITLE
Polyline transparency denser at each point.

### ISSUE THREAD

**Issue by wildwalks** [johnpryan/flutter_map#347]
Love this widget -- thanks so much.
When drawing a polyline with transparency each point it twice as dense as the line - I think the transparency should be uniform along the length of the line.  I suspect that the line is been drawn from point A to Point B then from Point B to Point C -- so that Point B gets drawn over twice.

See image, I think this line should not have the darker red circles.

Thanks :)

Polyline(
          color: Color.fromRGBO(255, 0, 0, 0.5),
         strokeWidth: 20,
          isDotted: false,
             points: [array]
![Screenshot_1561765845](https://user-images.githubusercontent.com/1892286/60376632-a30cd100-9a53-11e9-86c7-4c0bbfbaa31a.png)

**Comment by wildwalks** [comment]
I also noticed the same issue appears for "borderStrokeWidth".

**Comment by MichalMisiaszek** [comment]
Me too, I I set line transparency points are more opaque. I guess it is because Polyline sections start/stop overlap.

**Comment by johnpryan** [comment]
A better way to draw this might be to set the opacity on the entire layer, but I haven't looked at the details

**Comment by wildwalks** [comment]
> A better way to draw this might be to set the opacity on the entire layer, but I haven't looked at the details

Thanks John.  Yes it seems the opacity would need to be lifted up, I have tried wrapping the polyline in an opacity() widget as a workaround but the ide tells me that opacity can't be assigned to the parameter type 'Polyline', but I can't find a workaround sorry.

**Comment by johnpryan** [comment]
I think @MichalMisiaszek has found a solution for this.

**Comment by wildwalks** [comment]
Thanks John :)
well done @MichalMisiaszek  -- would love to see it, I had a play and could not find a solution without a fairly significant re-write.

**Comment by MichalMisiaszek** [comment]
> Thanks John :)
> well done @MichalMisiaszek -- would love to see it, I had a play and could not find a solution without a fairly significant re-write.

Sorry, but I did not solved it. I figured out why but did not implemented solution.

**Comment by wildwalks** [comment]
Hi John
Can we please re-open this. I don't have a solution for this yet.
thanks
Matt :)

**Comment by wildwalks** [comment]
Big thanks to @2ZeroSix for her hard work fixing this one :)
It looks great.
Thanks John for your work on the overall project, this is a great tool.
