### ISSUE TITLE
Question - map re-draw completion event.

### ISSUE THREAD

**Issue by MichalMisiaszek** [johnpryan/flutter_map#355]
Hi John,
Thanks again for great plugin. I have a question. I am calling ```mapController.fitBounds``` and then making screenshot of map widget using ```RepaintBoundary``` and ```  FocusScope.of(context).requestFocus(FocusNode());
    await _capturePng()```
Unfortunately sometimes map tiles are not refreshed/downloaded or painted before I make screenshot leading to map with grey background. Any idea how I can wait for plugin to complete painting maps ?
BTW. Can you have two tile layers (like overlay weather tiles on map) ?
Thanks again.

**Comment by johnpryan** [comment]
You could take a look at the ImageProvider that most TileProvider implementations are using to see if this could be exposed to MapController, but it's not clear to me exactly how that would work

**Comment by MichalMisiaszek** [comment]
This is an answer to 2nd or 1st question ? :)

**Comment by johnpryan** [comment]
that was more for the first question, I don't think we have an example of multiple tile layers being used, but it should be possible if the are partially transparent

**Comment by MichalMisiaszek** [comment]
Yea, I tried once with layer which suppose to be transparent but it was looking completely opaque, I will try again. For Map drawing, maybe you know better method ? I tried with hidden widgets but it did not work. I basically want to create image file from map with polylines etc ...

**Comment by johnpryan** [comment]
if you have a small demo it might be easier to debug what's going on, but under the hood we are just using a Stack widget with Positioned widgets. Here's the implementation: https://github.com/johnpryan/flutter_map/blob/master/lib/src/layer/tile_layer.dart#L427

**Comment by MichalMisiaszek** [comment]
I will create small demo app so we can find solution, thanks !

**Comment by MichalMisiaszek** [comment]
Hi John,
Plugin support multiple ```TileLayerOptions``` the trick was to change default background to transparent ! ;) ```backgroundColor: Colors.transparent``` It is not super fast but works. I have weather tiles on map tiles and it us usable. 
Still to solve issue 1.

**Comment by johnpryan** [comment]
I'm going to close this - please file one issue at a time :)

**Comment by MichalMisiaszek** [comment]
Ok, I still do not have a solution to map ready event.

**Comment by johnpryan** [comment]
ok, I've created #377 to track that.
