### ISSUE TITLE
How to keep the map state between two BloC states?

### ISSUE THREAD

**Issue by topnax** [johnpryan/flutter_map#357]
How would one keep the map state (position, zoom) between two BloC states? For example, I display a layer of markers on the map. Users zooms in, moves the pan. Then he decides to search the markers by their name so he clicks a button (SearchState is yielded) in the app bar and a new screen is displayed (instead of map widget a container is returned), he then closes this screen (map is now returned) and the zoom and position context is kept and displayed correctly. Currently, after closing the screen, the zoom and position is not kept and is set to the default one. Could anyone help me please? I am new to kinda BloC pattern and I found it kinda difficult in such cases.

**Comment by johnpryan** [comment]
This sounds like it's unrelated to flutter_map - can you try posting this question on StackOverflow and provide more detail? thanks!
