### ISSUE TITLE
getting the lat long from map when the user taps on it

### ISSUE THREAD

**Issue by mmojbo** [johnpryan/flutter_map#368]
Hi.

I'm new in Flutter and I want just to the following two cases:
1 - moving the map to the user current location (I get the user current location with geolocator plugin)
2 - getting the lat and long from the map when the user taps on it.

thanks for your help.

**Comment by TopHatMatt14** [comment]
You can choose the location that you want the map to display when you initialize the FlutterMap widget. This is done by specifying the center parameter in the MapOptions that you provide it.

```
return new FlutterMap(
    options: new MapOptions(
        center: new LatLng(<LATITUDE>,<LONGITUDE>)
    )
);
```

When the map is already initialized and built, you can move it by providing a MapController object as the mapController parameter for the map. Then call the MapController.move method to display the specified location on the map.

```
MapController mapController = new MapController();
...
return new FlutterMap(
    options: new MapOptions(
        center: new LatLng(<LATITUDE>,<LONGITUDE>)
    )
);
...
mapController.move(new LatLng(<LATITUDE>,<LONGITUDE>), <ZOOM_LEVEL>);
```
Finally, regarding getting the coordinates where a user taps on the map, there is a onTap parameter in MapOptions that you can provide a callback function to. The callback function takes a LatLng object as the only parameter.
```
... new MapOptions(
    onTap: (LatLng location) {
        // DO SOMETHING WITH LOCATION
    }
)
```

**Comment by mmojbo** [comment]
@TopHatMatt14  thanks for your help, but move event has error!
err massege:
`E/flutter (18681): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'move' was called on null.
E/flutter (18681): Receiver: null
E/flutter (18681): Tried calling: move(Instance of 'LatLng', 6.0, hasGesture: false, isUserGesture: false)
E/flutter (18681): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter (18681): #1      MapControllerImpl.move (package:flutter_map/src/map/map.dart:29:12)
E/flutter (18681): #2      _MySfulWidgetState.build.<anonymous closure>.<anonymous closure> (package:mr_asansor/mappage.dart:239:29)
E/flutter (18681): #3      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
E/flutter (18681): #4      _MySfulWidgetState.build.<anonymous closure> (package:mr_asansor/mappage.dart:227:13)
E/flutter (18681): #5      MapGestureMixin.handleTap (package:flutter_map/src/gestures/gestures.dart:94:13)
E/flutter (18681): #6      _TapPositionDetectorState._postCallback (package:positioned_tap_detector/positioned_tap_detector.dart:124:15)
E/flutter (18681): <asynchronous suspension>
E/flutter (18681): #7      _TapPositionDetectorState._onTimeout (package:positioned_tap_detector/positioned_tap_detector.dart:70:7)
E/flutter (18681): #8      _invokeErrorHandler (dart:async/async_error.dart:17:29)
E/flutter (18681): #9      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:286:9)
E/flutter (18681): #10     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:168:13)
E/flutter (18681): #11     _rootRunBinary (dart:async/zone.dart:1144:38)
E/flutter (18681): #12     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
E/flutter (18681): #13     _CustomZone.runBinaryGuarded (dart:async/zone.dart:939:7)
E/flutter (18681): #14     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355:15)
E/flutter (18681): #15     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
E/flutter (18681): #16     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7)
E/flutter (18681): #17     _SyncStreamController._sendError (dart:async/stream_controller.dart:768:19)
E/flutter (18681): #18     _StreamController._addError (dart:async/stream_controller.dart:648:7)
E/flutter (18681): #19     _StreamController.addError (dart:async/stream_controller.dart:600:5)
E/flutter (18681): #20     Stream.timeout.onListen.<anonymous closure> (dart:async/stream.dart:1530:22)
E/flutter (18681): #21     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (18681): #22     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (18681): #23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (18681): #24     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (18681): #25     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (18681): #26     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (18681): #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)`

its my code:
`
onTap: (point) {
            setState(() {
              _markers.add(Marker(
                  width: 80.0,
                  height: 80.0,
                  point: new LatLng(point.latitude, point.longitude),
                  builder: (ctx) => new Container(
                      child: IconButton(
                          icon: Icon(Icons.location_on),
                          color: Colors.indigo,
                          iconSize: 60.0,
                          onPressed: null))));
              print(point);
              mapController.move(new LatLng(point.latitude, point.longitude), 6.0);
            });
`

**Comment by bettdalpha** [comment]
> @TopHatMatt14 thanks for your help, but the move event has an error!
> err massege:
> `E/flutter (18681): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'move' was called on null. E/flutter (18681): Receiver: null E/flutter (18681): Tried calling: move(Instance of 'LatLng', 6.0, hasGesture: false, isUserGesture: false) E/flutter (18681): #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5) E/flutter (18681): #1 MapControllerImpl.move (package:flutter_map/src/map/map.dart:29:12) E/flutter (18681): #2 _MySfulWidgetState.build.<anonymous closure>.<anonymous closure> (package:mr_asansor/mappage.dart:239:29) E/flutter (18681): #3 State.setState (package:flutter/src/widgets/framework.dart:1141:30) E/flutter (18681): #4 _MySfulWidgetState.build.<anonymous closure> (package:mr_asansor/mappage.dart:227:13) E/flutter (18681): #5 MapGestureMixin.handleTap (package:flutter_map/src/gestures/gestures.dart:94:13) E/flutter (18681): #6 _TapPositionDetectorState._postCallback (package:positioned_tap_detector/positioned_tap_detector.dart:124:15) E/flutter (18681): <asynchronous suspension> E/flutter (18681): #7 _TapPositionDetectorState._onTimeout (package:positioned_tap_detector/positioned_tap_detector.dart:70:7) E/flutter (18681): #8 _invokeErrorHandler (dart:async/async_error.dart:17:29) E/flutter (18681): #9 _HandleErrorStream._handleError (dart:async/stream_pipe.dart:286:9) E/flutter (18681): #10 _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:168:13) E/flutter (18681): #11 _rootRunBinary (dart:async/zone.dart:1144:38) E/flutter (18681): #12 _CustomZone.runBinary (dart:async/zone.dart:1037:19) E/flutter (18681): #13 _CustomZone.runBinaryGuarded (dart:async/zone.dart:939:7) E/flutter (18681): #14 _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:355:15) E/flutter (18681): #15 _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16) E/flutter (18681): #16 _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:272:7) E/flutter (18681): #17 _SyncStreamController._sendError (dart:async/stream_controller.dart:768:19) E/flutter (18681): #18 _StreamController._addError (dart:async/stream_controller.dart:648:7) E/flutter (18681): #19 _StreamController.addError (dart:async/stream_controller.dart:600:5) E/flutter (18681): #20 Stream.timeout.onListen.<anonymous closure> (dart:async/stream.dart:1530:22) E/flutter (18681): #21 _rootRun (dart:async/zone.dart:1124:13) E/flutter (18681): #22 _CustomZone.run (dart:async/zone.dart:1021:19) E/flutter (18681): #23 _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23) E/flutter (18681): #24 Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15) E/flutter (18681): #25 _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19) E/flutter (18681): #26 _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5) E/flutter (18681): #27 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)`
> 
> its my code:
> `onTap: (point) { setState(() { _markers.add(Marker( width: 80.0, height: 80.0, point: new LatLng(point.latitude, point.longitude), builder: (ctx) => new Container( child: IconButton( icon: Icon(Icons.location_on), color: Colors.indigo, iconSize: 60.0, onPressed: null)))); print(point); mapController.move(new LatLng(point.latitude, point.longitude), 6.0); });`

It seems like the mapController isn't initialised. change the mapController.move before your setState

**Comment by johnpryan** [comment]
You need to wait for the `onReady` event before you start using MapController. @TopHatMatt14's answer should help you with the original issue.
