### ISSUE TITLE
Dynamically draw and edit polygons, circles, and rectangles with touch

### ISSUE THREAD

**Issue by aleffabricio** [johnpryan/flutter_map#369]
Hello @johnpryan  is it possible to dynamically implement to draw polygons, circles, rectangles? when the user touches the screen mark the points until all vertices are closed, see below an example of the polygon drawing  http://dev.openlayers.org/examples/draw-feature.html and based on the brochure documentation http://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#l-draw

**Comment by johnpryan** [comment]
Yes, there is a polygon layer.

**Comment by bettdalpha** [comment]
You can do this by having a list of LatLng and then when  map on tap is called, it adds the tapped latlng to the list and calls setState to the map which rebuilding the polygon with the new list of LatLng
