### ISSUE TITLE
flutter_map: ^0.6.1+2 with Flutter 1.5.4-hotfix.2 

### ISSUE THREAD

**Issue by fne00** [johnpryan/flutter_map#370]
Hi,
I was using flutter_map: ^0.5.3+1 for a long time ... All very good.
Upgraded Flutter to Flutter 1.7.8+hotfix.3 (also 1.5.4-hotfix.2) and now I get:

Another exception was thrown: type '_BroadcastStream<void>' is not a subtype of type 'Stream<int>'

Same as: https://www.gitmemory.com/issue/johnpryan/flutter_map/311/510472911

The example app builds and runs - but flutter_map: path: ../ has some differences in the code to that is imported from  flutter_map: ^0.6.1+2

Regards Peter

**Comment by lsaudon** [comment]
Use version 0.5.6. 
Versions 0.6.x are for channel dev

**Comment by fne00** [comment]
Thanks - that fixes it.
