### ISSUE TITLE
Change version numbers

### ISSUE THREAD

**Issue by lsaudon** [johnpryan/flutter_map#371]
I think it would be easier to have versions for dev channel in `x.x.x-dev` and `x.x.x` for stable channel.
The current versions are unclear.

**Comment by johnpryan** [comment]
That's a good idea - I think what we can do is tag 0.7.0 as the next stable channel release and let 0.7.x-dev be reserved for the dev channel

**Comment by johnpryan** [comment]
0.7.0 has been released and is compatible with stable an master (for now)
