### ISSUE TITLE
Not really an issue, support in refactoring a geolibrary which already implements OGC simple features specification.

### ISSUE THREAD

**Issue by bettdalpha** [johnpryan/flutter_map#372]
I'm sorry if this is the wrong place to mention this, but @johnpryan lemme share this here since it's map related.
If you check out the repository below, 
https://github.com/Gubaer/dart-simple-features its a dart library written in dart version 1. The library implements Open Geospatial Consortium standard simple-features which handles most of the conversions you would do by hand, like getting area, conversion from geojson to lists. Since it depends on avl_tree which is also written in dart version 1 (but i've been refactoring lately so I need someone to review the code for me) It's processing speeds are fast. 

[https://github.com/Gubaer/dart-simple-features/blob/master/README.md](dart-simple-features)

So I'm just asking if there could be any interested parties in helping refactor this library as most features have already been implemented. Making this work could be a big boost for users using flutter_map already.

**Comment by johnpryan** [comment]
I'm going to have to close this In order to keep the number open issues manageable. You might have better luck reaching out on other channels like Gitter.

**Comment by bettdalpha** [comment]
Lemme try
