### ISSUE TITLE
How to adjust the maxZoom and minZoom after loading the map?

### ISSUE THREAD

**Issue by moonhx** [johnpryan/flutter_map#373]
I want to change maxZoom and minZoom after loading the map. Can you help me? Thanks

**Comment by johnpryan** [comment]
you should be able to call `setState()` and the map will reflect those changes.

**Comment by moonhx** [comment]
I know，But maxzoom and minzoom are modified by final and cannot be changed.

**Comment by johnpryan** [comment]
Many properties on widgets are `final` in flutter, but that doesn't  they can't be changed. For example, `AppBar` has many `final` properties but they can be changed by calling `setState()` with a new value passed to them.

**Comment by moonhx** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
    LatLng swPanBoundary;
    LatLng nePanBoundary;
    MapController mapController;
    double maxZoom = 6.0;
    double minZoom = 4.0;
    initState(){
      // this.swPanBoundary = LatLng(50.5, -1.18);
      // this.nePanBoundary = LatLng(52.5, 1.06);
      mapController = MapController();
    }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('home'),
      ),
      body: Padding(
        padding: EdgeInsets.all(8.0),
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                   Text('Try tapping on the markers'),
                   RaisedButton(
                     child: Text('change zoom'),
                     onPressed: (){
                       setState(() {
                        // this.mapController.move(LatLng(52.5, 0.5), 3);
                        // this.options.swPanBoundary = LatLng(40.5, -20.18);
                        // this.options.nePanBoundary = LatLng(62.5, 10.06);
                        this.maxZoom = 18.0;
                        this.minZoom = 2.0;
                        print('change maxZoom to ${this.maxZoom}');
                       });
                     },
                   )
                ],
              ),
            ),
            Flexible(
              child: FlutterMap(
                mapController: this.mapController,
                options: MapOptions(
                  center: LatLng(51.5, -0.09),
                  zoom: 5.0,
                  maxZoom: this.maxZoom,
                  minZoom: this.minZoom,
                  // swPanBoundary: this.swPanBoundary,
                  // nePanBoundary: this.nePanBoundary,
                ),
                layers: [
                  TileLayerOptions(
                    urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    subdomains: ['a', 'b', 'c']
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

This is my code. I can change maxZoom by clicking on the button, but the map can't be enlarged. 
 The plug-in version I use is 0.5.4

**Comment by moonhx** [comment]
This is my code. I can change the value of maxZoom by clicking on the button, but the map can't be enlarged.
The plug-in version I use is `0.5.4`
```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
    LatLng swPanBoundary;
    LatLng nePanBoundary;
    MapController mapController;
    double maxZoom = 6.0;
    double minZoom = 4.0;
    initState(){
      // this.swPanBoundary = LatLng(50.5, -1.18);
      // this.nePanBoundary = LatLng(52.5, 1.06);
      mapController = MapController();
    }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('home'),
      ),
      body: Padding(
        padding: EdgeInsets.all(8.0),
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: <Widget>[
                   Text('Try tapping on the markers'),
                   RaisedButton(
                     child: Text('change zoom'),
                     onPressed: (){
                       setState(() {
                        // this.mapController.move(LatLng(52.5, 0.5), 3);
                        // this.options.swPanBoundary = LatLng(40.5, -20.18);
                        // this.options.nePanBoundary = LatLng(62.5, 10.06);
                        this.maxZoom = 18.0;
                        this.minZoom = 2.0;
                        print('change maxZoom to ${this.maxZoom}');
                       });
                     },
                   )
                ],
              ),
            ),
            Flexible(
              child: FlutterMap(
                mapController: this.mapController,
                options: MapOptions(
                  center: LatLng(51.5, -0.09),
                  zoom: 5.0,
                  maxZoom: this.maxZoom,
                  minZoom: this.minZoom,
                  // swPanBoundary: this.swPanBoundary,
                  // nePanBoundary: this.nePanBoundary,
                ),
                layers: [
                  TileLayerOptions(
                    urlTemplate: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    subdomains: ['a', 'b', 'c']
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
