### ISSUE TITLE
best way to draw on a "glasspane"?

### ISSUE THREAD

**Issue by moovida** [johnpryan/flutter_map#384]
Hi, is there a best practice to draw on top of the map in the pixel world?
For example to add simple tools like a screen center cross-hair to insert collected points or a finger measurement tool.
Or does one have to use a stack layout and do his/her own stuff?

**Comment by johnpryan** [comment]
Plugins have full access to the internal API (MapState) used by other layers like TileLayer. The plugin example is very simple but shows how you can display arbitrary widgets on top of the map. Hope that helps!

**Comment by moovida** [comment]
Ahhhh, ok. I now get it. I will see if I am able to make that work. 
That seems definitely to be the thing I am looking for. Thank you.
