### ISSUE TITLE
Version on pub does not contain all my merged PRs

### ISSUE THREAD

**Issue by escamoteur** [johnpryan/flutter_map#391]
Hi I just stumbled upon the following:

Using flutter_map 0.7.0+2 from pub has code that I already fixed:

This is from Pub:

![image](https://user-images.githubusercontent.com/16635729/63111970-40ce4800-bf8f-11e9-88d0-7af5d0dc8f8f.png)

and this is on master:

```
  set size(CustomPoint s) {
    _size = s;
    if (!_initialized) {
      _init();
      _initialized = true;
    }
    _pixelOrigin = getNewPixelOrigin(_lastCenter);
  }
```

any idea how this could happen?

**Comment by GregorySech** [comment]
The 0.7.0+2 bump is the commit before your PR getting merged. 
I guess that version was also published at the same time. 
If this is true a new version needs to be deployed to pub. 
This is the only "bug free" explanation that I can think of.

**Comment by escamoteur** [comment]
I checked it so please push a new version to pub.

**Comment by escamoteur** [comment]
Could you push a new version soon?

**Comment by johnpryan** [comment]
@escamoteur can you double check this? I think 0.7.1 was released with your changes https://pub.dev/packages/flutter_map#-changelog-tab-

**Comment by escamoteur** [comment]
Hi John, 

I checked it just now and somehow I can no longer see it.
