### ISSUE TITLE
Interactive Polygon

### ISSUE THREAD

**Issue by JonasVautherin** [johnpryan/flutter_map#394]
I would like to draw a polygon that can be edited by the user. E.g. a square, with "handles" on the corners, that can be drag-and-dropped to make it a generic quadrilateral.

I've read through PRs and issues, and I understand that it is possible to draw polygons, but I'm not sure what it implies to "edit" one.

I am new to the library, so any pointer/keyword would be welcome!

**Comment by synw** [comment]
I've made the [GeoDraw](https://github.com/synw/geodraw) package that let the user draw polygons on the map (as well as lines and markers). There is no edit but it should be easy to implement: use markers to materialize the polygon's points, move the point on tap and update the polygon. I don't know how to use drag and drop but it should be doable too.

**Comment by JonasVautherin** [comment]
That's interesting. And would that work with flutter_map? I'll see if I can try your example to see how responsive it is when moving the map. My fear is always that the polygon is not synchronized with the map :D.

**Comment by synw** [comment]
> And would that work with flutter_map?

That's built on flutter_map. Don't worry about responsiveness: polygons are fine with flutter_map: I"ve used maps with thousands of polygons and it was fluid

**Comment by JonasVautherin** [comment]
Awesome! I'll have a look at that. Closing this issue in the meantime.

Thanks a lot!
