### ISSUE TITLE
MapBox Map not being displayed  AT ALL

### ISSUE THREAD

**Issue by carloswhite** [johnpryan/flutter_map#398]
I'm in the beginning stages of trying to display a map in my recently created Flutter app. Thing is, I only get a blank screen instead of the map I created using the built-in studio tool on MapBox.com.

I've tried modifying 'Info.plist' inside my iOS folder for the project I'm working without much success.

`class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        centerTitle: true,
        title: new Text("Orlando"),
        actions: <Widget>[
          IconButton(
              icon: Icon(FontAwesomeIcons.mapMarkerAlt), onPressed: () {}),
        ],
      ),
      body: new FlutterMap(
        options: new MapOptions(
          center: new LatLng(51.5, -0.09),
          zoom: 13.0,
        ),
        layers: [
          new TileLayerOptions(
            urlTemplate:
                "mapbox://styles/carlosblancorocks/cjzk2tc9i5hqd1cpi5oz5gg5y",
            additionalOptions: {
              'accessToken':
                  'pk.eyJ1IjoiY2FybG9zYmxhbmNvcm9ja3MiLCJhIjoiY2p6azhsYmFkMDAyYTNncWlwZXo4ZWJ1cyJ9.ZD6ww-uwtXAM13ZCgRTqZw',
              'id': 'mapbox.mapbox-streets-v8',
            },
          ),
          new MarkerLayerOptions(
            markers: [
              new Marker(
                width: 80.0,
                height: 80.0,
                point: new LatLng(51.5, -0.09),
                builder: (ctx) => new Container(
                      child: IconButton(
                        icon: Icon(Icons.location_on),
                        color: Colors.red,
                        iconSize: 45.0,
                        onPressed: () {
                          print('yeahaa');
                        },
                      ),
                    ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}`

[error I get](https://i.imgur.com/35JvCUY.png)

**Comment by johnpryan** [comment]
are you sure that `mapbox://styles/carlosblancorocks/cjzk2tc9i5hqd1cpi5oz5gg5y` is the right url template to fetch the tiles from?

**Comment by carloswhite** [comment]
Good catch, John. However, changing the URLs around was one of my failed attempts to fixing the displaying issue. I have since gone back to the 'original' URL (which is: https://api.mapbox.com/styles/v1/carlosblancorocks/cjzjzc28c5eha1cmgkynbvthp/wmts?access_token=pk.eyJ1IjoiY2FybG9zYmxhbmNvcm9ja3MiLCJhIjoiY2p6anpneWgwMGZsMTNtb2FkdG5lMWJuOCJ9.m1qgEebj2nlXNHJxkk8XtA)

**Comment by carloswhite** [comment]
Hey, I'm closing the issue. Seems like MapBox has been changing their stuff around and that is what caused my app not work. Thank you for your support!
