### ISSUE TITLE
how to leaflet add wms layer ?

### ISSUE THREAD

**Issue by zozeei** [johnpryan/flutter_map#412]

**Comment by devmgs** [comment]
An example of leaflet on javascript library is avialable for your reference at http://jsfiddle.net/devmgs/t3u7xszy/14/

**Comment by nesnejretep** [comment]
I second this request, as all my available map services are either WMS or WFS services, and very rarely WMTS (tiled). This would be an invaluable addition to this plugin - and unfortunately currently a deal breaker for my application. Please plan to support WMS services. Thank you very much in advance.

**Comment by johnpryan** [comment]
@nesnejretep we accept pull requests! If you would like to try to implement this I am happy to provide guidance. It looks like you could extend the TileLayer class and make the modifications in the file linked by @devmgs

**Comment by porfirioribeiro** [comment]
There's a PR for adding that, #500 
Check it out
