### ISSUE TITLE
cant rotate map without hot reload

### ISSUE THREAD

**Issue by CalmAndCoDe** [johnpryan/flutter_map#413]
hi, how can i rotate the map without hot reload bcz i get angle from compass then i want to rotate the map when angle changes but i couldnt bcz every time i set the rotation i need to do a hot reload to update it.

Thanks in advance.

**Comment by escamoteur** [comment]
This should not be necessary. How do you change the rotation?

**Comment by CalmAndCoDe** [comment]
in the rotation argument u can set that but its not working untill u do some hot restart, i want to rotate the map as compass value get changes.

**Comment by escamoteur** [comment]
You have to use the Map Controller for that it has a rotate metheAm 16.09.2019 21:00 schrieb CalmAndCoDe <notifications@github.com>:in the rotation argument u can set that but its not working untill u do some hot restart, i want to rotate the map as compass value get changes.

**Comment by escamoteur** [comment]
@CalmAndCoDe did that work?

**Comment by CalmAndCoDe** [comment]
@escamoteur sorry for delay, yeah it solved thanks.
