### ISSUE TITLE
Wrapping FlutterMap in a GestureDetector doesn't work

### ISSUE THREAD

**Issue by barksten** [johnpryan/flutter_map#426]
Hi, I'm new to flutter so please forgive me if this is a stupid.
As I'm not able go get the gesture recogniser I tried to put flutter_map inside a GestureDetector widget to programatically set rotation on mapController from ```onScaleUpdate```.
Flutter map seems to block every callback from GestureDetector, even this doesn't work:
```
GestureDetector(
  onTap: () => print('Tap!'),
  child: FlutterMap(
    mapController: mapController,
    options: new MapOptions(
        ...
     ),
    layers: [
      new TileLayerOptions(
          ...
      ),
    ],
  ),
),
```
What's going on? Isn't this the way it's supposed to work?

**Comment by barksten** [comment]
Today I tried another approach to implement rotation in ```MapGestureMixin``` and ```MapState``` in my fork without luck. I can't quite figure out the choice of state management in this code.
I tried to add rotation information (MapState already have a field called rotation) to the ```void move(LatLng center, double zoom, {hasGesture = false})``` function of ```MapState``` but I can't get it to render.

**Comment by agersea** [comment]
I believe the FlutterMap.options property has what you want.

For example:
`
...your code
void mapOnTap(LatLng arg) {
    //do something with the coords
}

<your widget tree>...
child: FlutterMap(
    options: MapOptions(
        center: LatLng(_latitude, _longitude),
        onTap: (LatLng arg) => mapOnTap(arg),
        zoom: 15.0,
    ),
    layers: [...],
)`

**Comment by johnpryan** [comment]
It looks like @agersea's answer is correct
