### ISSUE TITLE
Get lag when zoom in map

### ISSUE THREAD

**Issue by maituongan11zz** [johnpryan/flutter_map#429]
I have 2 titlemap: 1. base map, 2. wms from my geoserver. I feel my app load too slow when zoom in map. How can i  increase performances my app? Thanks you

**Comment by maituongan11zz** [comment]
Is this problem fixed? I still get grey screen when zoom in. How can i fix this? Thanks you

**Comment by joelmoreiradev** [comment]
![photo_2020-03-02_22-12-55](https://user-images.githubusercontent.com/51009134/75733075-0b8f0a80-5cd3-11ea-953b-087edbf9575a.jpg)

I'm having the same problem, every time I zoom the map it 'blinks' in gray, and when I move the map there are many gray squares that remain for 1 second, and it's not a network problem.

**Comment by ibrierley** [comment]
I've got a pull request based on this branch... https://github.com/ibrierley/flutter_map/tree/improve_tiles_display  it would be interesting if you could test it, to see if it helps.

**Comment by maituongan11zz** [comment]
> I've got a pull request based on this branch... https://github.com/ibrierley/flutter_map/tree/improve_tiles_display it would be interesting if you could test it, to see if it helps.

Can you show me how to use your branch please? Many thanks.

**Comment by ibrierley** [comment]
You could clone it from git and switch branches...it would be 'something like'...

git clone -b improve_tiles_display https://github.com/ibrierley/flutter_map.git

And then change your pubspec.yaml to point flutter_map to the new location....

flutter_map:
    path: my_github_location

or it maybe better to get your pubspec.yaml to point to a specific git branch...comment out the old flutter_map part and put something like...

flutter_map:
    git:
         url: git://github.com/ibrierley/flutter_map.git
         ref: improve_tiles_display

Then swap back when finished testing.

Or, a bit hacky, but there are just 2 files changed. Find whereever the originals are copy/backup and replace with

https://github.com/ibrierley/flutter_map/blob/improve_tiles_display/lib/src/layer/tile_layer.dart
https://github.com/ibrierley/flutter_map/blob/improve_tiles_display/lib/src/map/map.dart

I don't recommend this way as it messes with the originals, but it can be a quick hack.
