### ISSUE TITLE
Center with offset or pan?

### ISSUE THREAD

**Issue by HugoHeneault** [johnpryan/flutter_map#433]
I would like to center my map with 200px offset at the top of it. How could I achieve that?

**Comment by RomanJos** [comment]
I want to do that too

**Comment by HugoHeneault** [comment]
I just found out it already exists!

Use `FitBoundsOptions` 🍻 

```dart
mapController.fitBounds(bounds,
        options: FitBoundsOptions(
            padding: EdgeInsets.only(
                bottom: 150.0, top: 50)));
```

**Comment by RomanJos** [comment]
fitBounds work well but when I'm adding animation with tween from map.center.latitude to the new latitude it don't take the 200px padding (map.center don't take the 200px padding)
