### ISSUE TITLE
possible to use in flutter web?

### ISSUE THREAD

**Issue by SebWojd** [johnpryan/flutter_map#440]
Hi guys, 
I try to use this framework to build with web. Unfortunately I received only blank screen in the place that map should be displayed.
On iOS/Android with the same code works fine.

Any hints?

**Comment by johnpryan** [comment]
Thanks for filing an issue! This looks like an issue with the flutter_image package. You can define your own TileProvider that uses NetworkImage to work around the issue:

```
class NonCachingNetworkTileProvider extends TileProvider {
  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return NetworkImage(getTileUrl(coords, options));
  }
}
```

Added e8e687b75e6287ff5faddd9331724f1915a00a27 to demonstate.

**Comment by johnpryan** [comment]
I've filed an issue here: https://github.com/flutter/flutter/issues/42375

**Comment by moovida** [comment]
Hi @johnpryan , web support would be more than awesome.

I tried to run with the above tileprovider and just show the osm map, but I am getting exceptions:

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following Event$ object was thrown resolving an image frame:
[object Event]

When the exception was thrown, this was the stack:
package:build_web_compilers/src/dev_compiler/dart_sdk.js 4000:38   createErrorWithStack
package:build_web_compilers/src/dev_compiler/dart_sdk.js 42332:44  onError
package:build_web_compilers/src/dev_compiler/dart_sdk.js 42589:56  _rootRunBinary
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41901:14  runBinary
package:build_web_compilers/src/dev_compiler/dart_sdk.js 37938:52  handleError
package:build_web_compilers/src/dev_compiler/dart_sdk.js 38443:51  handleError
package:build_web_compilers/src/dev_compiler/dart_sdk.js 38466:17  _propagateToListeners
package:build_web_compilers/src/dev_compiler/dart_sdk.js 38330:23  [_completeError]
package:build_web_compilers/src/dev_compiler/dart_sdk.js 38362:31  <fn>
package:build_web_compilers/src/dev_compiler/dart_sdk.js 42574:14  _rootRun
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41887:14  run
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41804:14  runGuarded
package:build_web_compilers/src/dev_compiler/dart_sdk.js 41843:33  callback
package:build_web_compilers/src/dev_compiler/dart_sdk.js 42426:13  _microtaskLoop
package:build_web_compilers/src/dev_compiler/dart_sdk.js 42432:13  _startMicrotaskLoop
package:build_web_compilers/src/dev_compiler/dart_sdk.js 38666:9   <fn>

Image provider: NetworkImage("https://a.tile.openstreetmap.org/13/4346/2914.png", scale: 1)
Image key: NetworkImage("https://a.tile.openstreetmap.org/13/4346/2914.png", scale: 1)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: [object Event]
Another exception was thrown: [object Event]
Another exception was thrown: [object Event]
Another exception was thrown: [object Event]
Another exception was thrown: [object Event]
Another exception was thrown: [object Event]
Another exception was thrown: [object Event]
...
```

Should the example work already for the web?

**Comment by moovida** [comment]
That is super cool! 

I tried it and interestingly it didn't work in the chrome instance launched with: flutter web -d chrome
Took me a while to figure what was wrong.

**Comment by SebWojd** [comment]
@johnpryan  thank you for your quick respond and help! I really appreciate it! 
Problem seems to be solved.

**Comment by moovida** [comment]
@SebWojd, do you have an idea on how to keep a cache? The proposed solution works but reloads same tiles.

**Comment by moovida** [comment]
I am testing the web part further. I hope it is ok to signal in this discussions test results, maybe @SebWojd can confirm if he/she also sees them.

I tried to add polylines on top of an OSM layer (same as I do in android/ios). The result is the background map disappearing:

![image](https://user-images.githubusercontent.com/390250/66702246-c65b4380-ed05-11e9-9e24-55aa2b782847.png)

If I drag to pan, the background map is seen flickering, but once I stop, the background disappears.

**Comment by SebWojd** [comment]
@moovida as for cache - I didn't figure it out yet. I've just started development for web so in few days I will get the results.

@johnpryan as you can see, there is the concern here about web - maybe you will take a look for this part of your framework in next releases?

**Comment by moovida** [comment]
@SebWojd, I have in my test-todo list to have a look if **html.window.indexedDB** can be used to keep tiles in cache. I would appreciate comments about this, if you have knowledge, since i will have to check it out from scratch.

**Comment by moovida** [comment]
I just finished another round of testing. The Markers part work pretty well also together with the clustering plugin.

![image](https://user-images.githubusercontent.com/390250/66719059-34c60180-edeb-11e9-9eb1-09ddc2f7c390.png)

There has been some flickering sometimes on panning, but I wasn't able to catch any error.

I have to say that being able to add widgets to the markers and add plugins to the library has a huge potential also for the web part. Thanks @johnpryan ! :-)

**Comment by johnpryan** [comment]
@ibosev Right now you would have to make a plugin that places buttons on the screen to move the map using the map controller. 

The long-term solution for zooming is to handle scroll gestures, but this is not part of the framework yet https://github.com/flutter/flutter/issues/23604

**Comment by moovida** [comment]
@johnpryan do you have any idea what could handle the background disappearing when adding lines? Also I experienced this today testing with markers on a secondary high resolution screen. But still no error and I am not able to understand what is getting crazy.

**Comment by ibosev** [comment]
> @ibosev Right now you would have to make a plugin that places buttons on the screen to move the map using the map controller.
> 
> The long-term solution for zooming is to handle scroll gestures, but this is not part of the framework yet [flutter/flutter#23604](https://github.com/flutter/flutter/issues/23604)

I made a workaround without adding buttons to the screen. One just have to wrap the map in Listener widget and check for onPointerSignal like so:
```
Listener(
        onPointerSignal: handleSignal,
        .....
)

======


void handleSignal(e) {
    if (e is PointerScrollEvent) {
      var delta = e.scrollDelta.direction;
      mapController.move(mapController.center, mapController.zoom + (delta > 0 ? -0.2 : 0.2));
    }
  }
```

**Comment by johnpryan** [comment]
This issue is tracked by #383 so I'm going to close this one
