### ISSUE TITLE
Flutter_map does not show if zoom is 20 or more

### ISSUE THREAD

**Issue by HamdyAli** [johnpryan/flutter_map#441]
If the zoom under MapOptions is set to 20, the map will not display and the debugger will say 'Couldn't download or retrieve file' Issue also occurs if the user zooms in to certain point.

<img width="420" alt="Screen Shot 2019-10-10 at 3 46 40 PM" src="https://user-images.githubusercontent.com/36948393/66549170-4ef6aa00-eb75-11e9-8664-68ab31c57a46.png">

**Comment by moovida** [comment]
What online datasource are you using? I am quite confident that for example Openstreetmap will block you from getting tiles at that zoomlevel. My guess is that it is not a problem of the library.

**Comment by HamdyAli** [comment]
Yes I think that was the issue

**Comment by Rashesh-Bosamiya** [comment]
I am facing the same issue.

Have you found any resolution?
