### ISSUE TITLE
Flutter v1.10.15-pre throws exception

### ISSUE THREAD

**Issue by bruce6135** [johnpryan/flutter_map#451]
Compiler message:
../../.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-1.1.2+1/lib/src/cached_network_image_provider.dart:53:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../Documents/github/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);

**Comment by valdio** [comment]
Any update on this issue? I am facing the same problem

**Comment by dimitristaufer** [comment]
As a temporary fix, use the command `flutter version v1.10.14` to revert back to version 1.10.14.
Everything works just fine there.
