### ISSUE TITLE
Map not showing on release apk, only on debug.

### ISSUE THREAD

**Issue by reidterror** [johnpryan/flutter_map#456]
My flutter map, i've taken out my api key. I've tried with mapbox and thunderforest. Both have the same effect.

```dart
body: FlutterMap(
                    options: MapOptions(
                        center: LatLng(57.1498817, -2.1950666),
                        zoom: 10.0,
                    ),
                    layers: [
                        new TileLayerOptions(
                            urlTemplate: "https://tile.thunderforest.com/neighbourhood/{z}/{x}/{y}.png?apikey=<apikey>",
                        ),
                        MarkerLayerOptions(
                            markers: getLocationsMarkers(),
                        ),
                    ],
                ),
```

**Comment by reidterror** [comment]
I've solved my issue by moving to google_maps_flutter. There's a markers example in the examples folder.

**Comment by benjamindean** [comment]
The same issue, actually.

**Comment by benjamindean** [comment]
To @reidterror and anyone who experiences the same issue: You have to add `<uses-permission android:name="android.permission.INTERNET"/>` permission to the root of your `AndroidManifest.xml` to fix it. Not sure why it happens, since it's needed for debugging only, but it fixed it for me.
