### ISSUE TITLE
Too slow for practical use?

### ISSUE THREAD

**Issue by LarsBocons** [johnpryan/flutter_map#457]
Hi
I'm doing a research to see if we can move from a Cordova based app to Flutter. First thing I tried is this Leaflet map plugin (used the example under "Markers" here https://tphangout.com/flutter-maps-and-markers/).
I'm kind of hoping I'm missing something, because running that on my Huawei P20 Lite is simple too slow to be of any practical use. On that very same phone, our Leaflet map in our Cordova app is just flying.

Am I the only one having performance problems with this plugin?

**Comment by ibrierley** [comment]
Have you made sure you're not running it in debug/log mode, and running in release mode (I think that's what it's called, but can't check atm) ? That makes a huge difference.

**Comment by LarsBocons** [comment]
I tried it in release mode and while it was faster, there were still huge issues with missing/dissappearing tiles when moving/zooming map.

Does anyone have a full main.dart example with Openstreetmap that works?

**Comment by deisold** [comment]
I have the same issue, sometimes its faster sometimes slower which points more to be a performance issue of the server than of the map implementation itself. 
Switching to Google maps isn't an alternative either since markers have to be PNGs. No widgets are allowed which makes it more complicate if you want to use dynamic content.

If anyone has a solution to the performance problem please let us know!

**Comment by ibrierley** [comment]
If you think it's a server side issue, i.e the map provider, you could host a tile cache yourself (if the tileprovider allows this, openstreetmaps encourage it iirc to reduce the load on their servers).

I.e you create a simple php or similar host somewhere, your app calls that host, if it has that file, it provides it, if not, it grabs the map from the server, stores it, and provides it. 

That may depend on the use case, but typically you don't need a masssive tilestore, as most tiles are around cities etc and reused.

**Comment by deisold** [comment]
I just tried it with mapbox.com as tile server and its already much faster ;-)

**Comment by vmwsree** [comment]
> If you think it's a server side issue, i.e the map provider, you could host a tile cache yourself (if the tileprovider allows this, openstreetmaps encourage it iirc to reduce the load on their servers).
> 
> I.e you create a simple php or similar host somewhere, your app calls that host, if it has that file, it provides it, if not, it grabs the map from the server, stores it, and provides it.
> 
> That may depend on the use case, but typically you don't need a masssive tilestore, as most tiles are around cities etc and reused.

can you provide some example code.

**Comment by ibrierley** [comment]
https://wiki.openstreetmap.org/wiki/ProxySimplePHP

**Comment by ibrierley** [comment]
If you get stuck with that shout, I can provide my own one if you need.
