### ISSUE TITLE
Markers flash when move map around

### ISSUE THREAD

**Issue by thuydao** [johnpryan/flutter_map#470]
I used `WidgetBuilder` to render marker.

**Comment by daskinnyman** [comment]
Hi @thuydao, I've issued the same problem, have you solved this issue,  can you share your solution with me, thank you.

**Comment by bruckmatthew** [comment]
Was getting this issue as well. 
I'm developing on Web with the NonCachingNetworkTileProvider() workaround passed into the tileProvider. I was using the Flutter image into Marker->builder->container->child as per readme example. 
My workaround: When I passed my own asset image in to the same location it seems to be working fine. Perhaps there is some conflict between NetworkImages and the provider?

**Comment by thuydao** [comment]
> Hi @thuydao, I've issued the same problem, have you solved this issue, can you share your solution with me, thank you.

FutureBuilder always call Future fuction when you move map arround. So, you need to cache the fuction in a var, then set it to FutureBuilder.

**Comment by srburton** [comment]
@thuydao , @bruckmatthew @daskinnyman

Did you manage to fix it? could post a solution?

**Comment by srburton** [comment]
My solution:


Add `UniqueKey ` in Widget. 

```

Marker(
     width: 40,
     height: 40,
     point: LatLng(lat, lon),
     builder: (_) => Container(
        key: UniqueKey(),
       child: ...
     )
 )
```
