### ISSUE TITLE
Because flutter_map 0.7.3 depends on flutter_image ^2.0.0

### ISSUE THREAD

**Issue by williamborba** [johnpryan/flutter_map#476]
Because flutter_map 0.7.3 depends on flutter_image ^2.0.0 and app depends on flutter_image 3.0.0, flutter_map 0.7.3 is forbidden.

So, because app depends on flutter_map 0.7.3, version solving failed.
pub get failed (1; So, because app depends on flutter_map 0.7.3, version solving failed.)

https://pub.dev/packages/flutter_image#-changelog-tab-

**Comment by johnpryan** [comment]
`0.8.0` has been published and now specifies flutter_image `^3.0.0` - thanks for filing an issue!
