### ISSUE TITLE
Polygons with outer and inner bounds

### ISSUE THREAD

**Issue by Tobisaninfo** [johnpryan/flutter_map#484]
Hi,

I try to use your plugin to display countries as a polygon overlay on open street maps. The problem is, that some countries are not a polygon in the normal way, because they enclose another country. So for that purpose, I have to use a polygone for the outer boundary and a second polygon for the inner boundary.

Is there an option to do so using the polygon class? Or is there any other way to realize this kind of overlay?

Best regards
Tobias

**Comment by moovida** [comment]
That is an interesting one which I also will soon have to look into. From the code I have the feeling that polygons with holes are not supported. 

I wonder if that is the way to do it in flutter? https://stackoverflow.com/questions/56923884/cutting-a-hole-in-a-shape-with-flutter-canvas

**Comment by Tobisaninfo** [comment]
I'm not quite sure, but the code snippet from the stackoverflow post seems to be useful. But I can't tell you, if this is the best way to do it.

**Comment by maRci002** [comment]
@Tobisaninfo could you please take a test ride with #526 PR?

**Comment by bettdouglas** [comment]
@maRci002 does this mean support for multipolygons? Could you also add an example?

**Comment by maRci002** [comment]
@bettdouglas sorry for late response I made an example in PR, see [this comment](https://github.com/johnpryan/flutter_map/pull/526#issuecomment-610284083).
