### ISSUE TITLE
Does this package support gradient lines for polygons

### ISSUE THREAD

**Issue by abhijithvijayan** [johnpryan/flutter_map#486]
I was thinking of this between 3 points **A, B & C**

From *A(Red) to B(green) to C(blue)*

![Screenshot from 2019-12-17 22-21-07](https://user-images.githubusercontent.com/34790378/71016748-9d976600-211b-11ea-8462-bbdcc1a879e6.png)
![Screenshot from 2019-12-17 22-23-58](https://user-images.githubusercontent.com/34790378/71017035-ff57d000-211b-11ea-961c-d5826ecab982.png)

Basically, there will be a source and destination. And multiple points might be in between them having different unit values for a specific quantity(say rainfall of yesterday)

Is it possible to show the gradient lines in between the points as a single polygon with appropriate color.

Or is it only possible to draw multiple lines from point to point with different color?

@johnpryan

**Comment by abhijithvijayan** [comment]
I was thinking of this between 2 points **A(at 1) & B(at 19)**

![Screenshot from 2019-12-17 22-11-57](https://user-images.githubusercontent.com/34790378/71015986-7db37280-211a-11ea-8b93-bd7cdbc7709d.png)

**Comment by abhijithvijayan** [comment]
It's that I have seen it in React Native (https://github.com/react-native-community/react-native-maps/pull/1911)

**Comment by abhijithvijayan** [comment]
@johnpryan Will this be a feature to be added or does it exist already?

**Comment by johnpryan** [comment]
I think this is related to https://github.com/johnpryan/flutter_map/pull/452

**Comment by abhijithvijayan** [comment]
#452 will be merged right?
