### ISSUE TITLE
map doesn't load 

### ISSUE THREAD

**Issue by feyzagezerer** [johnpryan/flutter_map#488]
Hello, the map doesn't show up because of these problems. Can you please help me?
Exception: Could not instantiate image codec.
Exception caught by image resource service: Couldn't download or retrieve file.

**Comment by lustigo** [comment]
which UrlTemplate did you enter?

**Comment by feyzagezerer** [comment]
> 
> 
> which UrlTemplate did you enter?

this one: https://api.mapbox.com/styles/v1/hyfy/ck3ydi5e6fpeh1coauo0hhir2/wmts?access_token=pk.eyJ1IjoiaHlmeSIsImEiOiJjazNtMG0yN2wxNm12M2RsY3lmeTFkMXVkIn0.Cg-21oEIgq1C1ksC229DmA

**Comment by feyzagezerer** [comment]
I solved the problem. The UrlTemplate I entered was incorrect. Thanks to lustigo for the comment that made me concentrate here.
