### ISSUE TITLE
Drag is not fluid enough

### ISSUE THREAD

**Issue by virshlee** [johnpryan/flutter_map#492]
I compared flutter_map to the normal google maps. Don't get me wrong, flutter_map's drag works fine, but it's as not smooth as the one in google maps. Do you have any idea what's the difference?

**Comment by kleeb** [comment]
Google Maps SDK has prebuilt vectorisation. Thats why this zooming in/out feels so smooth when in the meantime its downloading all relevant tiles. Not sure what would need to be done to make the UX better, maybe some rasterisation of the tiles before we get a new one from the network.

**Comment by johnpryan** [comment]
also related to flinging behavior: https://github.com/johnpryan/flutter_map/issues/271

**Comment by virshlee** [comment]
> I compared flutter_map to the normal google maps. Don't get me wrong, flutter_map's drag works fine, but it's as not smooth as the one in google maps. Do you have any idea what's the difference?

but I see it even when all the needed tiles are loaded

**Comment by johnpryan** [comment]
Right now what we have is a rough attempt to allow for two-finger dragging and zooming. Pull requests are accepted :)

**Comment by virshlee** [comment]
I will take a look at it, 

> Right now what we have is a rough attempt to allow for two-finger dragging and zooming. Pull requests are accepted :)

I will take a look at it, also it is possible that it would be better if I could run it in 60fps, I can't go above about 40 fps even in performance mode.

**Comment by virshlee** [comment]
> Right now what we have is a rough attempt to allow for two-finger dragging and zooming. Pull requests are accepted :)

Do you think the whole plugin could be made more fluid by multi threading some back-end work? Ex the gesture could be calculated on a different thread or isolate as it's called in flutter I think.

**Comment by MihaMarkic** [comment]
I _feel_ that putting gesture calculation in isolate would yield worse performance. Or is that calculation that much demanding? Perhaps some perf measurement could help.

**Comment by maRci002** [comment]
Hi, @virshlee could please take a test ride with #572 PR, maybe it resolves this issue.
