### ISSUE TITLE
Update cached_network_image

### ISSUE THREAD

**Issue by pro100svitlo** [johnpryan/flutter_map#493]
Right now there is new version available for `cached_network_image` - **2.0.0-rc**
It would be nice to update it in `flutter_map`, cos there are some braking changes, introdused by flutter team : `The Flutter team made a breaking change with the ImageProvider in Flutter 1.10.15`.
More details can be found here: https://github.com/renefloor/flutter_cached_network_image/issues/270

**Comment by AzarouAmine** [comment]
Any news on this?

**Comment by johnpryan** [comment]
pull requests accepted :)

**Comment by pro100svitlo** [comment]
thanks ;-)
