### ISSUE TITLE
[HELP] How to find the route between two point?

### ISSUE THREAD

**Issue by mattia-lau** [johnpryan/flutter_map#507]
[HELP] How to draw the route between two point?

**Comment by johnpryan** [comment]
This package only displays map tiles, you'll have to use an API for that.

**Comment by nishontan** [comment]
@mattia-lau 

I have hosted https://github.com/graphhopper/graphhopper#dockerr 
and requested routes via an API and drew the latitude and longitude as
polylines on flutter_map.


You can definitely find your own route API, https://docs.mapbox.com/api/navigation/#directions
and https://developers.google.com/maps/documentation/directions/intro are two popular options
