### ISSUE TITLE
Markers suggestion ...

### ISSUE THREAD

**Issue by almodoen** [johnpryan/flutter_map#509]
peace be on all of you ..

as i see you accept the marker to be a widget .. not just image or icon , and this is very good thing ..

so please make it accept the onpressed function in an IconButton() .. to give us the ability to show info window (or dialog) that contains some information about the selected place (like google maps markers) 

i hope you understand , thanks.

**Comment by X-SLAYER** [comment]
> peace be on all of you ..
> 
> as i see you accept the marker to be a widget .. not just image or icon , and this is very good thing ..
> 
> so please make it accept the onpressed function in an IconButton() .. to give us the ability to show info window (or dialog) that contains some information about the selected place (like google maps markers)
> 
> i hope you understand , thanks.

could use InkWell , IconButton or some other widget with an onTap method. 
check here  : h[ttps://github.com/johnpryan/flutter_map/pull/103](url)

**Comment by johnpryan** [comment]
Yes, as @X-SLAYER pointed out, there is an onTap sample here: https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/on_tap.dart
