### ISSUE TITLE
Fixed Scale for Markers (feature)

### ISSUE THREAD

**Issue by alfanhui** [johnpryan/flutter_map#52]
Hey, 

Would be great to see a **fixed scale** for markers, to cover a consistent area between zooms. 

I did try to implement a solution in the [marker_layer.dart](https://github.com/apptreesoftware/flutter_map/blob/master/flutter_map/lib/src/layer/marker_layer.dart), togglable by a new variable fixedScale, but unable to adjust size bigger than 100x100. 

**Ideas:**
`map.getZoomScale(map.zoom, map.zoom)` always returns 1.0 given the duplicated arguments, so currently its not doing anything in current code. I think it was placed here for this particular feature in the future. I believe the starting zoom should populate the second argument to maintain the starting size of the widget(image). 

**Current Implementation:**
My current implementation looks something like this (considering my starting zoom is 17.0).
[Screen capture on youtube](https://youtu.be/Y6dYTpc55xo)
Trouble I found is that the marker Width and Height have to be within 0-100 to work. My marker's widget is a AssetImage in a container. 

```
Widget build(BuildContext context) {
[...]
          var width = markerOpt.width;
          var height = markerOpt.height;

          var pixelPosX =
              (pos.x - (markerOpt.width - markerOpt._anchor.left)).toDouble();
          var pixelPosY =
              (pos.y - (markerOpt.height - markerOpt._anchor.top)).toDouble();

          if (markerOpt.fixScale) {
            width = markerOpt.width * map.getZoomScale(map.zoom, 17.0);
            height = markerOpt.height * map.getZoomScale(map.zoom, 17.0);

            pixelPosX = (pos.x -
                    (width -
                        (markerOpt._anchor.left *
                            map.getZoomScale(map.zoom, 17.0))))
                .toDouble();
            pixelPosY = (pos.y -
                    (height -
                        (markerOpt._anchor.top *
                            map.getZoomScale(map.zoom, 17.0))))
                .toDouble();
          }

          if (!latlngBounds.contains(markerOpt.point)) {
            continue;
          }

          markers.add(
            new Positioned(
              width: width,
              height: height,
              left: pixelPosX,
              top: pixelPosY,
              child: markerOpt.builder(context),
            ),
          );
        }
[...]
```

Got any ideas on how to increase the size?

**Comment by avioli** [comment]
Do you mean fixed scale as in scale the markers up/down while the map scales? To me fixed scale means to keep them at a fixed scale, which is already the case.

Polygons scale with the map. You can look at them for ideas. They just use a painter, but the scaling logic is there.

Anyway the plugin system is there for this reason - make a plugin and @johnpryan could integrate it at some point into the core. This way the plugin system will get some love too. :)

**Comment by johnpryan** [comment]
as @avioli mentioned, It looks like you have a solution that can be implemented using the plugin api. I'm going to close but feel free to reopen if you feel that doesn't fit your needs.
