### ISSUE TITLE
Not working in release?

### ISSUE THREAD

**Issue by Emrage** [johnpryan/flutter_map#530]
The map works when I launch it in emulator but it doesn't work on my phone on android 10.0.

```
FlutterMap(
                  mapController: widget.mapController,
                  key: _mapButton,
                  options: MapOptions(
                    minZoom: 3,
                    maxZoom: 17,
                    nePanBoundary: LatLng(80.0, 154.0),
                    swPanBoundary: LatLng(-80.0, -154.0),
                    center: LatLng(
                        double.parse(
                            widget.prefs.get("home").toString().split(" ")[0]),
                        double.parse(
                            widget.prefs.get("home").toString().split(" ")[1])),
                    zoom: widget.prefs.get("zoom"),
                    onLongPress: (LatLng latLng) => _handleTap(latLng, context),
                    onPositionChanged: (MapPosition pos, bool gesture) => _handleChangePos(pos, gesture),
                  ),
                  layers: [
                    TileLayerOptions(
                      tileProvider: NonCachingNetworkTileProvider(),
                      urlTemplate: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
                    ),
                    MarkerLayerOptions(
                      markers: widget.markerStore.markers.toList(),
                    ),
                  ],
                ),
```
```
class NonCachingNetworkTileProvider extends TileProvider {
  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return NetworkImage(getTileUrl(coords, options));
  }
}
```

I added the tile provider for it to work with web but it made no difference for the release version.

**Comment by ian-workcircle** [comment]
Double check that you may have a separate AndroidManifest.xml file, it may have internet disabled or missing in it. I had this, the one in the dev folder was fine.

It's probably in android->app->src   and then you may find there's different files in debug/main/profile. Compare the main, to the debug one.

**Comment by ibrierley** [comment]
Double check that you may have a separate AndroidManifest.xml file, it may have internet disabled or missing in it. I had this, the one in the dev folder was fine.

It's probably in android->app->src and then you may find there's different files in debug/main/profile. Compare the main, to the debug one.

**Comment by Emrage** [comment]
> 
> 
> Double check that you may have a separate AndroidManifest.xml file, it may have internet disabled or missing in it. I had this, the one in the dev folder was fine.
> 
> It's probably in android->app->src and then you may find there's different files in debug/main/profile. Compare the main, to the debug one.

You're right there are 2 AndroidManifest.xml thank you.

![image](https://user-images.githubusercontent.com/8495685/75560404-5f84bf80-5a45-11ea-911b-1ccee89d493f.png)

In the debug AndroidManifest.xml the permission is already there

![image](https://user-images.githubusercontent.com/8495685/75560447-72978f80-5a45-11ea-95d3-e594f3dbbc02.png)

For future people to fix this go to the AndroidManifest.xml in the main folder and add the permission.

![image](https://user-images.githubusercontent.com/8495685/75560487-89d67d00-5a45-11ea-84bb-2f77a7861827.png)
