### ISSUE TITLE
Animated Markers

### ISSUE THREAD

**Issue by Emrage** [johnpryan/flutter_map#532]
Is it possible to have markers with animation? For example a fade animation when adding a marker.

**Comment by porfirioribeiro** [comment]
Markers are just widgets, so just put any animated widget as a Marker

**Comment by johnpryan** [comment]
Yep, @porfirioribeiro's answer is correct

**Comment by aytunch** [comment]
fading in the widget is straight forward however when we removed the marker from the markers array, how can we fade it out? 
I believe at that moment the widget is disposed so the fade out animation will not be seen.

**Comment by loveoverflowdev** [comment]
> Markers are just widgets, so just put any animated widget as a Marker

How do you handle that animation if dragging map ?
