### ISSUE TITLE
should we migrate to work with AndroidX to be future proof ?

### ISSUE THREAD

**Issue by winwisely99** [johnpryan/flutter_map#533]
```
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can
    quickly migrate your app by following the
    steps on https://goo.gl/CP92wY
````
See:
https://flutter.dev/docs/development/androidx-migration

Is https://github.com/johnpryan/flutter_map/issues/257 still valid ?

**Comment by porfirioribeiro** [comment]
Are you talking about the example?
I migrated it to androifX on this PR #504 

The library code itself is pure Dart and don't use any AndroidX
