### ISSUE TITLE
Map doesn't get drawn on user location at screen start.

### ISSUE THREAD

**Issue by vinnytwice** [johnpryan/flutter_map#534]
UPDATE:

After discovering that that `FlutterMap` must be in a stateful widget I changed mine. On incoming state I performed a check on the State type and in side that called setState() with the new value from state. Error.. A builder that rebuilds building widget kind of error if I recall the error correctly. .. BlocBuilder wasn't the right choice anymore so I swapped it for a BlocListener instead that has a callback on States, and called setState() in there. FlutterMap gets now drawn on userLocation on buttonPressed even after Hot-reload or Hot-restart..and no more The method 'move' was called on null. errors.. so that one is solved.

Still FlutterMap doesn't get drawn on userLocation at screen load. Can you see what I'm missing? Some initial coordinates perhaps? Anyways.. shouldn't setState() keep track of where userLocation is used and rebuild those widgets ?

If I call _mapController.move(userLocation, 16);right after setState() than the map will follow the user location, useful in a step-by-step navigator, but is not what I need..also if you pan it as soon as a new state comes in, the map moves..

So the new code is:

```
// stateful widget using BlocListener:

class MapScreen extends StatefulWidget {
  final String name;
  final MapRepository _mapRepository;
//  MapController _mapController;
//  final AlertRepository _alertRepository;

  MapScreen(
      {Key key, @required this.name, @required MapRepository mapRepository})
      : assert(mapRepository != null),
        _mapRepository = mapRepository,
//        _mapController = MapController(),
//        _alertRepository = alertRepository,
        super(key: key);

  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  List<Marker> alerts;

  LatLng userLocation;

  MapController _mapController = MapController();

  @override
  Widget build(BuildContext context) {
    return BlocListener<MapBloc, MapState>(
//        bloc: MapBloc(mapRepository: _mapRepository),
      listener: (BuildContext context, MapState state) {
//      userLocation = (state as LocationStream).location;
        if (state is LocationStream) {
          setState(() {
            userLocation = (state).location;
          });
        }
      },
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0,
          title: Text(
            'Home',
            style: TextStyle(color: Colors.orangeAccent, fontSize: 40),
          ),
          actions: <Widget>[
            IconButton(
              icon: Icon(
                Icons.exit_to_app,
                color: Colors.orange,
                size: 35,
              ),
              onPressed: () {
//              BlocProvider.of<AuthenticationBloc>(context).add(
//                LoggedOut(),
//              );
              },
            ),
          ],
        ),
        backgroundColor: Colors.white,
        body: SafeArea(
          minimum: EdgeInsets.symmetric(horizontal: 20),
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Container(
                  height: 570,
                  width: 320,
                  child: FlutterMap(
                    options: MapOptions(
                      center: userLocation,
                      minZoom: 5.0,
                      maxZoom: 19.0,
                    ),
                    mapController: _mapController,
                    layers: [
                      //
//        PolygonLayer(polygonOpts, map, stream)
//                    PolygonLayerOptions(
//                      polygons:
//                    ),
                      TileLayerOptions(
                          urlTemplate:
                              'https://api.openrouteservice.org/mapsurfer/{z}/{x}/{y}.png?api_key=5b3ce3597851110001cf62484c4b65d85bc844eca3a2c6b9f300ddf4',
//                              urlTemplate:
//                                  'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                          subdomains: ['a', 'b', 'c'],
                          keepBuffer: 20),
                      new MarkerLayerOptions(
                        markers: [
                          Marker(
                            point: userLocation,
                            height: 200,
                            width: 200,
                            builder: (context) => IconButton(
                              icon: Icon(Icons.location_on),
                              color: Colors.red,
                              iconSize: 60,
                              onPressed: () {
                                print('icon tapped');
                              },
                            ),
                          ),
//                          Marker(
//                            height: ,
//                            builder: BlocBuilder<AlertBloc,AlertState>(
//                                builder: (BuildContext context, AlertState state) {
//                                  alerts = (state as AlertsUpdated).alerts;
//                                  return
//                                }),
//                          )
                        ],
                      ),
                    ],
                  ),
                ),
                SizedBox(
                  height: 10,
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    RaisedButton(
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(5)),
                      onPressed: () {
                        print(
                            ' @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   userLocation is $userLocation');
                        _mapController.move(userLocation, 16);
                      },
                      color: Colors.red,
                      child: Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Text(
                          'center',
                          style: TextStyle(color: Colors.white, fontSize: 30),
                        ),
                      ),
                    ),
                    RaisedButton(
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(5)),
                      onPressed: () {
                        //TODO  this goes actually in a alert icon callbac, here just navigates icons vc
                      },
                      color: Colors.red,
                      child: Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Text(
                          'alert',
                          style: TextStyle(color: Colors.white, fontSize: 30),
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
} 
```

I'm still very new to Flutter/Dart and I'm using the flutter_bloc bloc/repository pattern and I'm getting a strange behaviour in my app.
All prints show that all streams and bloc pattern are working correctly, incoming states are carrying the coordinates and the variable that hold the newest coordinates is never null, but when MapScreen loads, it doesn't draw the map on userLocation coordinates.
Also, when pressing center button sometimes I get `The method 'move' was called on null.` error.

In MapScreen `userLocation` that gets its value from incoming state  

    return BlocBuilder<MapBloc, MapState>(
    //        bloc: MapBloc(mapRepository: _mapRepository),
            builder: (BuildContext context, MapState state) {
          userLocation = (state as LocationStream).location;
    //      if (state is LocationStream) {
    //        userLocation = (state).location;
    //      }
          return Scaffold( 

 is then used to draw the map at user location 

    child: FlutterMap(
                        options: MapOptions(
                          center: userLocation,
                          minZoom: 5.0,
                          maxZoom: 19.0,
                        ),
                        mapController: _mapController,

 to display user on the map 

     

    Marker(
           point: userLocation,
           height: 200,
           width: 200,
           builder: (context) => IconButton(
               icon: Icon(Icons.location_on),
               color: Colors.red,
               iconSize: 60,
               onPressed: () {
                print('icon tapped');
               },
           ),
         ),

 and to re center the map on user location .

    RaisedButton(
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(5)),
                          onPressed: () {
                            print(
                                ' @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   userLocation is $userLocation');
                            _mapController.move(userLocation, 16);
                          },
                          color: Colors.red,
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'center',
                              style: TextStyle(color: Colors.white, fontSize: 30),
                            ),
                          ),
                        ),

The strange behaviour is that sometimes when I press center button I get `The method 'move' was called on null.` error, but not always.

 Sometimes works every time I press it, but sometimes it finds the value null after a few times that worked.

At first build, center button works as expected and centers the map, but always finds the value null after a Hot-reload or Hot-restart.. 

Can you see what I'm doing wrong ?
Thank you very much for your time and help.

Complete UI code:

    class MapScreen extends StatelessWidget {
      final String name;
      final MapRepository _mapRepository;
      final MapController _mapController;
    //  final AlertRepository _alertRepository;
      List<Marker> alerts;
      LatLng userLocation;
      MapScreen(
          {Key key, @required this.name, @required MapRepository mapRepository})
          : assert(mapRepository != null),
            _mapRepository = mapRepository,
            _mapController = MapController(),
    //        _alertRepository = alertRepository,
            super(key: key);
    
      
      @override
      Widget build(BuildContext context) {
        return BlocBuilder<MapBloc, MapState>(
    //        bloc: MapBloc(mapRepository: _mapRepository),
            builder: (BuildContext context, MapState state) {
          userLocation = (state as LocationStream).location;
    //      if (state is LocationStream) {
    //        userLocation = (state).location;
    //      }
          return Scaffold(
            appBar: AppBar(
              backgroundColor: Colors.transparent,
              elevation: 0,
              title: Text(
                'Home',
                style: TextStyle(color: Colors.orangeAccent, fontSize: 40),
              ),
              actions: <Widget>[
                IconButton(
                  icon: Icon(
                    Icons.exit_to_app,
                    color: Colors.orange,
                    size: 35,
                  ),
                  onPressed: () {
                    BlocProvider.of<AuthenticationBloc>(context).add(
                      LoggedOut(),
                    );
                  },
                ),
              ],
            ),
            backgroundColor: Colors.white,
            body: SafeArea(
              minimum: EdgeInsets.symmetric(horizontal: 20),
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Container(
                      height: 570,
                      width: 320,
                      child: FlutterMap(
                        options: MapOptions(
                          center: userLocation,
                          minZoom: 5.0,
                          maxZoom: 19.0,
                        ),
                        mapController: _mapController,
                        layers: [
                          //
    //        PolygonLayer(polygonOpts, map, stream)
    //                    PolygonLayerOptions(
    //                      polygons:
    //                    ),
                          TileLayerOptions(
                              urlTemplate:
                                  'https://api.openrouteservice.org/mapsurfer/{z}/{x}/{y}.png?api_key=5b3ce3597851110001cf62484c4b65d85bc844eca3a2c6b9f300ddf4',
    //                              urlTemplate:
    //                                  'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                              subdomains: ['a', 'b', 'c'],
                              keepBuffer: 20),
                          new MarkerLayerOptions(
                            markers: [
                              Marker(
                                point: userLocation,
                                height: 200,
                                width: 200,
                                builder: (context) => IconButton(
                                  icon: Icon(Icons.location_on),
                                  color: Colors.red,
                                  iconSize: 60,
                                  onPressed: () {
                                    print('icon tapped');
                                  },
                                ),
                              ),
    //                          Marker(
    //                            height: ,
    //                            builder: BlocBuilder<AlertBloc,AlertState>(
    //                                builder: (BuildContext context, AlertState state) {
    //                                  alerts = (state as AlertsUpdated).alerts;
    //                                  return
    //                                }),
    //                          )
                            ],
                          ),
                        ],
                      ),
                    ),
                    SizedBox(
                      height: 10,
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: <Widget>[
                        RaisedButton(
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(5)),
                          onPressed: () {
                            print(
                                ' @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   userLocation is $userLocation');
                            _mapController.move(userLocation, 16);
                          },
                          color: Colors.red,
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'center',
                              style: TextStyle(color: Colors.white, fontSize: 30),
                            ),
                          ),
                        ),
                        RaisedButton(
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(5)),
                          onPressed: () {
                            //TODO  this goes actually in a alert icon callbac, here just navigates icons vc
                          },
                          color: Colors.red,
                          child: Padding(
                            padding: EdgeInsets.all(8.0),
                            child: Text(
                              'alert',
                              style: TextStyle(color: Colors.white, fontSize: 30),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          );
        });
      }
    }

I also put together a sample app in case you want to have a look at it.
https://github.com/vinnytwice/flutter_app

**Comment by ibrierley** [comment]
I'm guessing (but maybe wrong!) the problem is something like your mapcontroller isn't initialised in time before you try and move it...

If that's the case, how you want to get around it is up to you, either check if initialised, or add a slight delay or something. I note there is a 'ready' &/or 'onReady' property, never used that, but it could be useful if it does what I think it may do.

**Comment by vinnytwice** [comment]
@ibrierley  Thank you very much for your hint.
Based on your suggestion I tried checking and it was indeed initialised, but still got there `move`error.
In another issue here I read that `FlutterMap`must be in a stateful widget so I changed mine. On incoming state I performed a check on the State type and in side called SetState with the new value from state. Error.. BlocBuilder wasn't the right choice anymore a builder that rebuilds building widget kind of error if I recall the error correctly. .. I swapped it for a BlocListener instead that has a callback on States, and called setState() in there.
It now center the map on userLocation even after Hot-reload or Hot-restart..and no more `move`errors.. so that one solved.

Still it doesn't draw map on userLocation at screen load.
Can you see what Im missing? Some initial coordinates perhaps?
Anyways.. shouldn't setState()  keep track of where userLocation is used and rebuild that widget ?  

If I call `_mapController.move(userLocation, 16);`right after SetState than the map will follow the user location, so if you pan it as soon as a new state comes in, the map moves.. useful in a step-by.step navigator, but is not what I need..

So the new code is:

```
// stateful widget using BlocListener:

class MapScreen extends StatefulWidget {
  final String name;
  final MapRepository _mapRepository;
//  MapController _mapController;
//  final AlertRepository _alertRepository;

  MapScreen(
      {Key key, @required this.name, @required MapRepository mapRepository})
      : assert(mapRepository != null),
        _mapRepository = mapRepository,
//        _mapController = MapController(),
//        _alertRepository = alertRepository,
        super(key: key);

  @override
  _MapScreenState createState() => _MapScreenState();
}

class _MapScreenState extends State<MapScreen> {
  List<Marker> alerts;

  LatLng userLocation;

  MapController _mapController = MapController();

  @override
  Widget build(BuildContext context) {
    return BlocListener<MapBloc, MapState>(
//        bloc: MapBloc(mapRepository: _mapRepository),
      listener: (BuildContext context, MapState state) {
//      userLocation = (state as LocationStream).location;
        if (state is LocationStream) {
          setState(() {
            userLocation = (state).location;
          });
        }
      },
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0,
          title: Text(
            'Home',
            style: TextStyle(color: Colors.orangeAccent, fontSize: 40),
          ),
          actions: <Widget>[
            IconButton(
              icon: Icon(
                Icons.exit_to_app,
                color: Colors.orange,
                size: 35,
              ),
              onPressed: () {
//              BlocProvider.of<AuthenticationBloc>(context).add(
//                LoggedOut(),
//              );
              },
            ),
          ],
        ),
        backgroundColor: Colors.white,
        body: SafeArea(
          minimum: EdgeInsets.symmetric(horizontal: 20),
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Container(
                  height: 570,
                  width: 320,
                  child: FlutterMap(
                    options: MapOptions(
                      center: userLocation,
                      minZoom: 5.0,
                      maxZoom: 19.0,
                    ),
                    mapController: _mapController,
                    layers: [
                      //
//        PolygonLayer(polygonOpts, map, stream)
//                    PolygonLayerOptions(
//                      polygons:
//                    ),
                      TileLayerOptions(
                          urlTemplate:
                              'https://api.openrouteservice.org/mapsurfer/{z}/{x}/{y}.png?api_key=5b3ce3597851110001cf62484c4b65d85bc844eca3a2c6b9f300ddf4',
//                              urlTemplate:
//                                  'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                          subdomains: ['a', 'b', 'c'],
                          keepBuffer: 20),
                      new MarkerLayerOptions(
                        markers: [
                          Marker(
                            point: userLocation,
                            height: 200,
                            width: 200,
                            builder: (context) => IconButton(
                              icon: Icon(Icons.location_on),
                              color: Colors.red,
                              iconSize: 60,
                              onPressed: () {
                                print('icon tapped');
                              },
                            ),
                          ),
//                          Marker(
//                            height: ,
//                            builder: BlocBuilder<AlertBloc,AlertState>(
//                                builder: (BuildContext context, AlertState state) {
//                                  alerts = (state as AlertsUpdated).alerts;
//                                  return
//                                }),
//                          )
                        ],
                      ),
                    ],
                  ),
                ),
                SizedBox(
                  height: 10,
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    RaisedButton(
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(5)),
                      onPressed: () {
                        print(
                            ' @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   userLocation is $userLocation');
                        _mapController.move(userLocation, 16);
                      },
                      color: Colors.red,
                      child: Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Text(
                          'center',
                          style: TextStyle(color: Colors.white, fontSize: 30),
                        ),
                      ),
                    ),
                    RaisedButton(
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(5)),
                      onPressed: () {
                        //TODO  this goes actually in a alert icon callbac, here just navigates icons vc
                      },
                      color: Colors.red,
                      child: Padding(
                        padding: EdgeInsets.all(8.0),
                        child: Text(
                          'alert',
                          style: TextStyle(color: Colors.white, fontSize: 30),
                        ),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
} 
```

**Comment by ibrierley** [comment]
I think you may have to do a _mapController.move in your location listener function, rather than calling setState yourself at all ?

**Comment by vinnytwice** [comment]
@ibrierley I call `setState` because User Icon has to move reflecting user position at all time, without it it stays on the first userLocation coordinates that it get drawn on. But you see? It does get drawn at `userLocation`coordinates, why map doesn't?

This is the issue that I mentioned before https://github.com/johnpryan/flutter_map/issues/58
Dough they use redux they have the same problem : `center`.

**Comment by ibrierley** [comment]
I think what I meant was something like this (not at a pc I can test with here atm, so I may be talking rubbish :D)
```
 if( state is LocationStream) {
            userLocation = (state).location;
            _mapController.move(userLocation, 16);
  }

**Comment by vinnytwice** [comment]
@ibrierley Yes I understood you, but that way user icon won't move.

this way does but I don't need the map to move with user location:

```
if (state is LocationStream) {
          setState(() {
            userLocation = (state).location;
          });
          _mapController.move(userLocation, 16);
        }
```

so I use this :

```
if (state is LocationStream) {
          setState(() {
            userLocation = (state).location;
          });
          //_mapController.move(userLocation, 16);
        }
```

and call `_mapController.move(userLocation, 16);` with a button callback only when needed.

is in here that it should take the coordinates but id doesn't.


```
FlutterMap(
                    options: MapOptions(
                      center: userLocation,
                      minZoom: 5.0,
                      maxZoom: 19.0,
                    ),
                    mapController: _mapController,
```

**Comment by ibrierley** [comment]
If you don't want the map to move, what happens if you do in the listener
 
userLocation = (state).location;
mapController.move(map.center, 16);

The general point being, it's mapController.move that will cause the update to the icon (even if it's the same location)..

**Comment by vinnytwice** [comment]
No.. that was working before. That way, now, the Icon stays still and the map moves ..MapScreen is now a stateful widget, so if you don't call `setState()`no widget will update on newer value, dough `_mapController.move`still works..so only the map moves.

**Comment by ibrierley** [comment]
Btw there is an an example moving markers in the example folder that may do what you want.

**Comment by vinnytwice** [comment]
@ibrierley I finally sorted it out.

I tried two different approaches and they both work.
First one is using a method that I actually written right at the beginning and forgotten about (don't know why..) and haven't tried to use, thinking that with just the stream I would be fine.
The method just returns a `Future<LatLng>`. 

```
Future<LatLng> getLocation() async {
    print('getLocation() called');
    Position position;
    LatLng location;
    try {
      position = await locationManager
          .getCurrentPosition(
              desiredAccuracy: LocationAccuracy.bestForNavigation)
          .timeout(Duration(seconds: 5));
      location = LatLng(position.latitude, position.longitude);
      print('getLocation() location is: $location');
      return location;
    } catch (error) {
      print(
          'getLocation(): error getting current location: ${error.toString()}');
    }
  }
```

I just send two events in `BlocProvider` from `main()` 

```
BlocProvider<MapBloc>(create: (context) {
          return MapBloc(
            mapRepository: mapRepository,
          )
            ..add(GetLocationStream())
            ..add(GetInitialLocation());
        }),
```

 event to trigger it and yield  a state with the value in bloc.

```
Stream<MapState> _mapCenterMapToState(GetInitialLocation event) async* {
    location = await _mapRepository.getLocation();
    print('_mapCenterMapToState location is : ${_mapRepository.getLocation()}');
    yield MapLoading(location);
  } 
```


Than in the listener added a new state check and used the value to move the map.

```
BlocListener<MapBloc, MapState>(
            listener: (BuildContext context, MapState state) {
          if (state is LocationStream) {
            setState(() {
              userLocation = (state).location;
            });
          }
          if (state is MapLoading) {
            userLocation = (state).location;
            print(
                ' @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ MapBloc initial state location is : $userLocation');
            _mapController.move(userLocation, 16);
          }
        })
```
 
I actually now remember why I did abandon this `getLocation() approach .. I didn't know how to use Futures and I got stuck in getting back the value in bloc, and thought that with just a stream I'd be sorted.. well it turns out that I had thought the logic correctly from the beginning..but I was too new to Flutter to code it right..lol..

Almost forgot.. the second method uses a different bloc just for the initial user location.   With the second one I'm listening to the same `Stream<LatLng>` but just getting the `.first`or `.single` that also returns a `Future<LatLng>`..but with first approach is tidier(less files), easier to read, and it also saves some resources I guess as I don't open two streams.. 

Many thanks for helping me out. I do appreciate it very much.
Cheers.
