### ISSUE TITLE
handling tileProvider errors

### ISSUE THREAD

**Issue by X-SLAYER** [johnpryan/flutter_map#536]
sometime tileProvider cause stopping of the app because of the remote server cant return a response or the cachingNetwork cant find a file but i didn't find a way to handle these errors to avoid the crash of the app

**Comment by ibrierley** [comment]
hmm it doesn't crash it on mine (I have a pull request that "may" help with that, not sure), but I suspect could be handled better...does it trigger a crash in release mode, and is it possible to include the code to replicate ? It may be worse on certain tileproviders.

**Comment by X-SLAYER** [comment]
> hmm it doesn't crash it on mine (I have a pull request that "may" help with that, not sure), but I suspect could be handled better...does it trigger a crash in release mode, and is it possible to include the code to replicate ? It may be worse on certain tileproviders.

ididint try it on release mode , but in debug mode try to use NonCachingNetworkTileProvider and zoom in more and more until the server could not get an image and it will throw eception

**Comment by ibrierley** [comment]
In the interim, to get around that problem, maybe set a min/maxzoom, to prevent that problem. But naturally we don't want it to crash still, just handle it gracefully.

**Comment by X-SLAYER** [comment]
yes i already did but for cachingNetworkTile i cant handle that

**Comment by ibrierley** [comment]
It may be useful to post the output of the crash btw, just to see which bit is causing it, maybe that provider can wrap the request in a try clause or something.

**Comment by X-SLAYER** [comment]
════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: File was empty

When the exception was thrown, this was the stack
#0      CachedNetworkImageProvider._loadAsyncFromFile 
package:cached_network_image/src/cached_network_image_provider.dart:75

![Capture](https://user-images.githubusercontent.com/22800380/76070479-e3cec980-5f94-11ea-8819-6aaf1f2bf778.PNG)

**Comment by eon46** [comment]
I have same error
