### ISSUE TITLE
Watermark creditation (feature)

### ISSUE THREAD

**Issue by alfanhui** [johnpryan/flutter_map#54]
This feature should be self-fullfilling, but would be good to allow users to add their own TextSpan (text with urls) to the bottom right/left corners. 

![image](https://user-images.githubusercontent.com/2172019/41380838-ef4b1cb0-6f5d-11e8-8ce4-bcfe6e45bfd6.png)

**Comment by avioli** [comment]
My suggestion - make a flutter_map plugin, although a simple Stack will do just fine.

If you have areas with different tile sources that need attribution, then listen on the move stream.

**Comment by johnpryan** [comment]
This is now supported via the plugin api

**Comment by Xennis** [comment]
I shared an example here #671
