### ISSUE TITLE
Dragabble marker example?

### ISSUE THREAD

**Issue by klaszlo8207** [johnpryan/flutter_map#540]
Any example on this? How to drag my locations marker?

**Comment by show111** [comment]
I also want to know the answer to this question.

**Comment by johnpryan** [comment]
There's not likely to be any offical support for this. For how-to questions I recommend StackOverflow. I would  try getting drag and drop working with regular (non-map) widgets and adapt it from there, possibly using the plugin API.

**Comment by ibrierley** [comment]
Out of interest I know this is closed, but I thought this may be a useful little project that introduced another plugin for draggable markers. 

see the main.dart file for example, I've uploaded at https://github.com/ibrierley/flutter_map_dragmarker if anyone wants an experiment, you just need the dragmarker.dart file.
