### ISSUE TITLE
Unable to install packages in flutter

### ISSUE THREAD

**Issue by rahul-bavaliya** [johnpryan/flutter_map#547]
I follow installation guides, I added dependency in **pubspec.yaml**. But it throws error. Here I mention it below.
Error: [flutter_map] flutter packages get
Running "flutter pub get" in flutter_map...                     
Error on line 26, column 3 of pubspec.yaml: **A package may not list itself as a dependency.**

   ╷

26 │   flutter_map: 
   │   ^^^^^^^^^^^

   ╵
pub get failed (65;    ╵)
exit code 65

**Comment by ibrierley** [comment]
Have you called your own app flutter_map ? Or another package/file called that. That's the normal issue.

**Comment by rahul-bavaliya** [comment]
> Have you called your own app flutter_map ? Or another package/file called that. That's the normal issue.

I try to install flutter_map dependency. But unable to download it.

**Comment by ibrierley** [comment]
Sure, but what is your app called ?

**Comment by rahul-bavaliya** [comment]
> Sure, but what is your app called ?

Thanks, It was silly mistake that I gave my app name same as dependency name.
