### ISSUE TITLE
Map Plugins, general question.

### ISSUE THREAD

**Issue by mat8854** [johnpryan/flutter_map#549]
Hello, I was looking into the sample application.  Functional map extensions are provided by implementing `MapPlugin` there.

How are these plugins managed and distributed (I mean plugins of common interest)?

**Comment by ibrierley** [comment]
Good question, I've done a bit of work, it would be nice to have a place to add links to a page at least, as not quite sure what to do with. I guess there's a few plugins out there as well, that would save people doing some work. Could also have ones in progress ?

I guess it would be difficult with loads of plugins to include them with this main one maybe (there's a couple in the examples code), as it adds a lot of overhead to testing etc, but it could at least be worth having a page with a list of them, their github link (so could easily be added to a pubspec.yaml) and a description and a last tested version it worked with ?

**Comment by mat8854** [comment]
@ibrierley Okay, I have been working with [osmdroid](https://github.com/osmdroid/osmdroid) . There these features are `Overlays` directly included in the library. 

The really basic features are:
* ScaleBar (already in example application, could be more customizable)
* Icon for Rotation indication
* Adaptive Lat/Lon Grid
* ...

Yes, as a first step this repo  `README` could link to proven `MapPlugin`s.

**Comment by mat8854** [comment]
Can be closed. I see there are already plugin linked at the bottom of this repo README.
