### ISSUE TITLE
Know if user moved map manually

### ISSUE THREAD

**Issue by julien-h** [johnpryan/flutter_map#554]
Hello,

This is either a question or a feature request. I want to automatically center the map on the last marker, unless the user moved or zoomed the map manually. 

Is there a way to detect if the user interacted with the map manually ? I didn't find anything in the api.

**Comment by ibrierley** [comment]
Can't you just compare the map.center to a previous one you stored ?

**Comment by julien-h** [comment]
Hi ibrierley,

I want to have two modes : (1) auto-centered on user location and (2) manual.

So I have a button to center the view and it should be disabled when mode (1) is already activated and enabled when mode (2) activates. And i want to automatically switch mode when the user moves the map.

How would I implement this reactivity with your approach? I need to be reactive

**Comment by ibrierley** [comment]
I haven't tested uses this callback, but there's a param, 

final PositionCallback onPositionChanged;

So I assume I could probably add a callback function if the map changes, to say in pseudocode, 

onPositionChanged: positionHasChanged, // in map params

// sep func
void positionHasChanged() {
  togglemode();
}

**Comment by julien-h** [comment]
Thank you, this is what I needed. The `hasGesture` parameter did the trick.

**Comment by julien-h** [comment]
For anyone interested, here's how to use it:

```
 FlutterMap(
        mapController: mapController,
        options: new MapOptions(
          onPositionChanged: (position, hasGesture) { /* here */ },
        ),
        ....
```

**Comment by arashAndroid** [comment]
Hi. Good day to you all!
The onPositionChanged option works but it gets called every time the map changes. But I want to get the position where I lift my finger (stop touching screen). Then I want to call an API to get list of markers near that location. 
So the problem with onPositionChanged is that it gets called a lot of times and I can not call the API that many times! So it would be great if I was able to call it when the user stops touching screen, like the onTapUp option in gestureDetector.
Is there any way to implement this?
