### ISSUE TITLE
Center map based on markers?

### ISSUE THREAD

**Issue by iJamesPHP** [johnpryan/flutter_map#558]
Hi, I'm using the marker cluster plugin and have got it implemented just fine and it's doing everything that I need.

I would like the map to initiate with a center and zoom level that includes all of the markers, e.g. if one was one side of the world and the other was on the other, it should show the entire map to make sure they're both visible.

How can I achieve this? Will I have to do some custom math with all of the marker's vectors or is there a built-in way to do it?

Thanks

**Comment by HugoHeneault** [comment]
Yes there is a built in way. Check it on https://github.com/johnpryan/flutter_map/blob/ef15ae9b88d9acecaea458d115076ac49ffbd5fc/example/lib/pages/map_controller.dart

with `fitBounds` method :)

**Comment by iJamesPHP** [comment]
Thanks very much!

Here's how implemented it:
`
_mapController.onReady.then((value) {
      var bounds = LatLngBounds();
      data.filteredAssets.where((Asset asset) => asset.coords != null).toList().forEach((Asset asset) {
        bounds.extend(asset.coords);
      });
      _mapController.fitBounds(
        bounds,
        options: FitBoundsOptions(
          padding: EdgeInsets.all(30),
        ),
      );
    });
`
