### ISSUE TITLE
Missing permissions in Android release mode

### ISSUE THREAD

**Issue by syonip** [johnpryan/flutter_map#568]
Hi,
When running in release mode in android, the map is blank, as shown in this SO issue:
https://stackoverflow.com/questions/59756576/flutter-map-blank-in-device-android

This is because of missing INTERNET permission in the release manifest file.

I can create PR if needed.
Thanks.

**Comment by X-SLAYER** [comment]
add `<uses-permission android:name="android.permission.INTERNET"/>` in the AndroidManifest.xml file.

**Comment by syonip** [comment]
Thanks @X-SLAYER ,
This is indeed the solution, but I think it should be documented in the plugin's readme.
