### ISSUE TITLE
Is there a way to redraw Polylines

### ISSUE THREAD

**Issue by r4ptus** [johnpryan/flutter_map#571]
I want to redraw my Polyline depending on a specific choice and without redrawing the complete map.
Is this possible?

**Comment by bettdouglas** [comment]
Can you give a clearer example of what you want to accomplish? Can't you accomplish this by using setState?

**Comment by r4ptus** [comment]
i render a map with an overlay above it,
then i can choose between difrent details and wich each detail the polyline changes.
i cant use setState cause everything redraws

**Comment by ian-workcircle** [comment]
I suspect the pull request at https://github.com/johnpryan/flutter_map/pull/542 could get around this, as it moves everything to widgets, just if you need the feature desperately it may be worth a test and give feedback there.

**Comment by devzom** [comment]
I have similar issue, but maybe it corespond to GoogleMaps. When I clear polyline id "poly" and tried to redraw it using **setState()** it draws a straight polyline from A to B point. Had smth like this?

**Comment by r4ptus** [comment]
I got it now.
Solved it with the bloc pattern and streams

**Comment by devzom** [comment]
@r4ptus  it's not solved for me unlucky...  had some issue like me?

> I have similar issue, but maybe it corespond to GoogleMaps. When I clear polyline id "poly" and tried to redraw it using setState() it draws a straight polyline from A to B point. Had smth like this?

@johnpryan know anything about it? 
I am using GoogleMaps and when remove old polyline by remove(string) and using function to draw polyline  from the same currentLocation -> destinationLocation getting straight polyline.

**Comment by johnpryan** [comment]
I’m not sure I understand the problem exactly. I would use setState() to update any poly lines. It does redraw, but unless you’re seeing performance issues I assume it wouldn’t be noticeable.
