### ISSUE TITLE
Flicker on double click zoom

### ISSUE THREAD

**Issue by ibrierley** [johnpryan/flutter_map#578]
There seems to be a flicker with the new tiling when you double click/tap zoom in (it doesn't seem to do it on an instant zoom, like the zoomplugin example, and doesn't do it on a gradual finger zoom).

It feels like when you double tap somewhere, somewhere in the first few frame animation (so hard to capture when) it jumps to one zoom level which flickers, then acts normally shortly after.

It's not a breaking issue or anything (it's far better than the old ver), but would be nice to isolate what's happening if it's simple.

I can't capture it, as it's too quick, but I think it's part of the animation. To reproduce, go to the example, eg OpenStreetMap and double tap, there will be a flicker of different tiles before animating the correct ones. It's only very slight, but just enough to be worth a fix.

Could it be it's initially displaying a zoomed in level, and then animating to it after or maybe when it transitions levels (or a zoom tile level ordering thing when transitioning levels) ?

**Comment by maRci002** [comment]
Hi @ibrierley maybe [this](https://github.com/johnpryan/flutter_map/pull/572#issuecomment-610269536) will help because by default there is 50ms delay before throw away old tiles.

Or startFadeInAnimation is called before setState the above fix tries to elimante this too, please take a look.

**Comment by maRci002** [comment]
@ibrierley I think I found out what you meant under flicker bug #579 is a fast patch, try it.

**Comment by ibrierley** [comment]
Thanks for the speedy fix, appreciate all the work you've done. I haven't
had chance to test yet, but your gif example looks good. Will try when I
get chance.

Ian
