### ISSUE TITLE
Feature: post process tiles with ColorFiltered widget

### ISSUE THREAD

**Issue by mat8854** [johnpryan/flutter_map#581]
Hello, I suggest a small update to `TileLayerOptions` with an optional parameter for a [ColorFilter.matrix](https://api.flutter.dev/flutter/dart-ui/ColorFilter/ColorFilter.matrix.html) to post process the tiles. Widget [ColorFiltered](https://api.flutter.dev/flutter/widgets/ColorFiltered-class.html).

Below the modified code sample for gray scale tiles (hard coded). Could also be used for visual enhancements (contrast, night vision, ...).

```
    return ColorFiltered(
        colorFilter: ColorFilter.matrix(<double>[
          0.2126,0.7152,0.0722,0,0,
          0.2126,0.7152,0.0722,0,0,
          0.2126,0.7152,0.0722,0,0,
          0,0,0,1,0,
        ]),
      child: Opacity(
        opacity: options.opacity,
        child: Container(
          color: options.backgroundColor,
          child: Stack(
          children: tileWidgets,
        ),
      ),
      ),
    );
  }
```

Edit: posted wrong code, now with child.

Not sure if this is the best place to do the filtering performance wise. Please comment.

**Comment by maRci002** [comment]
I checked it out and it looked awesome. However it should be the child of `Opacity` because if there are multiple Layers stacked on eachother this may cover lower layers or ColorFiltered will affect lower layers if opacity is low.

`TileLayerOptions` should have a `final ColorFilter colorFilter;` property and the final code would look like this in `build` method:
```
    var content = options.colorFilter == null
        ? Container(
            color: options.backgroundColor,
            child: Stack(
              children: tileWidgets,
            ),
          )
        : ColorFiltered(
            colorFilter: options.colorFilter,
            child: Container(
              color: options.backgroundColor,
              child: Stack(
                children: tileWidgets,
              ),
            ),
          );

    return Opacity(
      opacity: options.opacity,
      child: content,
    );
```

**Comment by mat8854** [comment]
Okay, I will open a PR.

**Comment by mat8854** [comment]
PR submitted. Closing this.
