### ISSUE TITLE
Zooming out very far causes null pointers

### ISSUE THREAD

**Issue by lenis0012** [johnpryan/flutter_map#59]
When zooming out very far and moving the map around, you are greeted with the following error.

https://pastebin.com/VxQ5jKhX

Setting the pan boundary to -90, -180 and 90, 180 did not resolve the issue.

**Comment by alfanhui** [comment]
That error looks like the centre MapOptions is not set. If you have your MapOptions arguments, this will help more, or try setting centre to LatLng coordinates. 

The pan boundaries take LatLng coordinates at southwest and northeast boundaries, so setting them using degrees does not work (or make sense? )

**Comment by lenis0012** [comment]
Hi @alfanhui 
Thanks for your response.

these are the options I am using
```dart
options: new MapOptions(
        center: new LatLng(51.5, -0.09),
        zoom: 2.0,
        swPanBoundary: new LatLng(-90.0, -180.0),
        nePanBoundary: new LatLng(90.0, 180.0),
      ),
```

**Comment by GregorySech** [comment]
Right now when using the package example zooming out does not cause an exception to be thrown but the map simply freezes and cannot be "zoomed in".
