### ISSUE TITLE
LatLng not working

### ISSUE THREAD

**Issue by ayush1612** [johnpryan/flutter_map#591]
`
new MarkerLayerOptions(
            markers: [
              new Marker(
                width: 80.0,
                height: 80.0,
                point: new LatLng(40.73, -74.00),
 builder: (ctx) => new Container(
                  child: new FlutterLogo(),
                ),
              ),
`
![img](https://user-images.githubusercontent.com/42496674/79631199-16afd400-8175-11ea-90aa-c8179f9cbf90.png)

**Comment by ibrierley** [comment]
Try importing LatLng

**Comment by ayush1612** [comment]
Thanks.
I imported **latlong** after including it in pub.yaml. It's working now but there is another issue.
![img](https://user-images.githubusercontent.com/42496674/79639430-66a88e00-81a9-11ea-84c6-4c5be35bc362.png)

**Comment by ayush1612** [comment]
Ok i got the error cleared.
I was using the WMTS url instead of CARTO.
Thanks for your help.
