### ISSUE TITLE
Scrolling over 180 degrees west and east supported?

### ISSUE THREAD

**Issue by mat8854** [johnpryan/flutter_map#594]
Hello, is scrolling and rendering tiles over the date line supported over some parameter?

**Comment by avioli** [comment]
Could you define `date line`?

**Comment by mat8854** [comment]
I mean the map is rendered once and then surrounded by gray on the outside. Scrolling over date line means scrolling over the red line. Over green line is not so crucial.

![Screenshot_20200420-101453](https://user-images.githubusercontent.com/2643309/79730203-c65d8100-82f0-11ea-92c9-bae6214d3ebc.png)
![Screenshot_20200420-101447](https://user-images.githubusercontent.com/2643309/79730204-c6f61780-82f0-11ea-97ae-ad8cbedd2f2b.png)


If you look at `osmdroid` for example the map is extentended and scrollable in all directions by default.

**Comment by mat8854** [comment]
Asked for #599 . Can be closed.
