### ISSUE TITLE
Questions: Touch hierarchy for many layers

### ISSUE THREAD

**Issue by mat8854** [johnpryan/flutter_map#597]
The order of the widgets in the layer parameter determinantes not only the drawing but also
the touch event / blocking order (?).

Even layers only containing a `CustomPainter` (lines across the whole screen, but with lots of spacing) block the touch events for lower widgets?

Any Flutter expert knowns more about that behaviour?

Cluster marker widget not clickable if added before line drawer plugin.
![Screenshot_20200421-091847](https://user-images.githubusercontent.com/2643309/79837292-7d213600-83b1-11ea-85f3-0711acd7ea5c.png)

**Comment by moovida** [comment]
I am also interested in this. Assume this is the same as issue #390

**Comment by mat8854** [comment]
It is definitely not default Android style right now: https://stackoverflow.com/questions/7449799/how-are-android-touch-events-delivered

**Comment by moovida** [comment]
Yes, agreed, usually someone has to consume the event and let others know. Not sure how this would have to be implemented here though.

**Comment by avioli** [comment]
A `CustomPaint` widget doesn't capture gestures, so this shouldn't happen.

Do you have any pointer capturing widgets in the tree? If you do then it is your job to determine when a gesture should or shouldn't be captured by your gesture recogniser.

Could you post an example?

**Comment by mat8854** [comment]
I will debug it with the `Flutter Inspector` from Android Studio ...

I see there is a dummy Container in the `MapPlugin` `createLayer` to get width and height (as work around):
```
return Center(
          child: CustomPaint(
            // the child empty Container ensures that CustomPainter gets a size
            // (not w=0 and h=0)
            child: Container(),
            painter: Myainter(options: options, mapState: mapState),
          )
      );
```

**Comment by mat8854** [comment]
@avioli Okay in this case it was really the added Container. This works in both layer orders:
```
return Center(
          child: CustomPaint(
            painter: MyPainter(options: options, mapState: mapState),
          )
      );
```

**Comment by mat8854** [comment]
> I am also interested in this. Assume this is the same as issue #390

@moovida I read the issue. My full screen map layers are not clickable. I just added them now before the marker cluster plugin. That solved the issue for me.
