### ISSUE TITLE
Empty map tails when return to same route

### ISSUE THREAD

**Issue by beerline** [johnpryan/flutter_map#608]
Hi flutter_map team! 

In examples, if you try to open same route the map widget show no tiles, until you trying to move or zoom map. See screen cast.

Any ideas how it can be fixed?

![2020-05-04 23-58-06](https://user-images.githubusercontent.com/7195911/81018424-c6b75980-8e64-11ea-9c54-cfb1a042bb06.gif)

**Comment by enrimon15** [comment]
I have the same problem. I have seen that if you use pushAndReplacementNamed('your route') this problem doesn't show up, but if you just use pushNamed('your route') it doesn't work. Is there a method to make the map work with pushNamed?
I'm on Flutter web so i need to use pushNamed instead of pushAndReplacementNamed

**Comment by beerline** [comment]
@enrimon15, thank you. I will try to use it as workaround

**Comment by matthwfalk** [comment]
In my implementation the problem with **pushReplacementNamed('route')** also shows up. I am not able to get it running after route state changes. 

pushReplacement() - not working
pushReplacementNamed() - not working
popAndPushNamed() -not working

Any suggestions?

**Comment by enrimon15** [comment]
@matthwfalk try to put tileProvider: NonCachingNetworkTileProvider(), in TileLayerOptions. Or you can try with pushNamedAndRemoveUntil

**Comment by matthwfalk** [comment]
I found a workaround that works for me.

To make clear what I am trying to implement (Weather Radar):

- Loading a base map from MapBox
- Adding dynamic WMS layer tiles from local weather service on top of it
- Changing the dynamic WMS layers on button click

This all works fine if I use the code from this commit:

```
  flutter_map:
    git:
      url: https://github.com/johnpryan/flutter_map.git
      ref: 3b6944343eab0805c08c857db55d9a3b125666b3
```

The next commit is not working as expected. I think its all about the caching of image data in flutter.

Maybe we can fix that in the upcoming version :)

**Comment by maRci002** [comment]
PR #715 fix the issue without tricking with Navigator.
