### ISSUE TITLE
Geojson from api

### ISSUE THREAD

**Issue by adnanefouam** [johnpryan/flutter_map#615]
i have multiple adresses  from api with coordinates and i want to display their geojson data on the map like this

<img width="1680" alt="Screen Shot 2020-05-12 at 07 51 23" src="https://user-images.githubusercontent.com/59290932/81655236-9d2e9d00-9425-11ea-83f5-0de01837c46e.png">

**Comment by ibrierley** [comment]
This may be of some use, see the example Parse and listen...

https://pub.dev/packages/geojson

Ian

**Comment by hahazheng** [comment]
@adnanefouam You are using google map ?

**Comment by adnanefouam** [comment]
@hahazheng no im using mapbox

**Comment by hahazheng** [comment]
@adnanefouam  How will mapbox be used in flutter_map?
I have a doubt and want to hear your thoughts

**Comment by adnanefouam** [comment]
FlutterMap(
                options:
                    MapOptions(
                      center: LatLng( widget.lon , widget.lat), zoom: 15,
                minZoom: 3.0,
               maxZoom: 20.0,
                      interactive: true, ),
                layers: [

              TileLayerOptions(
                  urlTemplate:
                  'MAPBOXURLaccess_token=YOUR_TOKEN_KEY ,         
  dditionalOptions: {
                    'accessToken':
                        'YOUR_TOKEN_KEY',
                    'id': 'mapbox.mapbox-stretts-v8',
                  }),

              MarkerLayerOptions(markers: [
                Marker(
                    width: 45.0,
                    height: 45.0,
                    point: LatLng(widget.lon , widget.lat),
                    builder: (context) => Container(
                          child: IconButton(
                            icon: Icon(Icons.location_on),
                            color: primarycolor,
                            iconSize: 45.0,
                            onPressed: () {
                              parseAndDrawAssetsOnMap();
                              print('Marker tapped');
                            },
                          ),
                        ))
              ]),
                  PolylineLayerOptions(
                    polylines: statefulMapController.lines,
                  ),
            ]),

**Comment by hahazheng** [comment]
@adnanefouam 
![image](https://user-images.githubusercontent.com/14149301/81673011-916ec500-947d-11ea-9a41-c93639d287f9.png)
Is there something wrong? I can't run

**Comment by dariocavada** [comment]
I use this code and it works perfectly:
I've stored in the following case the accessToken in a separated class.

``` dart
TileLayerOptions(
              urlTemplate: "https://api.tiles.mapbox.com/v4/"
                  "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
              additionalOptions: {
                'accessToken': secrets.accessToken,
                'id': 'mapbox.streets',
              },
            ),
```

What problems did you have? Can you describe it better?

**Comment by hahazheng** [comment]
@dariocavada 

> I use this code and it works perfectly:
> I've stored in the following case the accessToken in a separated class.
> 
> ```dart
> TileLayerOptions(
>               urlTemplate: "https://api.tiles.mapbox.com/v4/"
>                   "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
>               additionalOptions: {
>                 'accessToken': secrets.accessToken,
>                 'id': 'mapbox.streets',
>               },
>             ),
> ```
> 
> What problems did you have? Can you describe it better?

![image](https://user-images.githubusercontent.com/14149301/81674298-85840280-947f-11ea-8df8-4756ae4ad8f4.png)
Our code is consistent。

**Comment by adnanefouam** [comment]
i created a variabl named geoJson,

 var geoJson = {
      "type": "FeatureCollection",
      "features": [
    {
    "geometry": {
    "coordinates": widget.data,   //here i put my data from api 
    "type": "LineString"
    },
    "id": "67482000440040",
    "properties": {
    "commune": "67482",
    "contenance": 9.115727199974797e-07,
    "created": "",
    "numero": "40",
    "prefixe": "000",
    "section": "44",
    "updated": "2006-03-09"
    },
    "type": "Feature"
    } 

and i used   data =json.encode(geoJson) ; instead of  data = await rootBundle
        .loadString('assets/........');




NOTE  :  always keep an eye on how much arrays inside the coordinates 



thank you guys for this amazing package !!

**Comment by adnanefouam** [comment]
i created a variabl named geoJson,

 var geoJson = {
      "type": "FeatureCollection",
      "features": [
    {
    "geometry": {
    "coordinates": widget.data,   //here i put my data from api 
    "type": "LineString"
    },
    "id": "67482000440040",
    "properties": {
    "commune": "67482",
    "contenance": 9.115727199974797e-07,
    "created": "",
    "numero": "40",
    "prefixe": "000",
    "section": "44",
    "updated": "2006-03-09"
    },
    "type": "Feature"
    } 

and i used   data =json.encode(geoJson) ; instead of  data = await rootBundle
        .loadString('assets/........');




NOTE  :  always keep an eye on how much arrays inside the coordinates 



thank you guys for this amazing package !!

**Comment by tzsword** [comment]
> @dariocavada
> 
> > I use this code and it works perfectly:
> > I've stored in the following case the accessToken in a separated class.
> > ```dart
> > TileLayerOptions(
> >               urlTemplate: "https://api.tiles.mapbox.com/v4/"
> >                   "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
> >               additionalOptions: {
> >                 'accessToken': secrets.accessToken,
> >                 'id': 'mapbox.streets',
> >               },
> >             ),
> > ```
> > 
> > 
> > What problems did you have? Can you describe it better?
> 
> ![image](https://user-images.githubusercontent.com/14149301/81674298-85840280-947f-11ea-8df8-4756ae4ad8f4.png)
> Our code is consistent。

excuse me, same problem here. Did you solve it?

**Comment by tzsword** [comment]
> @dariocavada
> 
> > I use this code and it works perfectly:
> > I've stored in the following case the accessToken in a separated class.
> > ```dart
> > TileLayerOptions(
> >               urlTemplate: "https://api.tiles.mapbox.com/v4/"
> >                   "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
> >               additionalOptions: {
> >                 'accessToken': secrets.accessToken,
> >                 'id': 'mapbox.streets',
> >               },
> >             ),
> > ```
> > 
> > 
> > What problems did you have? Can you describe it better?
> 
> ![image](https://user-images.githubusercontent.com/14149301/81674298-85840280-947f-11ea-8df8-4756ae4ad8f4.png)
> Our code is consistent。

hi ~ i made it works.
![image](https://user-images.githubusercontent.com/20581031/82152951-3848cc00-9897-11ea-94c3-f83b6c840a89.png)

> code: 
![image](https://user-images.githubusercontent.com/20581031/82152978-53b3d700-9897-11ea-888f-424e298fb01f.png)

1.  open this site: https://studio.mapbox.com/
2. click the new styles button
    
![image](https://user-images.githubusercontent.com/20581031/82153023-983f7280-9897-11ea-8e41-69f1bb50bde5.png)
3. select a style 
  
![image](https://user-images.githubusercontent.com/20581031/82153067-d472d300-9897-11ea-9a82-b56a9200befa.png)

4. click the share of navigation bar
![image](https://user-images.githubusercontent.com/20581031/82153129-33384c80-9898-11ea-8bcd-fbea5451ce39.png)

5. select Third Party and CARTO
![image](https://user-images.githubusercontent.com/20581031/82153210-af329480-9898-11ea-92d6-1e54b601acec.png)

That's it. it works haaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ~ If you have a better way, please tell me thanku 
Gooooooooooooooooood luck~
