### ISSUE TITLE
Is it possible to use GeoPackage files within flutter_map

### ISSUE THREAD

**Issue by fryette** [johnpryan/flutter_map#621]

**Comment by moovida** [comment]
Yes, with the package https://pub.dev/packages/flutter_geopackage
There is an example with flutter_map.
Mind that the next version will dump sqflite for moor, since sqflite doesn't allow functions to be defined, which is preventing geopackage to be editable and to properly use spatial indexes.

**Comment by fryette** [comment]
@moovida  Thx for a response, but I cannot see any examples with flutter map. Could you please provide direct link?

**Comment by moovida** [comment]
Ah, sorry, my bad, in the current version there is only a text view in which the result of the calls are shown. Actually the example with flutter is in the branch of next version: moor_test

**Comment by fryette** [comment]
@moovida 
Thank you very much!
Will check. I will close the issue for now.
Please do not remove the branch)

**Comment by moovida** [comment]
Don't worry @fryette , that one will be the future master branch.
