### ISSUE TITLE
[QUESTION] assetName != null

### ISSUE THREAD

**Issue by brenoasm** [johnpryan/flutter_map#632]
Hi, I'm getting this error very often using the openStreetMap template 'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 134 pos 15: 'assetName != null': is not true. Is something wrong with the layerTileOptions? 

```
TileLayerOptions(
          urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          subdomains: ['a', 'b', 'c'],
        ),
```

Thanks in advance.

**Comment by ibrierley** [comment]
Maybe add a bit more code to show how it's being used. I'm assuming it works sometimes from the description ?

**Comment by brenoasm** [comment]
Sorry, I did something wrong with a marker... My mistake, thanks @ibrierley.
