### ISSUE TITLE
on tap polygon for infowindow

### ISSUE THREAD

**Issue by Anup2712** [johnpryan/flutter_map#634]
I am using flutter map and geojson to plot polygon.how to add ontap in to polygon??

`Future<void> processData({dynamic json32, Color color}) async {
    polygons.clear();
    final geojson = GeoJson();
    geojson.processedMultipolygons.listen((GeoJsonMultiPolygon multiPolygon) {
      for (final polygon in multiPolygon.polygons) {
        final geoSerie = GeoSerie(
            type: GeoSerieType.polygon,
            name: polygon.geoSeries[0].name,
            geoPoints: <GeoPoint>[]);
        for (final serie in polygon.geoSeries) {
          geoSerie.geoPoints.addAll(serie.geoPoints);
        }
        print(polygon.geoSeries[0].name);
        currentmove = new LatLng(
            geoSerie.geoPoints[0].latitude, geoSerie.geoPoints[0].longitude);
        statefulMapController.centerOnPoint(currentmove);
        statefulMapController.zoomTo(19);

        // final color =
        //     Color((math.Random().nextDouble() * 0xFFFFFF).toInt() << 0)
        //         .withOpacity(0.3);
        final poly = Polygon(
            points: geoSerie.toLatLng(ignoreErrors: true),
            color: Colors.transparent,
            borderStrokeWidth: 3.0,
            borderColor: color); // isDotted: true'
        polygons.add(poly);
        // setState(() => polygons.add(poly));
      }
    });
   
    geojson.endSignal.listen((bool _) => geojson.dispose());
    // The data is from https://datahub.io/core/geo-countries
    //final data = await rootBundle.loadString('assets/countries.geojson');
    final nameProperty = "ADMIN";
    unawaited(geojson.parse(json32, nameProperty: nameProperty, verbose: true));
  }`

**Comment by X-SLAYER** [comment]
the package don't have this feature , instead for me i make a method when i click on map it check if the point in polygon then it will be clicked

**Comment by Anup2712** [comment]
i have done infowindow
Refer [](https://github.com/johnpryan/flutter_map/issues/385)

**Comment by Anup2712** [comment]
i have done infowindow by onclick
[refer this link](https://github.com/johnpryan/flutter_map/issues/385#issuecomment-642601723)
