### ISSUE TITLE
Classic styles are no longer supported

### ISSUE THREAD

**Issue by jfajardo** [johnpryan/flutter_map#638]
I have this issue with MapBox
```
{
message: "Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"
}
```

**Comment by franciscofsales** [comment]
this is an update on mapbox really, not on this library, though the docs can be updated to reflect such changes.
You'll need to update the `additionalOptions` ID, such as:


`additionalOptions: {
            'accessToken':
                '',
            'id': 'mapbox.mapbox-streets-v8',
          },`

you can check more options at mapbox here: https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/

**Comment by johnpryan** [comment]
Thanks for answering @franciscofsales!
