### ISSUE TITLE
LatLng doesn't work

### ISSUE THREAD

**Issue by Nicolios** [johnpryan/flutter_map#658]
Hello,
I write here because the function LatLng doesn't work.
I just copy and past the "Open Street Map provider" on the github page.
The error is "The constructor returns type 'dynamic' that isn't of expected type 'LatLng'." and "Undefined class 'LatLng'."
Before I add flutter_map: any in my pubspec and run command "pub get".
That's not the first time I tried use LatLng but it's never work.
That's for your answer

**Comment by ibrierley** [comment]
Could you show the code using it (maybe just a minimal test example) and pubspec.yaml

**Comment by yuehernkang** [comment]
Had this problem too, i think it is because of the package 

import 'package:mapbox_gl/mapbox_gl.dart';

it has LatLng too
