### ISSUE TITLE
Map tiles not showing for zoom level 19

### ISSUE THREAD

**Issue by maro242** [johnpryan/flutter_map#670]
I need to display an offline map for which I got data from OpenStreetMap. Everything works great until I zoom in enough for the map to start loading tiles for zoom level 19, for which it only shows grey background. I do have the tiles for level 19 inlcuded in the project just like for other working zoom levels. So far, I have not found any cause for this problem. Is there some limitation to the package I am not aware of?

**Comment by maro242** [comment]
I figured it out. I was only setting maxZoom for MapOptions but not for TileLayerOptions, where it kept using the default value of 18.0. My bad.

**Comment by ch-muhammad-adil** [comment]
I am pretty much sure that options are being initialised properly. But let me give it a try..

**Comment by ch-muhammad-adil** [comment]
It is not working, it looks like it always works at maxZoom - 1 and grey out at maxZoom

**Comment by maro242** [comment]
Are you using a custom tile provider? Can you share some runnable code where this could be replicated?

**Comment by ch-muhammad-adil** [comment]
Yes i am using 


```
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_map/plugin_api.dart';
class CachedTileProvider extends TileProvider {
  const CachedTileProvider();
  @override
  ImageProvider getImage(Coords<num> coords, TileLayerOptions options) {
    return CachedNetworkImageProvider(
      getTileUrl(coords, options),
      //Now you can set options that determine how the image gets cached via whichever plugin you use.
    );
  }
}
```

**Comment by ibrierley** [comment]
I do think there's a bug (or two) in the main code (or something that's not clear at least)...a few suspicious bits...
```
maxZoom =
            wmsOptions == null && retinaMode && maxZoom > 0.0 && !zoomReverse
                ? maxZoom - 1.0
                : maxZoom,
```
in the TileLayerOptions, does this override, the options passed (if I try it, it seems to take the default of zoom 18 not mine of 17)?

Even if forcing a maxZoom internally, in _handlemove, _tileZoom becomes null, so we hit this line...

```
if ((tileZoom <= options.maxZoom) && (tileZoom >= options.minZoom)) {
```
So lets say tileZoom is 19 as zoomed too far, maxZoom is 18 (but wanted 17 anyway, but ignoring that problem)....so this is never true, so we do nothing abut it...(there is no "else" for that if).

This all feels a bit odd. I'm away from tomorrow, so won't have time to dig into this much I don't think, but I feel like these sections of code maybe need some double checking for the logic and initialization. (I haven't looked into the MapOptions maxZoom yet...)

**Comment by ch-muhammad-adil** [comment]
That is fine,, #1193
