### ISSUE TITLE
Unable to add new Marker / MarkerLayerOptions

### ISSUE THREAD

**Issue by EDToaster** [johnpryan/flutter_map#70]
Is there a way to add new Markers and remove markers from the Map when using the widget hierarchy?
I tried adding a MarkerLayerOptions to the map.layers variable, but I was unable to find a way to make the map update graphically.

If someone could tell me when/if this is implemented, I would be grateful!

(not sure if this is an issue)

**Comment by EDToaster** [comment]
Turns out by altering the layers of the Map, I am able to add/remove markers.

However, the only way of automatically updating the view (since after adding a new layer, the map must be updated to be able to see the effects) is to use the MapController, and moving the map slightly. 

This feels like a really bad way of doing things, is there something I am missing here?

**Comment by johnpryan** [comment]
We could look into alternatives to MapController.  For example, you could write a StatefulWidget that uses a MapController under-the-hood, but exposes a stateless API (e.g. calling setState() to set the map position)

Let me know if I'm understanding your question correctly

**Comment by johnpryan** [comment]
Closing as stale - calling setState() with the markers to display is the intended way of doing things
